### ISSUE TITLE
Hash matches are case sensitive

### ISSUE THREAD

**Issue by davehull** [VirusTotal/yara#1004]
Yara rules with hashes are case sensitive. The Yara documentation points this out, https://yara.readthedocs.io/en/v3.5.0/modules/hash.html, but users don't always read docs. Matching regardless of the case of a given hash should be supported.

**Comment by davehull** [comment]
I was referring specifically to creating yara rules that match files based on MD5 hashes. If a user puts in an uppercased MD5 hash, they won't get matches. Again the docs point out that hashes returned will be lowercase, but users and docs don't always mix. If it is not possible to tolower() hashes in user's yara rules, then close this issue. Thanks and cheers!

**Comment by wesinator** [comment]
> I’m assuming you’re talking about hash.sha256(0, file size) == “AABB...” which can’t support what you want. We have to pick one or the other and document it. To change this would alter every other string comparison done by that operator (==), including cases where you want case sensitivity.
> 

could you do the equivalent of a `toLower()` on the hash string passed in a condition, so the actual comparison would still use the lowercase, but the rule could be expressed in uppercase ?
