### ISSUE TITLE
inconsistent documentation of /-D/ CLI option

### ISSUE THREAD

**Issue by engerm** [VirusTotal/yara#1013]
**Version**: 

```
yara --version
3.8.1
```

**OS**:

```
cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

**Description**

The man for yara has two (2) entries for -D options. The pdf documentation for yara 3.8.1 ( for example on [https://media.readthedocs.org/pdf/yara/latest/yara.pdf]() ) is different that in man for the -D, and so is the readthedocs documentation ( [https://yara.readthedocs.io/en/v3.8.1/commandline.html]() ) different from the man for yara. 

It's unclear what the man -D option is supposed to be for - either for printing module data or printing stats.

**Steps**

1. Compile and install yara on CentOS
2. execute `man yara`. Output:

	```
       -D  --print-module-data
              Print module data.

       -g  --print-namespace
              Print namespace associated to the rule.

       -D  --print-stats
              Print rules' statistics.

       -s  --print-strings
              Print strings found in the file.
	```
	
	NOTE: there are two (2) option entries for -D.
3. Load the PDF documentation for yara 3.8.1, as seen on [https://media.readthedocs.org/pdf/yara/latest/yara.pdf]()
4. Locate the -D option (on page 72). 

	NOTE: -D references printing module data.

1. Load the readthedocs documentation ( [https://yara.readthedocs.io/en/v3.8.1/commandline.html]() )
1. Locate the -D option

	NOTE: -D references printing module data.

**Action Result**

* The man page for yara contains two (2) entries for -D
* The man page options for -D is different than the PDF documentation
* The man page options for -D is different than the readthedocs documentation

**Expected Results**

1. The man page for yara would only have one entry for the -D option
2. CLI options for yara would be consistent across all documentation - man page, PDF documentation, readthedocs, etc...

**Comment by plusvic** [comment]
Fixed in 017699102d018e858362828895794f2699730220
