### ISSUE TITLE
Is it possible to pass hex string to the function exported from custom module?

### ISSUE THREAD

**Issue by jhyeom26** [VirusTotal/yara#1014]
I'm writing a custom module,
and I want to export a function which compares byte stream in specific range of the file.

```c
import "my_module"
    rule test {
      condition:
        my_module.some_section_equal( {32 4B 2C} )
    }
```
This gives me a compile error message : syntax error, unexpected hex string, expecting ')'

Is there a way to pass hex string to the function?

**Comment by plusvic** [comment]
No, that can't be done, but you can pass a text string like "\x32\x4b\x2c", which is equivalent.

**Comment by jhyeom26** [comment]
thank you for your answer!
