### ISSUE TITLE
Regexp regression

### ISSUE THREAD

**Issue by deterb** [VirusTotal/yara#1018]
I've identified two regular expression engine regressions which are likely related.  The latest they work is in yara 3.6.3, the test cases break in 3.7.0 and continue to be broken in 3.8.1.  I'm unable to test against HEAD easily.

The first pattern set has the following test cases:
```c
// Passing cases
assert_true_regexp("(ba{4}){4,10}", "baaaabaaaabaaaabaaaabaaaa", "baaaabaaaabaaaabaaaabaaaa");
assert_true_regexp("(ba{2}a{2}){5,10}", "baaaabaaaabaaaabaaaabaaaa", "baaaabaaaabaaaabaaaabaaaa");
// Failing test cases (fail against 3.7.0, 3.8.1, pass against 3.5.0, 3.6.3)
assert_true_regexp("(ba{3}){4,10}", "baaabaaabaaabaaabaaa", "baaabaaabaaabaaabaaa");
assert_true_regexp("(ba{4}){5,10}", "baaaabaaaabaaaabaaaabaaaa", "baaaabaaaabaaaabaaaabaaaa");
assert_false_regexp("(ba{4}){4,10}", "baaaabaaaabaaaa");
```

The second pattern set has the following test cases:
```c
// Passing cases
assert_true_regexp("(bca{2}){4,10}", "bcaabcaabcaabcaa", "bcaabcaabcaabcaa");
assert_true_regexp("(bca{3}){3,10}", "bcaaabcaaabcaaabcaaa", "bcaaabcaaabcaaabcaaa");
assert_true_regexp("(bca{3}){3,10}", "bcaaabcaaabcaaa", "bcaaabcaaabcaaa");
assert_true_regexp("(bcaaa){4,10}", "bcaaabcaaabcaaabcaaa", "bcaaabcaaabcaaabcaaa");
assert_true_regexp("(bcaa{2}){4,10}", "bcaabcaabcaabcaa", "bcaabcaabcaabcaa");
// Failing test cases (fail against 3.7.0, 3.8.1, pass against 3.5.0, 3.6.3)
assert_true_regexp("bca{3}){4,10}", "bcaaabcaaabcaaabcaaa", "bcaaabcaaabcaaabcaaa");
```

I don't have access to a test environment here, but I did verify the transcribed regexps online.  I feel like there are some edge cases I missed from my initial testing, but this captures the bulk of what I'm seeing.  If I identify other different but relevant test cases which contribute, I'll add them.

**Comment by plusvic** [comment]
Good catch @deterb, this only happened with nested ranges {x,y} but not for all values of x and y.
