### ISSUE TITLE
Matches stores a non memory value as pointer

### ISSUE THREAD

**Issue by Tigzy** [VirusTotal/yara#1029]
Hello, 
From a crash dump, I've seen yr_string_matches_foreach returning a match pointer having 0x0001000000000000 value, which is non valid memory address => crash. 
Is it a value that reminds something? 

![image](https://user-images.githubusercontent.com/9531438/53578094-33570a00-3b77-11e9-9ba1-03ba2f14a498.png)

**Comment by plusvic** [comment]
Closing because this is too old.

**Comment by Tigzy** [comment]
No problem, haven't seen this lately anyway
