### ISSUE TITLE
Cannot build without static libraries

### ISSUE THREAD

**Issue by svidovich** [VirusTotal/yara#1036]
To reproduce, build by configuring with `./configure ... --disable-static ...`

This results in libyara.a being nonexistent during make, which causes make to fail.

**Comment by plusvic** [comment]
Can you provide the command sequence you used and its output?

**Comment by svidovich** [comment]
I was on a different machine that I don't have access to -- I can reattempt the build Monday and give you some output, but the gist was

`./configure --prefix=/usr --disable-static`
`make`
Which resulted in an ENOENT for libyara.a, if memory serves.

**Comment by worldofpeace** [comment]
We noticed the same issue in nixpkgs https://github.com/NixOS/nixpkgs/pull/73164#issuecomment-552206647, we used to workaround it by using a patch like https://github.com/andir/nixpkgs/commit/5f75f72497113001bbd464018db233fee13b0ed9.

**Comment by plusvic** [comment]
This issue should be solved by https://github.com/VirusTotal/yara/commit/04df811fa61fa54390b274bfcf56d7403c184404. Please re-open if the fix doesn't work for you.
