### ISSUE TITLE
Access violation in yr_compiler_create

### ISSUE THREAD

**Issue by StyleTec** [VirusTotal/yara#1040]
I don't know if this is an actual yara bug, but I am randomly getting access violation exceptions when calling "yr_compiler_create" function. I have used the engine in my C# .net project through the C++ CLR lib provided [here](https://github.com/Microsoft/libyara.NET).
When i activate exception handling for unmanaged code via "[HandleProcessCorruptedStateExceptions]" i can see, that the "yr_compiler_create" function raises the exception.

Sadly I was not able to reproduce an exact error condition yet, as the exceptions does occur randomly and rescanning a file that produces the error in the first place, does not raise them after.

Might be needed:
Got two systems, both virtual machines (one on a Hyper-V, the other on a VMware ESX host) that do have these issues.

**Comment by plusvic** [comment]
Can you provide more details about the error? Maybe a stack trace or error logs.

**Comment by StyleTec** [comment]
What i got back from the .net runtime is following:

Exception: System.AccessViolationException

StackTrace:
> at yr_compiler_create(_YR_COMPILER** )
> at libyaraNET.Compiler..ctor()
> at YaraScanner.analyzeMemoryStream(MemoryStream InpurtStream, String FileName)

TargetSite:
> Int32 yr_compiler_create(_YR_COMPILER**)

One more thing to say. The .net project is running as a windows service. Maybe this is useful...

**Comment by plusvic** [comment]
Unfortunately this is not very helpful. From that alone it's hard to tell if this is a problem with YARA itself or with the way the .net program interacts with YARA.

**Comment by StyleTec** [comment]
Yeah I know, but I've linked the code that is calling the yara function above. It is based in the compiler.h inside the libyara.Net folder of the repo. Maybe you could check if the calling is correct.

**Comment by sbruyere** [comment]
I've the exact same issue with the dnYara lib for .net. @StyleTec have you find a workaround ?
