### ISSUE TITLE
Yara hex pattern jumps issue

### ISSUE THREAD

**Issue by bahlaivlad** [VirusTotal/yara#1041]
I faced the issue in Yara hex patterns when using jumps (chunks of predefined length) at the end of hex expressions leads to a syntax error during rules compiling.

Here are some explanations. This rule compiles without any issues and works as well,
```yara
rule working_example { strings: $h = { 8D [2-3] 6A 04 ?? E8 ?? ?? ?? ?? } condition: $h }
```
while this rule leads to a syntax error:
```yara
rule non_working_example { strings: $h = { 8D [2-3] 6A 04 ?? E8 [4] } condition: $h }
```
Error while compiling the rule:
```
error: invalid hex string "$h": syntax error, unexpected '}', expecting _BYTE_ or _MASKED_BYTE_ or '(' or '['
```

I did not found any restrictions of using chunks of predefined length in the documentation. 
I built Yara using master branch with the last commit https://github.com/VirusTotal/yara/commit/becd6f0ea9de0772b71d7a8d9c3ccb849157bb7f and checked the issue. It is still present. Furthermore, the issue was present in previous versions of Yara (up to 3.7.0, I did not do further checks).

**Comment by plusvic** [comment]
This is known issue, see #481. For the time being it won't be fixed because it introduces some edge cases and a jump at the end of a string is usually unnecessary.
