### ISSUE TITLE
error: syntax error, unexpected _IDENTIFIER_ file.exe(1): error: non-ascii character

### ISSUE THREAD

**Issue by mstc-xqp** [VirusTotal/yara#1043]
time ./yara yara_rule3.yr 1ec7c393cbb96e84531c34d5ef9c2470cac3ee97_44b7d352y026ef7177875a6cb619d638f.apk
yara_rule3.yr(1): error: syntax error, unexpected identifier
yara_rule3.yr(1): error: non-ascii character

real	0m0.012s
user	0m0.008s
sys	0m0.003s

./yarac yaratest.rule yara_rule3.yr

compile with this rule

rule ExampleRule
{
    strings:
        $my_text_string = "text here"
        $my_hex_string = "b"
    condition:
        $my_text_string or $my_hex_string
}

**Comment by wxsBSD** [comment]
You have a non ascii character in your rule. Most of the time when I see this someone has copied a Unicode quote character on OS X.

**Comment by mstc-xqp** [comment]
how to fix it .I had tried dos2unix yaratest.rule  to reformat the code

**Comment by plusvic** [comment]
In the last version of YARA you must use -C option when passing compiled rules. See: https://github.com/VirusTotal/yara/commit/cd8284edf56739aa562e6d5127c4b1446e39ed8c

That's a security measure to prevent people from using compiled rules inadvertently. Maybe a more precise error message would be useful.

**Comment by wxsBSD** [comment]
Oh, my mistake! I didn’t realize you were using compiler rules.
