### ISSUE TITLE
exit code when some rule was triggered

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara#1044]
Is there some sort of porcelain option?
https://travis-ci.com/DanielRuf/clamav-test/jobs/186947143#L315 returns an exit code of `0`.

**Comment by plusvic** [comment]
yara returns exit code 0 on success, and 1 if an error occurs. Do you want a different exit code when a match occurs and and when it doesn't?

**Comment by DanielRuf** [comment]
> yara returns exit code 0 on success, and 1 if an error occurs

Well, how do I check then on CI if a rule was matched? Like we do with `yarn/npm audit` and so on.
References:
https://github.com/yarnpkg/yarn/pull/6819

https://travis-ci.com/DanielRuf/clamav-test/jobs/186947143#L316

Because `0` means everything is ok but I would like to get an exitcode of `1` or `> 0` when a rule is matched.

> Do you want a different exit code when a match occurs and and when it doesn't?

Exactly.

**Comment by plusvic** [comment]
YARA uses the POSIX convention for exit codes, and we shouldn't change it as it may break existing scripts. You can write some script that invokes YARA, check if it produces the expected output, and return an exit code accordingly.

**Comment by DanielRuf** [comment]
> check if it produces the expected output

Ok, sounds reasonable. Thanks for the feedback.
But it could be maybe an optional flag in the future to produce the needed exit code > 1.

**Comment by plusvic** [comment]
I considered adding a flag that changes the exit code behavior, but still I'm not convinced about this approach neither. It adds complexity to YARA for something that will be used in very specific scenarios that can be solved in some other ways.

**Comment by DanielRuf** [comment]
Understood. Many thanks for taking the time to answer my proposal / feature request.

**Comment by DanielRuf** [comment]
Hm, is this excepted (3.4.0)?

```
$ yara --version
yara 3.4.0
The command "yara --version" exited with 1.
```

Why do they all print the exit code `1` which would be an error or be sent to stderr?
