### ISSUE TITLE
host binary releases

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara#1045]
It would be great to have the binary releases hosted on GitHub too to make it easier to download the latest one automatically.

https://github.com/VirusTotal/yara/releases

Also prebuilt releases for other OS could be useful imo.

Because the current solution with Dropbox and others is not ideal.

Also relevant:
https://github.com/VirusTotal/yara/issues/841  
https://github.com/VirusTotal/yara/issues/993

**Comment by aurora-of-earth** [comment]
@DanielRuf Isn't the releases on GitHub just right now? so what's wrong?

**Comment by DanielRuf** [comment]
> Also prebuilt releases for other OS could be useful imo.

**Comment by DanielRuf** [comment]
Currently at least the Windows builds are now part of the releases page here on GitHub.

Closing as we can build the others with GHA.

**Comment by DanielRuf** [comment]
Reopening since I see that there is a new build setup with GitHub Actions and the question: could we not upload the artifacts of these builds to GitHub for every release / tag?

https://github.com/VirusTotal/yara/blob/master/.github/workflows/build.yml

**Comment by DanielRuf** [comment]
Still waiting for Linux binaries.
