### ISSUE TITLE
Unexpected no match on wide string containing null separators

### ISSUE THREAD

**Issue by wesinator** [VirusTotal/yara#1051]
Consider the following byte sequence (from "Naikon" malware):
`77 00 6F 00 72 00 6C 00 64 00 00 00 68 00 65 00 6C 00 6C 00 6F 00 00 00 6A 00 65 00 72 00 72 00 79 00 00 00 74 00 6F 00 6D 00 00 00 73 00 61 00 6E 00 64 00 79`

wide Unicode sequence of words also separated by null 0x00 values

I expected the following string rule to match on this, but it does not:
`$test = "world\x00hello\x00jerry\x00tom\x00sandy" wide`

Is there a reason wide strings do not also count and match strings including null separators ?

**Comment by wxsBSD** [comment]
Try testing on this:

```
77 00 6F 00 72 00 6C 00 64 00 00 00 68 00 65 00 6C 00 6C 00 6F 00 00 00 6A 00 65 00 72 00 72 00 79 00 00 00 74 00 6F 00 6D 00 00 00 73 00 61 00 6E 00 64 00 79
```

Your test data is missing the trailing null after the "y" in "sandy".

**Comment by wesinator** [comment]
Thanks @wxsBSD , that was it !
I knew there was something off about how I was testing
