### ISSUE TITLE
memory leak in yr_re_exec

### ISSUE THREAD

**Issue by teoring** [VirusTotal/yara#1054]
Hello,

I was running my program under AddressSanitizer and faced few reports regarding a memory leak in yr_re_exec.

At the moment I don't have much information, the call stack seems a bit too short for some reason. Compiled with debug symbols ( other reports ASAN found were reported with a full stack ). 

> =================================================================
==9195==ERROR: LeakSanitizer: detected memory leaks

> Direct leak of 72 byte(s) in 3 object(s) allocated from:
    #0 0x7f0346f63602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f0334e98179 in yr_re_exec (/usr/local/lib/libyara.so.3+0x39179)

> Indirect leak of 6240 byte(s) in 3 object(s) allocated from:
    #0 0x7f0346f63602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f0334e97a0e in yr_re_exec (/usr/local/lib/libyara.so.3+0x38a0e)

> SUMMARY: AddressSanitizer: 6312 byte(s) leaked in 6 allocation(s).
=================================================================

I am using YARA v. 3.7.1.
Ubuntu 16.04 LTS
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

Any advise how I can further investigate the issue?

**Comment by teoring** [comment]
I guess I will have to compile YARA library with ASAN to get more detailed stack traces.

**Comment by plusvic** [comment]
I'm closing this issue because it lacks details. If you have more information to share please re-open it.
