### ISSUE TITLE
MD5 forbidden in FIPS mode!

### ISSUE THREAD

**Issue by d1g1t4lumpia** [VirusTotal/yara#1065]
Hi,
I'm trying to compile YARA v3.10.0 on a FIPS-enabled system but get the following error:

===================================
   yara 3.10.0: ./test-suite.log
===================================

# TOTAL: 11
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-rules
================

md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!

FAIL: test-pe
=============

md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!

Has anyone run into this?

**Comment by plusvic** [comment]
YARA uses OpenSSL for certain features, and it looks like you can not build OpenSSL in FIPS mode. You can use `./configure --without-crypto` but it will be disable certain features.
