### ISSUE TITLE
ERROR:volatility.debug:Please install Yara from https://plusvic.github.io/yara/ 

### ISSUE THREAD

**Issue by Waterman178** [VirusTotal/yara#1079]
[6] pyrebox> %vol yarascan -K -Y cccc -D /home/water/Downloads/
ERROR:volatility.debug:Please install Yara from https://plusvic.github.io/yara/
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

[7] pyrebox> %tb
SystemExit Traceback (most recent call last)
/home/water/Downloads/pyrebox-qemu4.0/pyrebox/pyrebox/ipython_shell.pyc in ()
----> 1 get_ipython().magic(u'vol yarascan -K -Y -D /home/water/Downloads/')

/home/water/Downloads/pyrebox-qemu4.0/pyrebox_venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
2158 magic_name, _, magic_arg_s = arg_s.partition(' ')
2159 magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2160 return self.run_line_magic(magic_name, magic_arg_s)
2161
2162 #-------------------------------------------------------------------------

/home/water/Downloads/pyrebox-qemu4.0/pyrebox_venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
2079 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
2080 with self.builtin_trap:
-> 2081 result = fn(*args,**kwargs)
2082 return result
2083

</home/water/Downloads/pyrebox-qemu4.0/pyrebox_venv/local/lib/python2.7/site-packages/decorator.pyc:decorator-gen-153> in vol(self, line)

/home/water/Downloads/pyrebox-qemu4.0/pyrebox_venv/local/lib/python2.7/site-packages/IPython/core/magic.pyc in (f, *a, **k)
186 # but it's overkill for just that one bit of state.
187 def magic_deco(arg):
--> 188 call = lambda f, *a, **k: f(*a, **k)
189
190 if callable(arg):

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/pyrebox/ipython_shell.pyc in vol(self, line)
1733 pp_error("[!] The specified volatility command is not in the command list (%list_vol_commands)")
1734 return
-> 1735 self.vol_commandscmd
1736
1737 @line_magic

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/pyrebox/ipython_shell.pyc in vol_execute_command(cmds, cmdname, config, line)
142 # Register the help cb from the command itself
143 config.set_help_hook(functools.partial(vol_command_help, c))
--> 144 c.execute()
145 except Exception as e:
146 pp_error(

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/volatility/volatility/commands.pyc in execute(self)
145 return
146
--> 147 func(outfd, data)
148
149 def _formatlookup(self, profile, code):

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/volatility/volatility/plugins/malware/malfind.pyc in render_text(self, outfd, data)
340 if self._config.DUMP_DIR and not os.path.isdir(self._config.DUMP_DIR):
341 debug.error(self._config.DUMP_DIR + " is not a directory")
--> 342 for o, addr, hit, content in data:
343 outfd.write("Rule: {0}\n".format(hit.rule))
344

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/volatility/volatility/plugins/malware/malfind.pyc in calculate(self)
287 def calculate(self):
288 if not has_yara:
--> 289 debug.error("Please install Yara from https://plusvic.github.io/yara/")
290
291 addr_space = utils.load_as(self._config)

/home/water/Downloads/pyrebox-qemu4.0/pyrebox/volatility/volatility/debug.pyc in error(msg)
58 def error(msg):
59 log(msg, logging.ERROR)
---> 60 sys.exit(1)
61
62 def critical(msg):

SystemExit: 1

I have installed yara, and it tested successfully(total：11 pass:11), but it still can't be used.
I don't know what is going on.
os：debian 9.0 64bit

**Comment by plusvic** [comment]
This looks like an issue to be reported to Volatility, it seems that it doesn't find YARA for some reason, but I'm not familiar with how Volatility works.
