### ISSUE TITLE
Parse export addresses

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1081]
Hey,

There are a few cases where when looking at exports for DLLs I'd like to look at the address of the export in the file.

That way I could look for:

* DLLs where all or most of the exports actually point to the same location (see referenced screenshot)
* DLLs where an export with a particular name points to a location where it shouldn't (i.e in the case of one DLL impersonating another popular DLL)

Happy to explain more via some chat medium.

Cheers,
Tom

![image](https://user-images.githubusercontent.com/5901749/59449696-73c55580-8dff-11e9-8f89-8f5d56f4f597.png)

**Comment by wxsBSD** [comment]
I have something which does this which I will put up for your testing soon. Can you share the hash of the file which generated the above screenshot for my own testing?

One question I have is how it should be implemented. I see a couple of options:

1. Implement it as `pe.export_addresses` array of structures so you could then examine them like:
`for any i in (0..pe.number_of_exports - 1):
    (pe.export_addresses[i].offset == 0xaabb)`

2. Completely revamp `pe.exports`, which is currently a few functions, to be an array of structures so you could examine them like:
`for any i in (0..pe.number_of_exports - 1):
  (pe.exports[i].name == "foo" and pe.exports[i].offset == 0xaabb)`

3. The same as above but make it a new array of structures and deprecate `pe.exports()` with a warning.

4. Make it a new array, don't deprecate `pe.exports()`, and make `pe.exports()` walk the internal structures used by YARA that we would need to support an array.

**Comment by wxsBSD** [comment]
I'm going with the following:

`pe.exports()` will still exist in it's various forms.

Internally, exports (and imports) will no longer be stored in a list that is opaque to yara. Instead there will be the following for use in conditions:

`
  declare_integer("number_of_exports");

  declare_string("dll_name");
  begin_struct_array("export_details");
    declare_integer("offset");
    declare_string("name");
    declare_integer("ordinal");
  end_struct_array("export_details")
`

The `pe.exports()` functions will be converted to traverse the array described above, which will get us backwards compatibility.

**Comment by tlansec** [comment]
Just tidying up - this is now done via pe.export_details.
