### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by wxsBSD** [VirusTotal/yara#1102]
I've been toying around with the idea of a YARA formatter (think clang-format or gofmt) that would autoformat an input set of rules. My plan is something like:

1. Add a "debug" flag to the compiler that would have the compiler store all the components that make up the rule in their raw state. Regular expressions would be stored as raw text (along with the compiled state), same with conditions and other things which we lose when compiling rules. We would have to store things like filename (if one exists) currently being compiled, comments, and any other information necessary to recreate a properly formatted rule.

2. If rules are compiled with "debug" turned on then yr_compiler_get_rules() will not return a working rule set. This will ensure people can not save off rules in this bloated format.

3. Expose all that information "debug" information in yara-python.

4. Write yarafmt (I'm terrible with names) in python that would use all this new information and output a "properly" formatted set of rules. Obviously people will disagree about what "properly" means so the python code would need to be configurable.

The goal here is to allow the shops which have a lot of YARA rules to have an automatic formatter run that ensures rules are consistent. Right now it's very easy to get consistency on metadata, but very difficult to get consistent style in a collection of rules. I'm aware of plyara in this space but it is it's own project that runs the risk of being out of date easily as YARA evolves. My implementation would allow for the information to be consistent with each update to the compiler and the formatter can be maintained separately.

I'm happy to do the work, but just curious if you would consider this for inclusion or not.

**Comment by plusvic** [comment]
You may be interested in this https://github.com/VirusTotal/gyp

In VirusTotal we started working on this YARA parser precisely with the idea of building tools that are able to understand YARA's grammar without having to add complexity to YARA itself. The parser uses the same bison grammar than than YARA, so is relatively easy to keep both parsers in-sync when making changes.

I prefer the approach of maintaining a separate parser, one that can be easily integrated in your own program and that is flexible enough for multiple uses, that will be harder to accomplish by using the real YARA or would add too much complexity to it.

The drawback is that it's Golang, so you are tied to the Golang ecosystem, but that can be a good think for a commad-line tool like yarafmt, given that  Golang is good at producing statically compiled binaries for every operating system.

It would be great to have someone else interested in this project and contributing to it.

**Comment by wxsBSD** [comment]
Thanks for the pointer to gyp. I've never touched go before but have been looking for something that might get me started in it! I've also got someone on my team who wrote a (pretty good) yara formatter in go but it wasn't using the YARA grammar so it was more fragile than we wanted. I'm going to point him to gyp and we'll see if we can get a good formatter going.

I'm going to close this out as we look into gyp.
