### ISSUE TITLE
xor now work with nocase 

### ISSUE THREAD

**Issue by snorlax122** [VirusTotal/yara#1110]
its not find the xor string with when i add NoCase,
and, there is a way to ignore results of xor by 0?

**Comment by plusvic** [comment]
I don't get what you are trying to report about the nocase flag.

Regarding your second question: no, when you use the xor modifier with a string it returns a match if the original string is found (i.e. it was xored with 0), you can't ignore that case.

**Comment by snorlax122** [comment]
about the first one
**work:**
rule X
{
   strings:
      $x "This program" xor
}

**doesn't work**
rule X
{
   strings:
      $x "this program" xor nocase
}

and its not make sense so i report about it as a bug.

about the second one, yara rules meant to be a tool to detect malwares and a lot of researchers use it at the last version to find encoded malware strings and by "fixing" the xor tag to include the 0x00 key its again make no sense, lets take a look at the ex form the documentation:

> $xor_string = "This program cannot" xor

its will pop on every PE with or without encoded strings. 
so who can it help me?

**Comment by plusvic** [comment]
Now a I see what's happening. The problem here is that we you use the "xor" modifier without either "ascii" or "wide" the "ascii" modifier is not assumed by default. 

Also, I think you're right about the the "xor" modifier including the 0x00 by default may be a bad idea. 

I think could change the semantics of "xor" to something like this:

"xor" alone: only searches for strings XORed with something different from zero.
"xor" + "ascii": searches for both the original string and the XORed strings.
"xor" + "ascii" + "nocase": searches for the original string in case-insensitive mode or the XORed strings, also in case insensitive mode.
"xor" + "nocase": Searches for the XORed strings in case-insensitive mode. 

@wxsBSD, what do think about this?

**Comment by wxsBSD** [comment]
This makes sense. I can get a PR up which enforces this and has tests hopefully this weekend.

**Comment by snorlax122** [comment]
Its sound grate but I'm not sure its will get all the possibilities.
**let take a look at this:**
_file 1:_
"lol" as ascii
_file 2:_
"lol" as wide
_file 3:_ 
"lol" as xor wide
_file 4:_ 
"LOL" as xor ascii

if i looking for all of the files will set a rule like this:

> "LOL" xor wide ascii nocase

and its ok, but if i look for only file 3 and 4 there is no rule i can make.

i think the source of the problem is because we change the way we see the tags "ascii" "wide" and "nocase" from "how can the string represent" to "what the strings that can be"

for my opinion the right solution its to make the "xor" tag ignore the 0x00 key and the "ascii" "nocase" and "wide" just tell the way the xor string can be without adding new strings like its is now.

so if i looking for all the xor possibilities ill write something like this:

> $x_xor = "lol" xor ascii wide nocase
> $x = "lol" ascii wide nocase
> any of them

if i looking only for the xor string ill right it like this

> $x_xor = "lol" xor ascii wide nocase
> any of them

and its will work.

what do you think?

**Comment by wxsBSD** [comment]
@snorlax122 I'd appreciate it if you could test out my "xor_fixes" branch (which I put up as #1113). The branch is at https://github.com/wxsBSD/yara/tree/xor_fixes. I believe I've addressed all your concerns and have test cases which covers them but would appreciate it if you could let me know if it behaves like you expect.

As for making it print the xor key used... I thought about doing that when I originally wrote this but the xor byte is never actually kept by YARA anywhere. My thinking was that if you want to know the xor byte you can always script it with yara-python (or some other binding). You know the plaintext and the offset where the xor match happened so you can easily calculate the xor byte.

**Comment by snorlax122** [comment]
OK, i downloaded the project and build it. (i looked in the code and sow the function _yr_atoms_xor with a loop start from 1 so i think the publishing go right)

i made some tests files:
normalA:
**lol as ascii**
normalW:
**lol as wide**
xorA:
**lol as xor ascii**
xorW:
**lol as xor wide**
xorWUpperCase:
**LOL as xor wide**

i wrote a yara rule:

```
rule test1
{
    strings:
        $normalA = "lol" xor

    condition:
        $normalA
}

rule test2
{
    strings:
        $normalA = "lol" ascii xor

    condition:
        $normalA
}

rule test3
{
    strings:
        $normalA = "lol" wide xor

    condition:
        $normalA
}

rule test4
{
    strings:
        $normalA = "LOL" nocase xor

    condition:
        $normalA
}

rule test5
{
    strings:
        $normalA = "LOL" wide ascii xor

    condition:
        $normalA
}

rule test6
{
    strings:
        $normalA = "LOL" nocase wide ascii xor

    condition:
        $normalA
}
```

i run the rule with the new exe:

> yara-xor_fixes\windows\vs2017\Debug>yara64.exe testWithXor.txt files\
> test3 yara-xor_fixes\test\files\xorW.txt
> test5 yara-xor_fixes\test\files\xorW.txt
> test3 yara-xor_fixes\test\files\normalW.txt
> test5 yara-xor_fixes\test\files\normalW.txt
> test6 yara-xor_fixes\test\files\normalW.txt
> test1 yara-xor_fixes\test\files\xorA.txt
> test2 yara-xor_fixes\test\files\xorA.txt
> test4 yara-xor_fixes\test\files\xorA.txt
> test5 yara-xor_fixes\test\files\xorA.txt
> test2 yara-xor_fixes\test\files\normalA.txt
> test4 yara-xor_fixes\test\files\normalA.txt
> test5 yara-xor_fixes\test\files\normalA.txt
> test6 yara-xor_fixes\test\files\normalA.txt

as you can see, all the rules in the yara file are including the XOR tag, but there are rules that find a string in a "normal*.txt" files and its wrong.
the only rule that "work" is rule1 because i used only the XOR tag without ascii or wide.
**i think that the 'ascii'  and 'wide' tags are adding the original string again.** 
 
now lets look at the xor files.
if we ignore all the normal*.txt files we get this results:

> test1 yara-xor_fixes\test\files\xorA.txt
> test2 yara-xor_fixes\test\files\xorA.txt
> test3 yara-xor_fixes\test\files\xorW.txt
> test4 yara-xor_fixes\test\files\xorA.txt
> test5 yara-xor_fixes\test\files\xorA.txt
> test5 yara-xor_fixes\test\files\xorW.txt

its look good except one thing.
test6 should match with every Xor*.txt file and its not (include xorWUpperCase).


I am sorry I did not say this before so ill say its now, thank you very much for your help.

**Comment by wxsBSD** [comment]
> i think that the 'ascii' and 'wide' tags are adding the original string again.

This is the intended behavior now. Just the `xor` modifier by itself will not include the plaintext version of the string. If you want that you need to specify `xor ascii` or `xor wide`. Maybe I'm misunderstanding what you're saying?

Here's the implementation as I have it (and tests to back it up):

`xor` will search for the string with every single byte xor from 0x01 to 0xff. It does not include the plaintext string when searching.

`xor ascii` will search for the plaintext string and the xor strings.

`xor wide` will search for the plaintext wide string and the xor wide strings.

`xor wide ascii` will search for the plaintext ascii string, plaintext wide string and the xor versions of both.

In the interest of making this easier to do I've decided to make `xor nocase` an error in the compiler. This is because verifying the combination of xor and nocase is a lot more work to get right and I'm not sure it's worth the effort at this point.

Unfortunately I'm having a hard time understanding your bug report. Is it possible to provide me with a simple file to test with and a rule which does not behave like you expect when run against that file, along with a clear explanation of what you expect to happen.

**Comment by snorlax122** [comment]
i get it.

the way you choose to implement the XOR tag with the combination of ASCII and WIDE will allow to use it except one thing.
looking for XOR WIDE string without the unXOR string. its not perfect but fine.

about the `xor nocase` i think you did right. its make sense.

**Comment by wxsBSD** [comment]
> looking for XOR WIDE string without the unXOR string

Yeah, that's a good point and not one I have a great answer for right now. I confirmed this works, but it is less than ideal...

```
wxs@wxs-mbp yara % ./yara rules/test.yara tests/data/xorwideandascii.out
a tests/data/xorwideandascii.out
wxs@wxs-mbp yara % cat rules/test.yara
rule a {
  strings:
    $a = "T\x00h\x00i\x00s\x00 \x00p\x00r\x00o\x00g\x00r\x00a\x00m\x00 \x00c\x00a\x00n\x00n\x00o\x00t\x00" xor
  condition:
    #a == 255
}
wxs@wxs-mbp yara % ./yara rules/test.yara tests/data/xorwideandascii.out
a tests/data/xorwideandascii.out
wxs@wxs-mbp yara %
```

I also confirmed that all 255 matches are only the xor versions of the string, not the plaintext. Like I said, this isn't ideal but it will work.

**Comment by snorlax122** [comment]
yes, i think about the same solution this morning, its seams like we can write rule for any thing now and the xor 0x00 bin fixed, Im happy :)  thank you very much.

for now ill use your "xor_fixes" branch but its will be nice to know if this will implement in the next release of the main branch, pls let me know if it will.

this bug can be close 👍

**Comment by wxsBSD** [comment]
I don't know when it will make it in a release. This is @plusvic project, I just write things I need for it. He sets release dates and features. I've got a handful of things pending which I hope will make it in the next release. :)

**Comment by plusvic** [comment]
I've been thinking about the case in which you want to find the xored wide string without looking for the plain text version of the string, which can't be expressed right now. 

I'm wondering if it wouldn't be a better idea if we start supporting more powerful modifiers like `xor(0x00-0xFF)` for indicating that we want the string xored with all bytes from 0x00 to 0xFF (using `xor` without arguments would be equivalent to this for backward compatibility). If you don't want the plain text string you can use `xor(0x01-0xFF)`. 

Thoughts?

**Comment by wxsBSD** [comment]
I think that's a really good idea! I especially like that we will find the plaintext version by default for backwards compatibility to the current released version. I can have an implementation up hopefully by the end of this weekend.

**Comment by plusvic** [comment]
Thanks for volunteering! This will be a little more complicated as it requires some changes at the grammar level, but I think you already know the code base really well. Go for it.

**Comment by wxsBSD** [comment]
The suggested changes are up in https://github.com/VirusTotal/yara/pull/1132. Looking forward to the feedback, and apologies for the delay. My first attempt was terribly wrong and I needed a little extra time. :)
