### ISSUE TITLE
Define HAVE_* for public libyara headers

### ISSUE THREAD

**Issue by ahippo** [VirusTotal/yara#1115]
Public yara headers use several `HAVE_*` macros (`HAVE_STDBOOL_H`, `HAVE_CLOCK_GETTIME`, and others).
While building yara itself, they are defined on command-line using -D switches,
so everything works fine.

However, when building 3rd-party code against libyara, they are not defined anywhere,
which results in different set of declaration in yara headers.
For example, `HAVE_CLOCK_GETTIME` is defined during yara build itself, so `YR_STOPWATCH` gets `struct timespec`,
but when compiling against libyara `HAVE_CLOCK_GETTIME` is _not_ defined, so `YR_STOPWATCH` gets `struct timeval` instead.

I think `-DHAVE_*` defines used for building yara itself need to be made available in public headers -- either through shipping of config.h (and unconfig.h not to bleed into 3rd-party code) or through pkg-config file (would be nice to rename the macros to `YR_HAVE_*` not to interfere with similar-named 3rd-party HAVE_* macros).

I see that there were some issues with config.h in the past (#165, #541), but from a quick glance none of them seem unsolvable.

Also, regarding `YR_STOPWATCH`, can it be simply turned into an opaque structure (and only used by pointer), so that public API doesn't care about its size?

**Comment by plusvic** [comment]
If you are familiar with how to do this using pkg-config your contributions are welcomed. In the past we used a config.h file, but I'm not sure that's the best solution for this problem. The config.h file is generated by the ./configure script, gathering information from your own system, and is not supposed to be distributed.

I'm investigating how to do this with pkg-config, but haven't found anything so far.

**Comment by ahippo** [comment]
> If you are familiar with how to do this using pkg-config your contributions are welcomed.

Basically, I was thinking of adding required macros (determined at configure time), like -DYR_HAVE_STDBOOL_H -DYR_HAVE_CLOCK_GETTIME to Cflags field in [yara pkg-config file](https://github.com/VirusTotal/yara/blob/master/libyara/yara.pc.in#L11).

(macros are prefixed with YR_ since they are a part of public interface and so that they don't conflict with 3rd-party own macros of similar name)

> The config.h file is generated by the ./configure script, gathering information from your own system, and is not supposed to be distributed.

It shouldn't be distributed as part of source package.
But it affects libyara ABI, so it's a part of public interface of libyara library, and thus needs to be distributed within yara devel binary package (RPM/deb).

pkg-config file doesn't actually differ much from config.h -- both are generated at compile time, both carry the required macros, both are shipped within a binary package.

For example, glib does a similar thing by placing generated config.h under `/usr/lib64/glib-2.0/include/glibconfig.h`. (yes, /usr/lib64, not /usr/include, because it differs to different ABIs (like x86 vs x86_64)).
(for Ubuntu/Debian, the path is `/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h`)

Ideally, yara public ABI just shouldn't depend on availability of clock_gettime or something else, and use opaque YR_STOPWATCH, for example, or a platform-independent wrapper around timespec/timeval, which can fit any of those.

**Comment by plusvic** [comment]
I completely agree. But haven't found any reference on how to autogenerate the pkg-config file with the required macros. I'm not very familiar with pkg-config nor binary package generation, this part was contributed by someone else. That's why I'm calling for someone with more experience than me in this area.

Regarding the `YR_STOPWATCH` issue, I think this should solve the problem: https://github.com/VirusTotal/yara/pull/1125

With that change you can build your program with the YARA header files no matter if the library was built with `HAVE_CLOCK_GETTIME` or not.

**Comment by ahippo** [comment]
Oh, I see.

> Regarding the `YR_STOPWATCH` issue, I think this should solve the problem: #1125

Oh, that's great, thank you!
Out of all HAVE_* macros used in libyara headers, `YR_STOPWATCH` struct size was the most risky one.
