### ISSUE TITLE
YARA for a commercial training online/classroom

### ISSUE THREAD

**Issue by DeadlyHollows** [VirusTotal/yara#1123]
Hi,
    Great work guys! I really appreciate the project and the efforts you guys have put into it. We would like to use YARA for a commercial training online/classroom. So, I just wanted to clarify, if we acknowledge the source, would that be sufficient and covered under the terms of use?

Thanks.

**Comment by KeyJoo** [comment]
@DeadlyHollows hi. You can see about [license](https://github.com/VirusTotal/yara/blob/master/COPYING) file here. That it's **BSD 3-Clause "New" or "Revised" License**

### Permissions
- [x] Commercial use
- [x] Modification
- [x] Distribution
- [x] Private use

**Comment by DeadlyHollows** [comment]
Thanks for a quick reply. I had read the license, just wanted a confirmation from your side. We would be acknowledging the source.

Thanks.

**Comment by plusvic** [comment]
I'm late to this thread, but yes, you can do almost everything with YARA, including commercial use in the form of trainings.

**Comment by DeadlyHollows** [comment]
Thanks a lot again. We really appreciate your support.

**Comment by veryadrenergic** [comment]
> I'm late to this thread, but yes, you can do almost everything with YARA, including commercial use in the form of trainings.

How should one handle the inclusion of the YARA license and is it possible for there to be more than one license controlling the use of the binaries in someone's software package that is using YARA?

Of course it would not affect YARA itself but I'm wondering about controlling the license of a commercial product being copied, re-sold, re-distributed, etc. whereas such seems to be permitted in YARA's own license freely. So can one change this for their own software explicitly that is using YARA in some shape or form or no?
