### ISSUE TITLE
Absolute path for filenames sent to include_callback

### ISSUE THREAD

**Issue by malwarefrank** [VirusTotal/yara#1126]
Developing with libyara, is there an easy way to obtain the absolute path of the filenames passed to the include_callback function passed to compile()?  If there are multiple levels of includes, then the later calls only provide what was in the include statement.

For example, if /path/to/ruleset1.yar has an include statement for ruleset2.yar which in turn has an include statement for ruleset3.yar, then the first call to the include_callback function will be passed:
```
requested_filename="ruleset2.yar",
filename="/path/to/ruleset1.yar",
namespace
```
but the second call to the include_callback function will be passed:
```
requested_filename="ruleset3.yar",
filename="ruleset2.yar",
namespace
```
and a custom include_callback function has no way of knowing where those files are without keeping track of previous invocations of the function.

I am using yara-python, but it looks like this is coming straight from libyara.

**Comment by plusvic** [comment]
The purpose if the include_callback arguments is letting you program to fully control the include process, when the file `/path/to/ruleset1.yar` includes `ruleset2.yar`, the `ruleset2.yar` string could be anything, even something different from a file name. You could for example implement a callback that resolves something like `include "http://github.com/user/repo"`.

So, when you provide your own callback YARA doesn't make any assumption about the meaning of the argument passed in the include statement. If it is a path to a file, is the callback's responsibility to keep track of all the information required for locating further imports that could be relative to the previous file.
