### ISSUE TITLE
Main Docs Link Pointing to Old Docs

### ISSUE THREAD

**Issue by utkonos** [VirusTotal/yara#1131]
Visitors to `https://yara.readthedocs.io` are redirected to an old version of the documentation (3.8.1) rather than the current version. I'd suggest changing the link to point to `https://yara.readthedocs.io/en/stable/`. Then you don't need to maintain it.

<img width="849" alt="Screen Shot 2019-09-11 at 11 35 19" src="https://user-images.githubusercontent.com/2775739/64712115-a9262180-d488-11e9-978c-a50a859fd2da.png">
<img width="361" alt="Screen Shot 2019-09-11 at 11 35 49" src="https://user-images.githubusercontent.com/2775739/64712134-b17e5c80-d488-11e9-965e-07e2dc8c3771.png">

**Comment by plusvic** [comment]
Fixed.
