### ISSUE TITLE
What is the right way to increase the upper limit of parallel threads?

### ISSUE THREAD

**Issue by chenzhongxiang** [VirusTotal/yara#1148]
`libyara` hardcoded the upper limit of parallel threads was `YR_MAX_THREADS` in `/include/yara/limits.h` .
I tried to override this configuration out of curiosity，is my way:
```
#define YR_MAX_THREADS    (64)
#include <yara.h>
```
But it has serious consequences. I can't read any member in `YR_RULE` struct after compiled the rules, it's will cause segment fault. so what is the right way to increase the upper limit of parallel threads?

**Comment by plusvic** [comment]
Increasing the number defined by YR_MAX_THREADS should be enough. You should be able to change that number and run `make check` without issues. 

Can you provide more details about the steps you are following?

**Comment by chenzhongxiang** [comment]
Sorry, modifying the YR_MAX_THREADS macro will correctly increase the limit of parallel threads.
