### ISSUE TITLE
Rich Header incorrectly parsed for driver/sys files

### ISSUE THREAD

**Issue by computerate** [VirusTotal/yara#1149]
In module https://github.com/VirusTotal/yara/blob/master/libyara/modules/pe/pe.c there is an assumption that the Rich Header will start at offset 0x80, however it appears to start at offset 0x200 in several files identified, these all seem to be real mode device drivers.

E.g. a malicious and a bening example:
https://www.virustotal.com/gui/file/582ce3eea9c97d5e89f7d83953a6d518b16770e635a19a456c0225449c6967a4/content/hex
https://www.virustotal.com/gui/file/3593d3d08761d8ddc269dde945c0cb07e5cef5dd46ad9eefc22d17901f542093/content/hex

```
yara test.yara 3593d3d08761d8ddc269dde945c0cb07e5cef5dd46ad9eefc22d17901f542093 -D
pe
...
        rich_signature
                clear_data = UNDEFINED
                raw_data = UNDEFINED
                key = UNDEFINED
                length = UNDEFINED
                offset = UNDEFINED
...
```

**Comment by wxsBSD** [comment]
Sorry for the delay, I'm working on improving this code now.
