### ISSUE TITLE
files hit YARA even though they shouldn't

### ISSUE THREAD

**Issue by YuriRoz** [VirusTotal/yara#1151]
1093cb0315d26a09998f1a1a93ff1beb01b4a99130a000e255b1ec53113bd432 hit yara on VT hunting that had 

condition:
  (uint32(0) == 0xE011CFD0) and 
        (
        (any of ($a*)) and 
        (any of ($j*)) and 
        (not (2 of ($msi*))) and 
        (not (2 of ($utodesk*)))
        )

when clearly it does not begin with 0xE011CFD0.

**Comment by plusvic** [comment]
Notice that in VirusTotal the files are unpacked before applying the rules (both the original file and any derived files are scanned) so you can get matches for files that are not actually the original one, but some file extracted from it. In those cases you should see the tag `subfile` in the notification. Is that the case?

**Comment by YuriRoz** [comment]
Oh right! Didn't know it hits extracted stuff - Thanks. Is there a way to make the rule to not notify on subfiles?

**Comment by plusvic** [comment]
> Oh right! Didn't know it hits extracted stuff - Thanks. Is there a way to make the rule to not notify on subfiles?

Not now, but that feature is coming.
