### ISSUE TITLE
Loop Private Rules

### ISSUE THREAD

**Issue by utkonos** [VirusTotal/yara#1153]
It would be useful to have a condition like so: `for any i in (Rule1,Rule2,Rule3,Rule4) : ( i == 1 )`.

One may then have sets of TTP-based rules that can be iterated through and match if a certain threshold of TTPs match in the condition.

**Comment by plusvic** [comment]
I guess that you want to express that at least N rules from Rule1,Rule2,Rule3,Rule4 must be true. For the specific case of N=1, this can be done with `Rule1 or Rule2 or Rule3 or Rule4` but for N>1 there's no way to do it. Is this what you want?

**Comment by utkonos** [comment]
Yes, you are correct. The example I had used above is actually easy to write today. This is more what I'm looking to express: `any 2 i in (TTP1,TTP2,TTP3) : ( i == 1 )`.
