### ISSUE TITLE
Won't follow symbolic links/symlinks

### ISSUE THREAD

**Issue by github-pba** [VirusTotal/yara#1168]
yara 3.9.0 on Debian 10/x64

I want to scan recursively through a directory which collects multiple subdirectories referenced by a symlink:
```
/files/dir_a/...
/files/dir_b/...
/files/dir_c/...
[...]
/scanfiles/dir_a -> ../files/dir_a
/scanfiles/dir_c -> ../files_dir_c
```

Executing `yara -f -r /yrules/rules.yara /scanfiles/` does not match a single file and quits immedately.

I miss something like a `-F`-switch for `follow symbolic links`.

Is there a chance to see this in the future? Or any advice how I could follow symlinks (no, I won't do a `find ... -exec yara`, because this would be very slow because of process spawing)?

Thank you!

**Comment by wxsBSD** [comment]
There is no option to follow symlinks, but I just put up a diff which will follow symlinks by default now when scanning recursively. I debated on making it a separate option but I figured since scanning a single file already follows symlinks that this should just do the same.

**Comment by github-pba** [comment]
That's awesome, thank you. 

I did not look at your code yet, but did you keep in mind that when following symbolic links you have to limit the depth to avoid a denial-of-service against yara?

Imaging the following structure:
```
/path
/path/file1
/path/file2
/path/subdir -> /path
```

A possible solution could be tracking the length of the absolute file path and limit it either on a defined length (say, 256 chars) or depth (no more than 256 folders deep).

Ugh, that all sounds so ungrateful. You solve my problem, and I throw more potential problems at you. Sorry.

**Comment by github-pba** [comment]
OK, I tested your change, but it does not work.

Running yara with the code modifications given results in 

```
root@server:~/yara# ./yara -r /tmp/testrule /testdir
error scanning /testdir/subdir: could not open file
error scanning /testdir/usr_bin: could not open file
```

with `/testdir` containing:

```
root@server:~/yara# ls -l /testdir
total 172264
[...]
-rwxr-xr-x 1 root root   36478 Nov 29 09:08  aclocal
-rwxr-xr-x 1 root root   36478 Nov 29 09:08  aclocal-1.16
-rwxr-xr-x 1 root root   26704 Nov 29 09:08  addpart
-rwxr-xr-x 1 root root   31840 Nov 29 09:08  addr2line
-rwxr-xr-x 1 root root  432480 Nov 29 09:08  analog
-rwxr-xr-x 1 root root   56296 Nov 29 09:08  apropos
[...]
lrwxrwxrwx 1 root root       3 Nov 29 09:08  subdir -> /testdir
[...]
lrwxrwxrwx 1 root root 8 Nov 29 09:16 usr_bin -> /usr/bin

[...]
```

Symlinks pointing to directories result in an error message, not in descending the directory tree.

**Comment by wxsBSD** [comment]
Nice catch. I’ll see if I can get a fix for it in this week.

**Comment by github-pba** [comment]
Thank you very much. I highly appreciate your efforts.

**Comment by wxsBSD** [comment]
Sorry for the delay, I've updated the PR - please take a look and let me know what you think.

**Comment by github-pba** [comment]
Thank you for implementation. It's very useful im my case, and I hope others will not be bothered by this new functionality.

**Comment by marnao** [comment]
This feature bit me recently as I was testing out 4.0.2. We utilize symlinks quite a bit and this wreaked havoc in our testing. I thought yara 4.0.2 was really slow when it went on for hours, but it turns out I was just scanning tons and tons of data inadvertently.

As a workaround for anyone who wants to disable this feature (no official way to currently disable it):
Use the find command and limit to files only, output to a file
Use the new(ish) --scan-list argument to scan the files, sans symlinks.
