### ISSUE TITLE
ERROR_NOT_DOS_DISK on exe signature scan

### ISSUE THREAD

**Issue by d3v1l401** [VirusTotal/yara#1169]
Greetings!

I was hoping to find a solution on this issue which is basically blocking me from the final steps of my project: ERROR_NOT_DOS_DISK.
This error appears in the **yr_rules_scan_file** function call, by using LibYara.
If I scan ANY file, I wouldn't have any problem, but if I scan this large .exe (PE) file (I can't release it, sorry!) I receive this error.

What I noticed during the debugging of LibYara to figure out where the error might happen is that sometimes the scanner does hit a match on many of my rules on this target, but these doesn't get reported back to the callback at all.
I'm sorry I can't help you more than the details I have exposed, the debugging is a bit of a problem due to the scanner timeout.

To understand if I made a mistake or if it is a Yara problem, I used yara64.exe compiled under the Debug profile and tested it with the same target & set of rules: in this case, it does work wonderfully.

What could the problem be?
This is how I initialize the library:

```
if (yr_initialize() != ERROR_SUCCESS)
	return false;

if (yr_compiler_create(&g_compiler) != ERROR_SUCCESS) {
	return false;
}

FILE* _handle = nullptr;
fopen_s(&_handle, _pathToYaraDb.c_str(), "r");
if (!(_handle != NULL))
			return false;

if (yr_compiler_add_file(g_compiler, _handle, NULL, NULL) != 0) {
	return false;
}

if (yr_compiler_get_rules(g_compiler, &g_rules) != ERROR_SUCCESS) {
	return false;
}
```

The initialization function (above) returns true, meaning no errors are reported during the init process.

The scanning function:
```
auto _result = yr_rules_scan_file(g_rules, _pathToFile.c_str(), NULL, _defaultCB, (void*)&__lastFile, 0);
if (_result != ERROR_SUCCESS)
	return _result;
```

**Comment by plusvic** [comment]
Do you mean that you are getting `ERROR_NOT_DOS_DISK` from YARA? It's `yr_rules_scan_file` returning that error?

**Comment by d3v1l401** [comment]
So little update after my sickness, sorry for the wait.

I fixed the problem by passing 0 and disabling the debugging performance monitor (heap monitor and CPU profiling), this does not happen on my personal PC but happens at work, so it may be a specific situation.
