### ISSUE TITLE
Yara got stuck..Help please

### ISSUE THREAD

**Issue by riteshadg** [VirusTotal/yara#1179]
I am a newbie to Yara rules and hope someone could help me

My input file content is this:
**Titan**
ffgrsgsddsdrer**Titan**dfxvcxvfxgrs
**titan**

The rule I wrote is:
```
rule Titan
{ 
 strings:
  $name1="Titan"
  $name2="TiTan"
  $avoid1= /[0-9a-zA-Z]{3,}titan/ nocase
  $avoid2= /titan[0-9a-zA-Z]{3,}/ nocase
condition: 
 (any of them) and (not $avoid1) and (not $avoid2)
}
``` 

I want to identify if the string **titan** present in the input file.
If the term **`titan`** comes as a part of some other words, then I dont want that.
If the file contains the term _titan_ as standalone and also the same file contains the term _titan_ as a part of another word, then only the standalone term should be the part of output and avoid the other.

Any help or guidance will be greatly appreciated.

**Comment by plusvic** [comment]
You should use the `fullword` modifier. See: https://yara.readthedocs.io/en/latest/writingrules.html#searching-for-full-words
