### ISSUE TITLE
Feature request - internal error verbosity

### ISSUE THREAD

**Issue by MalPunch3r** [VirusTotal/yara#1196]
I received an `internal error: 46` the other day when trying to run a ruleset. The problem was there were thousands of rules combined into a single .yara file and it ended up being quite a pain to find the offending rule. It ended up being that the rule would not run with yara version 3.8.1. It did however run fine with the latest release. I am not able to upgrade the toolset using that outdated version myself. 

Even though the rule works fine with the latest release of yara, if an internal error within yara occurs like this in the future, it would be nice to be as verbose as possible to show the potentially offending rule.

**Comment by plusvic** [comment]
This is a long-standing problem that is difficult to fix due to the way rules are structured. I've been myself in your shoes and debugging cases like this one is a pain, but unfortunately I don't foresee this issue being solved for now.

**Comment by MalPunch3r** [comment]
ok cool - thanks for taking a look.
