### ISSUE TITLE
Cannot include yara rule from within another rule

### ISSUE THREAD

**Issue by kuzenko** [VirusTotal/yara#1198]
The documentation says that 

> The base path when searching for a file in an include directive will be the directory where the current file resides.

I have one file that I am including "helloWorld.yar" with contents:
```
include "ransomeware.yar"

rule HelloWorldMalware
{
    meta:
        description = "Hello world malware"
        author = "Kuzenko"
        info = "AlphaCrypt Ransomware"
    strings:
        $h = "hello"
        $h2 = "world"
    condition:
        $h and $h2
}
```

I have another file "ransomeware.yar":
```
import "hash"

rule IsPE
{
  condition:
     // MZ signature at offset 0 and ...
     uint16(0) == 0x5A4D and
     // ... PE signature at offset stored in MZ header at 0x3C
     uint32(uint32(0x3C)) == 0x00004550
}

rule TrojanDownloader:hash
{
    condition:
       not IsPE and filesize < 350KB and hash.md5(0, filesize) == "18ad8211981cc91e2fd3bce8c7ea3001"
}
```

I am trying to load only first file "helloWorld.yar" and it tries to include the second one. The error that I am getting is: "Error: can't open include file: ransomeware.yar". I am using yr_compiler_add_file() method to add the rule.

The interesting thing about that is if I write include path relative to the executable for these rules then it works. Another case if I try to use include callback, what I see is that it is calling and I am returning path where both my rules are located and I am getting errors:
```
Error in file: ransomeware.yar, at line 1
Error: syntax error, unexpected regular expression 
```

When I am trying to call yara from the command line everything is working file, it is included without any errors and finding malware.

Version of yara: 3.11.0 builded from source
Mac OS: Mojave 10.14.6
Cmake: 3.13.3
Apple clang version 11.0.0 (clang-1100.0.33.12)

**Comment by wxsBSD** [comment]
The include callback needs to return the content of the included file, not the path to it.

**Comment by kuzenko** [comment]
Thanks, now it works.
