### ISSUE TITLE
"not" keyword isn't working with rules referencing

### ISSUE THREAD

**Issue by chunk734** [VirusTotal/yara#1203]
I tried multiple yara rules where using "not" keyword while rule referencing is not working in the desired manner. Eg-

rule r1
{
strings:
           $str1 = "xyz"

condition:
           $str1
}

rule r2
{
strings:
           $str2 = "abc"

condition:
           $str2
}

rule r3
{
condition:
           r1 and not r2
}

**Comment by plusvic** [comment]
I've tested the rules above with a file containing only "xyz" and it works as expected, both `r1` and `r2` match. If I add "abc" to the file `r1` and `r2` match, but not `r3`. Can you provide more details about what you are doing for testing?
