### ISSUE TITLE
Large files scan with no rules slows down yara

### ISSUE THREAD

**Issue by nikolay-n** [VirusTotal/yara#1213]
When I'm trying to scan folder with a large files generated by 
`dd if=/dev/urandom of=test_file.mp4 bs=1048576 count=330` command with empty rules file, it slows down yara for some reason

```
bash-3.2$ ls -la
total 6785024
drwxr-xr-x   4 admin  staff         128 Feb  7 21:50 .
drwxr-xr-x  13 admin  staff         416 Feb  7 21:10 ..
-rw-r--r--   1 admin  staff           0 Feb  7 21:50 test.yar
-rw-r--r--   1 admin  staff  3460300800 Feb  7 21:48 test_file.mp4

bash-3.2$ yara -v
3.10.0
bash-3.2$ time yara test.yar test_file.mp4

real	0m6.326s
user	0m5.729s
sys	0m0.589s

```

Do anyone know the reason of such behavior? Thanks!

**Comment by nikolay-n** [comment]
It's looks like the calculation of the sha1
```
bash-3.2$ time shasum -a 1 test_file.mp4
8b44048c82128ff69abf24439b9af3bd635769a0  test_file.mp4

real	0m6.528s
user	0m5.752s
sys	0m0.731s
bash-3.2$ time md5 test_file.mp4
MD5 (test_file.mp4) = bbb55247753671b1565bb49280c4c8ff

real	0m6.487s
user	0m6.393s
sys	0m0.834s
```

**Comment by wxsBSD** [comment]
It’s not the sha1. I don’t believe yara is calculating any hash unless you ask it to, and with an empty rules file you are not asking it to.

What I think is going on is YARA is still iterating over the chinks of the file, even though doing so is pointless (there is no rules so there are no strings to search for). I noticed this when I was doing some work a few years ago but decided against fixing it because the edge case of no rules and/or no strings is likely rare in the real world.

I don’t recall the size of the chunks being used but you asked it to scan a 3.4GB file, that’s going to take some time.

**Comment by nikolay-n** [comment]
I've look through the source and you are right. And now I'm trying to figure out how to break the scan, to not read the whole file to the end.
command `yara --max-rules=1 test.yar test_file.mp4`
test.yar with the rule 
```
rule Test {
    strings:
        $s1 = { ?? }
    condition:
	    $s1 at 0
}
```
doesn't stop the process

**Comment by nikolay-n** [comment]
My World Will Never Be The Same :( 
I've never look at yara sources and I thought it's well optimized at rule level. When I'm asking to look at some offset or range for some data and no other operations that requires full file scan, yara knows that no need to read all the file. I'm very frustrated.

**Comment by wxsBSD** [comment]
Your thinking rather narrowly. In the real world people run with many rules and all kinds of different strings and conditions. In your case there is an optimization made (it only searches for your string at a specific offset) but it still iterates over the entire file in chunks. Optimizing for that case in your contrived example probably doesn’t buy you much in real world workloads.

**Comment by nikolay-n** [comment]
I'm using yara in different stages, file types detection and detected formats rules, scanning the first N bytes to detect file type using buffer scan improve performance a lot. @wxsBSD thanks for your comments. In general I understand if there are a lot of rules the best way to scan sequentially.

**Comment by veryadrenergic** [comment]
> I'm using yara in different stages, file types detection and detected formats rules, scanning the first N bytes to detect file type using buffer scan improve performance a lot. @wxsBSD thanks for your comments. In general I understand if there are a lot of rules the best way to scan sequentially.

What I do is I have rules organised by malware type, malware family and variant whilst specifying the intended file format the rule is to be included in scans for. During the loading of the rules, this data is processed and a rule is ignored or included in a set of rules at startup depending on what file format the scanner instance that'll be using that set of rules is for.

I determine the file format outside of YARA and scan files with the appropriate scanner instance which will rely on a set of rules specifically intended to be used for that file format.

This means I never have to check the file format in any of my rules and no rules not intended to be used when scanning a file with a specific file format are used unless appropriate.
