### ISSUE TITLE
Yara performance with shared strings vs private rule

### ISSUE THREAD

**Issue by Solumnant** [VirusTotal/yara#1223]
I haven't been able to find anything in the performance documents about this, but I was wondering whether placing strings that are common across multiple yara rules in a public rule would actually improve performance and memory usage, or whether the compilation process already performs these optimizations on it's own if it detects identical strings across different rules.

For instance, if I have 20,000 rules that have the string  $a1= "Microsoft", would it help performance at all to have a private rule that searches for that string, and for all 20,000 of my rules to use the private rule within their condition?

I know this would be better for organization (and probably compilation speed), but the question specifically concerns performance and memory usage after compilation has already occurred.

Edit: The reply by @plusvic here: https://github.com/VirusTotal/yara/issues/625#issuecomment-288650622 seems to imply that identical strings are optimized away by only stating that $str and $str2 are recognized as different, but I would appreciate some clarification.

**Comment by plusvic** [comment]
Yes, if you have 20,000 rules that have the string "Microsoft" it would be beneficial both in terms of speed and memory usage to put it in a separate rule and use that rule in the condition of the remaining ones. Every time you declare a string in a rule it's handled as a different string, even if they are identical. By moving the common string to a separate rule you are effectively removing 19,999 strings from the final compiled rules. I have the intention of optimizing this behavior some day, but so for far it works like that.

The comment https://github.com/VirusTotal/yara/issues/625#issuecomment-288650622 is about different topic. That thread was about the number of matches stored for a particular string during the  scanning phase.
