### ISSUE TITLE
Metadata Values are Unescaped

### ISSUE THREAD

**Issue by malvidin** [VirusTotal/yara#1242]
For any metadata string that contains "\x00", that value and any following data is dropped. I found this while attempting to work around the XOR limitations mentioned in #1235 (Provide XOR keys in results), which is unreasonable to address. 

Metadata strings that are unescaped to non-ASCII strings ("\x80" - "\xFF") caused issues with yara-python (Python 3.8, yara-python 3.11.0, Windows), where Python crashes with `Process finished with exit code -1073741819 (0xC0000005)` when the rule compilation is tried. 

YARA also ignores metadata strings at and after any '\x00' character position, which is unescaped to NULL.

For example, if the metadata includes this:
`    xor_pt_a_xor  = "\"\\\t\n\x00AA\nAA👍\x80"`

The metadata strings gets returned as one of the following:
`xor_pt_a_xor="\"\\\t\n"  # yara 3.11.0 binary`
`'xor_pt_a_xor': '"\\\t\n'  # yara-python 3.11.0, if the \x80 is removed`

I expect the meta values to be returned without modification, some like this:
`xor_pt_a_xor="\"\\\t\n\x00AA\nAA\xF0\x9F\x91\x8D\x80"  # yara 3.11.0 binary`
`'xor_pt_a_xor': '\\"\\\\\\t\\n\\x00AA\\nAA\\xF0\\x9F\\x91\\x8D\\x80'  # yara-python 3.11.0`
Or if UTF8 is maintained:
`xor_pt_a_xor="\"\\\t\n\x00AA\nAA👍\x80"  # yara 3.11.0 binary`
`'xor_pt_a_xor': '\\"\\\\\\t\\n\\\\x00AA\\nAA👍\\x80'  # yara-python 3.11.0`

```
import yara

mydata = b"\"\\\t\n\x00AA\nAA\xf0\x9f\x91\x8d\x80"
myrule = r'''
rule thumbs_up
{
  meta:
    xor_pt_a_xor = "\"\\\t\n\x00AA\nAA👍\x80" 
    plugin = "xor"
  strings:
    $a_xor="\"\\\t\n\x00AA\nAA👍\x80" xor
  condition:
    all of them
}
'''

yr = yara.compile(source=myrule)

yml = yr.match(data=mydata)
print(yml[0].meta)
assert(yml[0].meta['xor_pt_a_xor'] == '\"\\\t\n\x00AA\nAA👍\x80')
```

**Comment by plusvic** [comment]
Fixed in `yara-python`
