### ISSUE TITLE
Feature for printing Yara function return values

### ISSUE THREAD

**Issue by strictlymike** [VirusTotal/yara#1247]
I'd like a command-line switch similar to `--print-function-retvals`.

For purposes of discovering how Yara works and how to build effective rules, I would find it useful to know what functions like `pe.section_index()` return for binaries that don't contain the referenced section names, Something similar to `--print-module-data` but for when we call Yara functions, might help me figure out how Yara behaves when it encounters the corner cases I'm anticipating, so I can build rules that cope with those scenarios.

**Comment by dzzie** [comment]
the solution i have been using is a pe.dbg function to dump values https://github.com/VirusTotal/yara/issues/1221

You can also (ab)use it for quick and dirty sample profiling

```c
import "pe"
import "math"

rule test
{
     condition:
        for all i in (0 .. pe.number_of_sections -1):(
            pe.dbg( 
                pe.sections[i].name,
                math.entropy(
                    pe.sections[i].raw_data_offset, 
                    pe.sections[i].raw_data_size
                )
            )
        )	
}
```
