### ISSUE TITLE
Got error "error scanning xxxx.txt: error: 34"?

### ISSUE THREAD

**Issue by chuanjiesun** [VirusTotal/yara#1252]
when I use yara to detect some files with compiled rules, THIS ERROR occured.  
yara: v3.9.0 branch on 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64，is there any way to solve this error?

**Comment by wxsBSD** [comment]
Error 34 is unknown module. You wouldn't happen to know what modules are imported, would you?

**Comment by plusvic** [comment]
This error usually occurs when you compile your rules with one version of YARA that was built with support for a certain module and those compiled rules are later loaded with another version than was compiled without support for that module.
