### ISSUE TITLE
Removing Deprecated Functions

### ISSUE THREAD

**Issue by malvidin** [VirusTotal/yara#1258]
Will either of `yr_finalize_thread` (deprecated since 3.8) and `entrypoint` (deprecated since 3.0) be removed from YARA 4.0?

**Comment by plusvic** [comment]
Thank you for pointing it out. In fact this function was already removed from the code, but it was still mentioned in the documentation. Removed in a0fdda7a472cf162e399a479b8dbd0db0cf8526c
