### ISSUE TITLE
Documentation Missing for Python Config "max_match_data"

### ISSUE THREAD

**Issue by malvidin** [VirusTotal/yara#1259]
Merged pull 121 from @kevin-haynie in yara-python adds the `max_match_data` configuration option to `yara.set_config`, but this behavior has not been added to the Python documentation at https://github.com/VirusTotal/yara/blob/master/docs/yarapython.rst.

> Synchronize call to python's get_config with that of yara core library.
https://github.com/VirusTotal/yara-python/pull/121

**Comment by plusvic** [comment]
Done in 1ed9e1bb0a3cf9cce93cd14889f7c15dd8941bce
