### ISSUE TITLE
I want to compile yara by adding androguard module in windows

### ISSUE THREAD

**Issue by roopeshiitd** [VirusTotal/yara#1273]
Hi,
I want to compile yara by adding androguard module in windows as I would like to use yara on windows. But I could see from the documentation that for windows pre compiled libraries were given and compiling source code steps were given for debian system. Can you please help guide me how to compile it and install on windows?

**Comment by plusvic** [comment]
Take a look at the instructions in Androguard's page: https://github.com/Koodous/androguard-yara#preparing-compilation.

**Comment by roopeshiitd** [comment]
Thank you plusvic. Actually I have already went through the documentation. They gave the instruction just to recompile the yara source code by adding androguard.c to modules and modifying the makefiles. 
./bootstrap.sh
./configure --enable-cuckoo
make
make install

The above commands are for linux right? I want to build the source code in windows and use yara on windows. Can you please help me with that.

**Comment by plusvic** [comment]
Oh, sorry. In Windows you need to add the `androguard.c` to the Visual Studio project, and the `MODULE(androguard)` line to `libyara/modules/module_list`. I think that you should be enough.

**Comment by roopeshiitd** [comment]
Thanks a lot plusvic. That worked! I could use it through command line. Can you please help how to add the androguard module in yara-python python library as well? I would like to make scripts in python.
