### ISSUE TITLE
ERROR_INCLUDE_DEPTH_EXCEEDED thrown with 1 level of depth

### ISSUE THREAD

**Issue by avanbrunt-cb** [VirusTotal/yara#1279]
I was trying to use the `index.yar` file from https://github.com/Yara-Rules/rules which contains close to 450 includes however the file does not go beyond a depth of 1 or 2. The ERROR_INCLUDE_DEPTH_EXCEEDED is thrown around line 56 of the `index.yar` file which seems like an odd location to trigger such an error. Investigating the file and removing various groups of includes from the file I was able to get a successful compile at various amounts of includes.

Through the investigation, I noticed a pattern when a particular group of includes that was indicated by shared folder exceeds 16 files there would be a failure within that group. When I reduced a group that triggered the depth error to below 16 items, I would receive a compilation error instead indicating that something is wrong within last file. This leads me to believe that the ERROR_INCLUDE_DEPTH_EXCEEDED error is masking compilation errors because the `file_name_stack_ptr` is not being properly decremented when a particular include fails with an error. In these cases as well, yara is not terminating early if a particular include fails for with an error.

Not sure what the intended design is but the ERROR_INCLUDE_DEPTH_EXCEEDED is confusing and does not match the errors that are occurring within the yara rules file.

**Comment by plusvic** [comment]
Can you provide more information for reproducing the bug? I'm trying with the last version of the rules in that repository and don't get the ERROR_INCLUDE_DEPTH_EXCEEDED error. If you can provide the YARA version number and a zip, the command line you are using, and a zip file containing the files that produce the errors they will be welcomed.
