### ISSUE TITLE
scanning timed out error

### ISSUE THREAD

**Issue by p-g-krish** [VirusTotal/yara#1283]
when run this command

> yara -r juicy_files.txt D:\program_files

facing below error

```
error scanning D:\program_files\Android\platform-tools\NOTICE.txt: scanning timed out
error scanning D:\program_files\Android\platform-tools\sqlite3.exe: scanning timed out
```

**Comment by plusvic** [comment]
This happens with YARA rules that are particularly slow. You can either improve the performance of your rules or change the default timeout with the `--timeout` argument.
