### ISSUE TITLE
yarac tool with cutom modules

### ISSUE THREAD

**Issue by marcocereda** [VirusTotal/yara#1284]
Hi yara creators,
I have compiled yara version 3.11.0 following "Writing your own modules" instructions on how to include non standard modules. Actually, I have installed yara adding known modules such as "manape" and "androguard". Now the problem is that yara tool seems to act fine with the added modules, while yarac tool returns "error: unknown module "manape"" when trying to compile rules.
Am I missing something or yarac tool doesn't work with added modules?
Thank you in advance.

Marco

**Comment by plusvic** [comment]
It's strange that `yara` works fine with rules that import the "manape" module but `yarac` does not. I would double check that the version of `yarac` is the one that was recompiled with the non standard modules.

**Comment by marcocereda** [comment]
Ok I’ll check, thank you.
