### ISSUE TITLE
What does error code "error: 29" stands for?

### ISSUE THREAD

**Issue by marcocereda** [VirusTotal/yara#1285]
Hi yara creators,
I am currently using yara 3.11.0 and I am writing to ask the description of the following scanning error:
- "error scanning FileName.tmp: error: 29"

Thank you in advance
Marco

**Comment by securitykitten** [comment]
Errors can be looked up under `libyara/include/yara/error.h`

In 3.11.0 error 29 is set as 
```
#define ERROR_INVALID_ARGUMENT                  29
```

**Comment by marcocereda** [comment]
Thank you very much
