### ISSUE TITLE
Better way to handle failing lookups in `OP_OBJ_FIELD`?

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#1288]
I recently got a bug report https://github.com/hillu/go-yara/issues/70 about a failed assert() in `exec.c`. It turned out that the libyara for compiling included OpenSSL support and the libyara for scanning did not which led to `pe.number_of_signatures` being unavailable at scan time which led to the scan program being aborted through `assert()`.

Perhaps there should be a better way to handle this situation. On the other hand, if this is intended behavior, it should probably be documented.

Easy steps to reproduce on Linux:
```
$ ( mkdir build-crypto && cd build-crypto && ../configure && make )
[…]
$ ( mkdir build-nocrypto && cd build-nocrypto && ../configure --without-crypto && make )
[…]
$ cat t.yar
import "pe"
rule t { condition: pe.number_of_signatures >= 0 }
$ ./build-crypto/yarac t.yar t.yac
$ ./build-nocrypto/yara -C t.yac /dev/null
yara: ../../libyara/exec.c:889: yr_execute_code: Assertion `r1.o != NULL' failed.
Aborted
```

**Comment by plusvic** [comment]
I think we can return an error instead of aborting the program. You still won't be able to use rules compiled with OpenSSL support with a version of YARA that doesn't support it, but at least the error won't be so catastrophic.
