### ISSUE TITLE
[ADDING] New company which use your solution

### ISSUE THREAD

**Issue by vincent-guesnard** [VirusTotal/yara#1291]
Hello,

Javier Ramirez from VirusTotal asked us to open an issue about this .. Well, that's not a issue at all.

Thanks for all the work you did and do, it's an amazing jobs.

Our company use your solution since 3 years - we would be glad to be within the company list : www.touchweb.fr / TouchWeb - as you proposed in the README.

Thanks for all,

Kind regards,

Vincent

**Comment by plusvic** [comment]
Added in 9a3b4e3d7d246df9cadd43420d24195a7a7ea758. Thank you very much for your feedback!
