### ISSUE TITLE
Bug in error compilation output

### ISSUE THREAD

**Issue by lprat** [VirusTotal/yara#1296]
Hi,

Since yara v4.0 (and 4.01), there is a bug in the compilation stderr return. 
It's problem for me, because i use this return for add missing externals variables..

Use this rules: https://raw.githubusercontent.com/lprat/static_file_analysis/master/yara_rules1/chm.yar

Version 4.01
>>> import yara
>>> yara.compile(filepath="chm.yar",externals={})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(56): undefined string "$chmmagic"
>>> 

Now, i use old version 3.11.0:
>>> import yara
>>> yara.compile(filepath="chm.yar",externals={})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(56): undefined identifier "FileType"
>>> yara.compile(filepath="chm.yar",externals={'FileType': ''})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(56): undefined identifier "PathFile"
>>> yara.compile(filepath="chm.yar",externals={'FileType': '', 'PathFile': ''})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(56): undefined identifier "CDBNAME"
>>> yara.compile(filepath="chm.yar",externals={'FileType': '', 'PathFile': '', 'CDBNAME': ''})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(43): undefined identifier "chm_file_bool"
>>> yara.compile(filepath="chm.yar",externals={'FileType': '', 'PathFile': '', 'CDBNAME': '', 'chm_file_bool': ''})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: chm.yar(43): undefined identifier "FileParentType"
>>> yara.compile(filepath="chm.yar",externals={'FileType': '', 'PathFile': '', 'CDBNAME': '', 'chm_file_bool': '', 'FileParentType': ''})
<yara.Rules object at 0x7ff678455620>
>>> 

Thanks for you help.
Lionel

**Comment by lprat** [comment]
I just compiled yara from today's github repository. It works! I'll wait for the next release!
Thanks.

**Comment by plusvic** [comment]
So this issue can be closed right?

**Comment by lprat** [comment]
Yes! Thanks.

**Comment by timthurner** [comment]
Hi im trying to use the same repo with the same output as @lprat is there any workaround ?
