### ISSUE TITLE
Yara 4.0.0 and 4.0.1 break compatibility with macho module

### ISSUE THREAD

**Issue by melina-delgado** [VirusTotal/yara#1298]
I was just upgrading from Yara 3.x to Yara 4.x. I use the macho module. I ran `./configure --enable-macho` for both versions. Yara 4.0.1 returned the following error on `make check`:
```
==================================
   yara 4.0.1: ./test-suite.log
==================================
 
# TOTAL: 14
# PASS:  13
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
 
.. contents:: :depth: 2
 
FAIL: test-macho
================
 
failed to compile rule << import "macho" rule test { condition:     macho.cputype == macho.CPU_TYPE_X86 } >>: line 1: invalid field name "cputype"
```

Yara 4.0.0 did not error on `make check`, but when I try to import the module I get the following error: `rules/helpers.yar(3): error: unknown module "macho"`

Any advice on how to resolve these issues?
Thanks,
Melina

**Comment by HydraDragonAntivirus** [comment]
Similar issue.
