### ISSUE TITLE
yara-python match causes segmentation fault 

### ISSUE THREAD

**Issue by Neo23x0** [VirusTotal/yara#130]
I used the actual sources and compiled them on 3.8.0-34-generic Linux 32bit. 
Checking a process with yara succeeds while checking the same process using the python module causes a segmentation fault. 
I used the same rule set in both cases. Both processes are started as root.
Am I doing something wrong?

![ishot-140325-211347](https://f.cloud.github.com/assets/2851492/2517558/58ec1e8a-b45a-11e3-9e04-93901d2bc9e3.png)

![ishot-140325-211410](https://f.cloud.github.com/assets/2851492/2517559/58fd015a-b45a-11e3-99eb-99142ca74717.png)

**Comment by plusvic** [comment]
Closing because it's a very old issue. Please re-open if still valid.
