### ISSUE TITLE
a bug found when run a rule

### ISSUE THREAD

**Issue by zxxunkxzhx** [VirusTotal/yara#1318]
hi, team:
when run following rule
rule Base64Example1
{
    strings:
        $a = "This program cannot" base64

    condition:
        $a
}

I was expecting to detect VGhpcyBwcm9ncmFtIGNhbm5vd only, but  instead I found it can also detect RoaXMgcHJvZ3JhbSBjYW5ub3

please check it, thanks.

**Comment by wxsBSD** [comment]
This is not a bug. The details of how this works (including a link to a relevant blog article) are at https://yara.readthedocs.io/en/stable/writingrules.html#base64-strings.
