### ISSUE TITLE
Not a valid Win32 application

### ISSUE THREAD

**Issue by blahblahm2** [VirusTotal/yara#1332]
Hello,

Just wondering if anyone can assist with this issue.
I am getting this issue when running the exe on windows 2003 OS.

![image](https://user-images.githubusercontent.com/67685397/89260707-2691ec00-d670-11ea-9c23-e0001a037910.png)

**Comment by tlansec** [comment]
Have you tried using older versions of YARA? Perhaps the newest version uses API calls that are not present in Win 2003.

**Comment by joshlemon** [comment]
You have to go back a few version to get the compiled binaries to work on Server 2003. 

You'll need to use [Release 3.5.0](https://github.com/VirusTotal/yara/releases/tag/v3.5.0) and you'll also need to have the [Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) installed](https://www.microsoft.com/en-US/download/details.aspx?id=8328).

Just remember there are a number of options that won't work in this release, mainly compiled rule, so adjust your command as needed.

**Comment by blahblahm2** [comment]
Thank you for your response. Tom,

I used release 3.5.0 and this seem to work fine.

Regards,
Junell

**Comment by blahblahm2** [comment]
Thank you, Josh.

In the end I used Release 3.5.0 and that seems to work. I didn't need MS
Visual C++.

I am still new to this tool so I am not familiar with the options.

Regards,
