### ISSUE TITLE
The function that applies rules on a given file/text.

### ISSUE THREAD

**Issue by ItsCRC** [VirusTotal/yara#1342]
Hey, I hope you guys are doing well.
I am working on converting yara rules into snort signatures as a part of my research. So can you guys guide me as to where is the function that takes rules of yara and applies it on a given text/file.  More specifically, the function which is doing pattern match in yara.

**Comment by plusvic** [comment]
I'm not sure if you are interested in seeing how YARA works internally or if you want to use it's API. If you are interested in the API you can start here: https://yara.readthedocs.io/en/stable/capi.html, specifically you may want to take a look at the [yr_rules_scan_file function](https://yara.readthedocs.io/en/stable/capi.html#c.yr_rules_scan_file). If you want to know how YARA works internally it's a bit more complicated to point you out to something specific. There's no single function in YARA doing the pattern matching stuff, is actually a lot of functions working together.
