### ISSUE TITLE
[Feature Request] - number_of_imported_functions

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1345]
Hi,

I was wondering if it would be possible to include a count of the number of imported functions in addition to the number of imports, e.g. for the following file:

https://www.virustotal.com/gui/file/0f75fabe825f8a7a55714d13535848c46f9a4e72fa748907e269f9c5a96febab/details

It would be:

number_of_imports - 1 
number_of_imported_functions - 1 

Whereas if it imported more than just "_CorDllMain" the # of functions would be larger.

I appreciate that for large import tables this might not be fast, so it might be better to make this available as a function, in a similar fashion to pe.imphash().

Cheers,
Tom

**Comment by wxsBSD** [comment]
We are already parsing functions, so this is just exposing the counter we already have for them. It's a pretty small patch. Should have it up tonight.

**Comment by tlansec** [comment]
Nice one!
