### ISSUE TITLE
Change handling on strings that cause too many matches.

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1346]
Hello,

At the moment sometimes when scanning large files its possible for even relatively sensible rules to cause an error of the format:

"error scanning foo blah in rule bar causes too many matches" 

The current behaviour when this happens is to stop scanning the file (afaik, based on testing with @wxsBSD ), but in this issue i would like to request a change so that instead it continues scanning the file. The requirements to make this work are:

1) Create a "max count" for each string, where each string can only match that # of times (I am unsure on what a sensible value for this is, but it should be based on whatever number currently causes this error to occur)
2) When this max count is reached for a given string, YARA should stop recording offsets // matches and should print a warning message "Warning maximum string count for string X matched in rule Y - rule Y may no longer work as intended"

The reason for this request is that although it doesnt occur often for regular files, when scanning large files it's possible for a variety of reasons that strings that are sensible on smaller files will cause errors, meaning users have to edit their rules file and rescan (which depending on the volume of data being scanned may be undesirable).

I also think that its not obvious to users with the current error message that the error will cause no rules to match the file, so as a minimum the error message could be modified to be more explicit.

Thanks,
Tom

**Comment by plusvic** [comment]
Makes a lot of sense.

**Comment by wxsBSD** [comment]
I’ll see if I can get a patch for this out in the coming week.

**Comment by wxsBSD** [comment]
I've put up a PR for this so we can have discussion over there. Once we settle on the implementation I'll be sure to adjust the docs accordingly (if necessary).
