### ISSUE TITLE
Rules utilizing filesize match on process memory

### ISSUE THREAD

**Issue by secDre4mer** [VirusTotal/yara#1354]
Using filesize in a rule should always result in false when matching on process memory, according to the YARA documentation ([https://yara.readthedocs.io/en/stable/writingrules.html#file-size](https://yara.readthedocs.io/en/stable/writingrules.html#file-size)):

> The use of filesize only makes sense when the rule is applied to a file. If the rule is applied to a running process it won’t ever match because filesize doesn’t make sense in this context.

However, this is not the case. Conditions with filesize match process memory.

Minimal example: 
```
PS C:\Users\Test\Downloads> .\yara64.exe -v
4.0.2
PS C:\Users\Test\Downloads> cat custom.yar
rule Example_Rule {
   condition:
      filesize < 800KB
}
PS C:\Users\Test\Downloads> .\yara64.exe custom.yar 856
Example_Rule 856
```

**Comment by plusvic** [comment]
Fixed in a1f0720970f3bde0524073c960b6f9ccd34a1f63
