### ISSUE TITLE
YARA newbie seeking best strategy for implementing asynchronous / incremental memory block access ?

### ISSUE THREAD

**Issue by simonhf** [VirusTotal/yara#1375]
I'm interested in tweaking the libyara API so that it can scan n arbitrarily large files concurrently in a single thread where the memory blocks for each file are available in order over time, but not all at once.

I know YARA supports threads, but I'm imagining n being 1,000 or 10,000 or 100,000 or more, which seems prohibitively large for numbers of threads, or? And at the same time, I'd prefer not to queue all those files on disk, etc.

Perhaps naively, this functionality seems within grasp since libyara is already designed to scan files as a sequence of consecutive overlapping discreet memory blocks, and already has a callback mechanism to fetch the next memory block, etc. The main difference seems to be that in the current libyara implementation, all the memory blocks needed are assumed to be available at the time libyara is called to scan the file. However, I'd like to change the functionality so that each call to libyara it scans what it can with the memory blocks available so far, but then can keep state and continue later when more memory blocks become available.

So I'm asking / brain-storming here as to whether anybody has ideas about the best way to approach implementing this functionality, as well as the challenges associated?

Having already dipped my toes in the libyara development swimming pool with a few recent PRs, this is my initial thoughts / ideas for how to approach the implementation of the functionality (please feel free to criticize, or suggest a different approach!):

Most functions in libyara return `ERROR_SUCCESS` [1] upon success, or one of the different `ERROR_*` errors / states. I'm thinking about creating a new return code called e.g. `ERROR_BLOCK_NOT_READY` which would be the libyara equivalent of the common Linux return codes `EAGAIN` or `EWOULDBLOCK`.

The libyara scanner will eventually callback to get the next memory block and that function might return `ERROR_BLOCK_NOT_READY` if the block isn't available.

Upon receiving `ERROR_BLOCK_NOT_READY` then all the functions in between would also return `ERROR_BLOCK_NOT_READY` back to the original caller of libyara.

The libyara caller can then wait until the next memory block is available, then call libyara again, and then the libyara scanner would immediately callback to get the next memory block until the next `ERROR_BLOCK_NOT_READY` or until the last memory block.

In theory this would be backward compatible with existing libyara API callers because their code would never have a next memory block callback returning `ERROR_BLOCK_NOT_READY`? And therefore, they'd never have to worry about that business logic?

One area that I'm not sure about is the file size. Currently this is given up front in the libyara API, but what if the file size is not known up front, or is known but the rest of the memory blocks never become available at scan time and then the scan is prematurely cancelled?

Assuming there are YARA rules which rely on knowing the file size in advance, how to filter those out at rule compile time, and would that be a significant percentage of rules making the whole approach questionable in terms of usefulness?

As a test, I'm imagining creating a new YARA test which attempts to scan n files concurrently (in a single thread) with their memory blocks becoming available in a random but deterministic order.

What do you guys think? Am I on the right path? What would be a better path? Is this going to be a world of pain? If so, why? And is this the type of functionality that the YARA community would welcome?

[1] https://github.com/VirusTotal/yara/blob/master/libyara/include/yara/error.h#L40

**Comment by plusvic** [comment]
My first question is: do you want to have multiple threads where each thread scans one block of data?  And the second question is: What do you intend to achieve with that level of parallelism? Can you provide a description of the real-life problem that you want so solve?

In general I wouldn't add complexity to `libyara` itself unless it solves some fundamental problem. The issue with the current design is not that all memory blocks must be already available when `libyara` is called (this is not case actually), the issue is that you can not scan the memory blocks out of order. The `yr_scanner_scan_mem_blocks` receives a `YR_MEMORY_BLOCK_ITERATOR`, and you can implement an iterator that asks for all the blocks simultaneously if you want, the only requirement is that you must return those blocks to `libyara` one after the other in the right order whenever YARA calls your iterator's `next` function. In other words, the `next` function must return the blocks in the correct order, if some block is not yet available,`next` must block and wait until it is. Is this solution not enough in your case?

**Comment by simonhf** [comment]
Thanks for the questions!

The real-life problem is using libyara to scan files contained / embedded in network traffic in close to real time. Typical network traffic in a larger organization (such as a university) will have very many concurrent connections, and many of those can be concurrently transferring files, or hierarchical archives containing files. For each network connection, the idea is to gather network packets as they trickle in over time, to form the next consecutive memory block to feed to libyara dynamically. This would be more efficient because for each concurrent network connection, you only have to keep track of the current memory block, plus a little overlapping of the last memory block. There is no need to build the entire file in memory, and/or save it to disk for later scanning with libyara, as the current libyara API demands. In this way a single thread could scan arbitrarily many files (of arbitrary size) concurrently.

"if some block is not yet available, `next` must block and wait until it is" That's right, and that's what I'd like to change so that the blocking and waiting part is no longer necessary. In the network scenario then we don't know when the next packet will arrive (for a particular connection) which completes the next memory block to scan, however, many other packets for other concurrent memory blocks to scan may arrive in the meantime. Therefore, I am proposing -- and open to other ideas and suggestions too -- that `next` be able to return a special status somehow, meaning e.g. 'next block not ready', thus not needing to block and wait until the memory block is available. So I'm proposing that `next` be changing from a blocking function to a non-blocking function, as well as all the libyara functions which are called before. In theory this wouldn't change the business logic for existing code using libyara, because that existing code never deals with the non-blocking `next` callback, i.e. for existing applications, the files to be scanned are always completely available at run-time and therefore the non-blocking API is never used?

**Comment by simonhf** [comment]
For example -- real world network traffic -- a university network might see 150+M files per day with the highest number of concurrent files being in the multiple thousands range. These types of figures make it impractical to use one thread per file. And if we are using less threads then it's much less efficient to buffer and queue all the files waiting to be scanned. Looking forward to your comments.

**Comment by plusvic** [comment]
Ok, now I get the idea. I don't see any problem with this approach besides the one you already mentioned with the file size. Everything should be fine if you call `yr_scanner_scan_mem_blocks` again with the same `YR_SCANNER` and `YR_MEMORY_BLOCK_ITERATOR` until the iterator is able to return the next block. 

For solving the file size issue that would probably require adding a new function to the iterator that returns the file size. So, instead of initializing the `file_size` field in `YR_SCANNER` after reading the file, that would be done after all the blocks has been iterated and before calling `yr_execute_code` in https://github.com/VirusTotal/yara/blob/master/libyara/scanner.c#L470. The iterator would be responsible of computing the file size and returning it when `yr_scanner_scan_mem_blocks` asks.

**Comment by simonhf** [comment]
@plusvic Okay, so here's [1] a working draft of the idea. There are still some extra tests I'd like to add, but all the existing libyara tests pass with the changed code. I have not looked into the file size issue yet. The changes are as follows:

* Introduce new error code `ERROR_BLOCK_NOT_READY` which gets returned if the next block is not available yet.
* Keep the libyara API identical and it works the same if `ERROR_BLOCK_NOT_READY` is never returned.
* So the `YR_SCANNER` instance can be re-used later, I introduce `yr_scanner_existing` & `yr_scanner_employed`.
* Enhance the test iterator in `util.c` so it can not only split into blocks, but also return `ERROR_BLOCK_NOT_READY`.
* No longer allocate data structures on the stack because they will not survive `ERROR_BLOCK_NOT_READY`.
* A brand new end-to-end test file `test-async.c` demonstrates manipulating the `YR_SCANNER` instance at run-time.

Do you foresee any YARA plugins that might not work with this approach, or where it might be good to add extra testing?

Also, forgot to mention in above posts that this technique might allow libyara to be used in more constrained environments where it might have otherwise difficulty running, e.g. on a tiny but useful  devices like a Raspberry Pi it could never-the-less scan n 1TB files concurrently -- albeit slowly as the packets flow in -- whereas otherwise there might not be space to store the files on disk for subsequent scanning.

Looking forward to any comments, criticism, and/or encouragement :-)

[1] https://github.com/simonhf/yara/commit/768a1d2407055accaa02ed51183c01d2e87e19a9

**Comment by plusvic** [comment]
Your changes look mostly ok to me except for one thing, I prefer to avoid all the `yr_scanner_existing` and `yr_scanner_employed` logic, which add more complexity and introduce multithreading issues. What I would do instead is leaving the `yr_rules_scan_xxx` API as it is today and return `ERROR_BLOCK_NOT_READY` only from `yr_scanner_scan_xxx` functions. Of course this forces you to use the `yr_scanner_xxx` API for using this new feature, but that's just a minor inconvenience for the sake of simplicity. With this approach you only need to modify `yr_scanner_scan_mem_blocks`.

The open question is what to do if one if the `yr_rules_scan_xxx` functions receive a `ERROR_BLOCK_NOT_READY` from their `yr_scanner_scan_xxx` counterparts. We have at least three options:

1. `yr_rules_scan_xxx` keep retrying until the block is ready.
2. `yr_rules_scan_xxx` returns `ERROR_BLOCK_NOT_READY`, but caller can't recover from the error by calling `yr_rules_scan_xxx` again.
3. `yr_rules_scan_xxx` returns some other error instead of  `ERROR_BLOCK_NOT_READY`.

The simplest solution is 2, but 1 is the most coherent. With option 1 `yr_rules_scan_xxx` would be the first implementator of the retrying logic after a `ERROR_BLOCK_NOT_READY`. Maybe we can go with 2 to start with, and then implement 1 in the future.

**Comment by simonhf** [comment]
Thanks very much for looking at the proposed implementation and the constructive feedback!

Regarding option #1 of the 3 alternative options kindly proposed: "`yr_rules_scan_xxx()` keep retrying until the block is ready": I'm not sure this makes sense when the non-blocking API is used. Why? Because it could be a relatively long time before the next block becomes available over the network. And also there is no guarantee that the next block arriving over the network will be for that particular file being scanned and where `yr_rules_scan_xxx()` is retrying. In `test-async.c` then 3 files are scanned in the same thread using the non-blocking API and the tests rotate through each block in order and each file in order, but this is only for test simplicity and in reality the blocks will be in order but the files might not be in order, e.g. block 2 for file 2 might become available before block 2 for file 1, etc. In the end, the **caller** of the non-blocking libyara API needs to manage the number of scanner instances, and when the caller receives a new block of a file, it needs to set the scanner instance **behind the scenes** for the appropriate file, and re-invoke `yr_rules_scan_mem()`. So "retrying until the block is ready" isn't an option.

Regarding option #2 of the 3 alternative options: "`yr_rules_scan_xxx()` returns `ERROR_BLOCK_NOT_READY`, but the caller can't recover from the error by calling `yr_rules_scan_xxx()` again": I originally opted not to do this because:

* It means I cannot do the `test-rules.c` 3rd pass (please see below), leveraging the existing tests, and
* I'd need to effectively duplicate the `yr_rules_scan_xxx()` functionality for the non-blocking API which creates a larger API and possibly makes it more confusing than using `yr_scanner_existing` & `yr_scanner_employed` business logic?

So my strategy so far has been:

* Avoid changing or growing the current libyara API.
* Avoid duplicating code in the current libyara API functions.
* Try to re-use and leverage the existing tests where possible.

I totally agree with your preference for avoiding the `yr_scanner_existing` & `yr_scanner_employed` business logic and this is something I struggled over, and in the end I decided to keep it and bounce it off you because:

* It means the existing API does not have to change, or get larger.
* Only using `yr_scanner_xxx()` functions means I must duplicate functionality in `yr_rules_scan_xxx()` functions.
* Although the business logic is more complicated, it's only more complicated for non-blocking use of the API, and there is a concrete example of the non-blocking API being used in the new `test-async.c` test file.

In order to try and alleviate your concerns I have a not-yet-pushed work-in-progress update which:

* Encapsulates the `yr_scanner_existing` & `yr_scanner_employed` API business logic in the new functions -- which attempt to be more 'intention revealing' -- `yr_scanner_instance_behind_the_scenes_set()` and `yr_scanner_instance_behind_the_scenes_get()`; `_behind_the_scenes_` being a kind of API user 'alert' that something different and less usual is happening.
* Updates `test-async.c` with comments further explaining what is happening and why.
* Updates `threading.h` with a cross platform `YR_TLS` definition which removes the multi-threading issues.
* Updates `test-rules.c` to perform a 3rd test pass; 1st and original test pass scans a single memory region. 2nd and recently added test pass scans the same region but divided into blocks by the test iterator. 3rd and new test pass scans the same region, and divides into blocks by the test iterator as before, but returns `ERROR_BLOCK_NOT_READY` after each block, thus testing the call function tree with the existing code-base. This test takes advantage of the fact that `yr_rules_scan_xxx()` API has not changed.

The `test-rules.c` 3rd test pass has resulted in some minor fixes needed to make most of the tests work. However, the hash tests are failing and the reason is that `libyara/modules/hash/hash.c` also needs a refactor to support the new `ERROR_BLOCK_NOT_READY` result from the test iterator, which is what I'm exploring refactoring at the moment, e.g. `data_md5()` needs to return upon `ERROR_BLOCK_NOT_READY` and then be called again later, etc.

Again, leveraging the existing tests to test e.g. the hash module, requires using `yr_rules_scan_xxx()` which is another reason to keep the less desirable API business logic proposed, which seems to be the best of a bad bunch of options, or? The alternative would be to either modify the `yr_rules_scan_xxx()` API, or create a nearly duplicate API and tests so as not to change the `yr_rules_scan_xxx()` API.

I'm hoping you can tolerate this solution as the best of a bad bunch.

Looking forward to your further comments, and in the meantime I'm working on the hash module refactor to support the blocking test iterator.

**Comment by simonhf** [comment]
@plusvic here [1] is the now pushed work-in-progress update which is hopefully more intention revealing, solves the threading issue, and has the `test-rules.c` 3rd pass doing extra testing.

Looking forward to any comments, criticism, and/or encouragement :-)

[1] https://github.com/simonhf/yara/commit/3ffe9546cfedb8aba9a9e161371abde4a04cb928

**Comment by plusvic** [comment]
It's great to see such a detailed and well explained reasoning, I'm really glad to have this kind of contributors.

If I understand right one of the main advantages of making `yr_rules_scan_xxx()` retry-able after a `ERROR_BLOCK_NOT_READY` is being able to re-use the existing test cases for the async use case. The other advantage of course is that `yr_rules_scan_xxx()` would behave like `yr_scanner_scan_xxx()`, and both would be retry-able. However I still think that the added complexity overweights the advantages, and prefer to implement either option #2 or #3. 

We still don't know how many people are going to use this new API semantic, but I would say that not too many. This is a pretty advanced use-case for people with very specific needs. For that reason I think we should make the minimal set of changes that allows the async use-case, but without introducing too much new stuff in the code base. Everything new that we introduce increases the maintenance burden in the future. 

With regards to testing, it would be ideal to use all the existing tests with the async scanning approach, but that's not strictly necessary. It should enough if we have a set of tests focused in the async case and covering the specific issues that it can introduce, for example:

* Make sure the hash module produces the right hash for the whole data even if sliced in blocks and when some of those blocks returned `ERROR_BLOCK_NOT_READY`

* Make sure that certain rules with regexps like /foo.*bar/ match. The .* operator in regular expressions may cause problems with data that is sliced in blocks.

I'm aware that my arguments against making `yr_rules_scan_xxx` retry-able are very subjective, and depends a lot on the priorities we set, but at this point maintainability and reducing complexity is very high in my list.

**Comment by simonhf** [comment]
@plusvic Thanks for the kind words which are much appreciated. After removing the `yr_scanner_existing` & `yr_scanner_employed` business logic as requested, then the code does seem simpler, so I think you were right. I was probably too hung up on the idea of re-using the existing tests without hugely refactoring them. Similar thing with overloading `iterator->first()` which I also changed. You were also right there. I was probably too hung up with trying to not extend the existing structures. Looking forward to any further comments, criticism, and/or encouragement :-)
