### ISSUE TITLE
Feature: TELFHash Support in "elf" module

### ISSUE THREAD

**Issue by Neo23x0** [VirusTotal/yara#1378]
I think this `telfhash` by TrendMicro would be a good extension for the `elf` module. 

Details
https://blog.trendmicro.com/trendlabs-security-intelligence/grouping-linux-iot-malware-samples-with-trend-micro-elf-hash/

Recent Article
https://www.trendmicro.com/en_us/research/20/j/virustotal-now-supports-trend-micro-elf-hash.html

**Comment by hillu** [comment]
The basic feature that you and I would probably think of (imphash, but for ELF files) is certainly useful and can be efficiently implemented, as part of the elf module. However, it would be a bad idea to implement handling of static binaries: There, the TELF implmentation uses the Capstone disassembler to determine target addresses of call instructions.

**Comment by plusvic** [comment]
I haven't looked at `telfhash` yet, but if it depends on the Capstone disassembler that would be a heavy dependency :(

**Comment by Neo23x0** [comment]
Understood. Yes, that's bad.

**Comment by merces** [comment]
It's kinda tough to get rid of a disassembly library but I'll think about that. Thanks for considering a module anyway.
