### ISSUE TITLE
Inconsistent "reasonable value for N" warnings using regex

### ISSUE THREAD

**Issue by Viper896** [VirusTotal/yara#1386]
When using regex, warnings are displayed when using the `.*` or `.*?` syntax.  However, a similar warning is not displayed when using the` .{0,}` or `.{0,}?` syntax.  As these queries essentially mean the same thing, I would expect the warnings to be consistent as well.

**Comment by wxsBSD** [comment]
I can't reproduce this on latest master.

```
wxs@wxs-mbp yara % cat rules/re.yara
rule a { strings: $a = /.{0,}/ $b = /.{0,}?/ condition: any of them }
wxs@wxs-mbp yara % ./yara rules/re.yara /bin/ls
rules/re.yara(1): warning in rule "a": $a is slowing down scanning
rules/re.yara(1): warning in rule "a": $b is slowing down scanning
```

**Comment by plusvic** [comment]
@wxsBSD in your rule the other warning is triggering first. With this other rule is reproducible:

```
rule a {
strings:
  $a = /fooo.{0,}bar/
condition:
  $a
}
```

**Comment by wxsBSD** [comment]
Wow, I completely missed that this is the other warning for poor atom quality. Sorry for the confusion and I’ll take a look at the PR tonight.

**Comment by plusvic** [comment]
Too late ;)  https://github.com/VirusTotal/yara/pull/1398
