### ISSUE TITLE
unknown module “hash”

### ISSUE THREAD

**Issue by TriompheL** [VirusTotal/yara#1406]
When I use the hash module, the following problem occurs
![image](https://user-images.githubusercontent.com/27794837/100692276-71750380-33c5-11eb-9eef-0d6aa0f416c7.png)
![image](https://user-images.githubusercontent.com/27794837/100692299-805bb600-33c5-11eb-83df-e6f2fb84d3c6.png)

**Comment by plusvic** [comment]
That's because you built YARA without OpenSSL support. Which operating system you have?

**Comment by TriompheL** [comment]
I have resolved my problem by use the YARE 4.0.0
