### ISSUE TITLE
Newbie help: syntax error while builiding?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [VirusTotal/yara#1407]
Hi all, I've never done this before and also not real good with Linux in general. I'm using kubuntu 20.10. When I go into the dir and do a:

`./build.sh`

I get this after a bunch of lines scroll:

> ./configure: line 11458: syntax error near unexpected token `PROTOBUF_C,'

> /configure: line 11458: `    PKG_CHECK_MODULES(PROTOBUF_C, libprotobuf-c >= 1.0.0)'

> make: *** No targets specified and no makefile found.  Stop.

**Comment by simonhf** [comment]
I haven't had this error myself, but when I come across errors like this I often trying Googling the error text, in this case `syntax error near unexpected token `PROTOBUF_C,'`. For me, this actually brings up a few results and one [1] looks like it might be identical to your issue and solve it :-) Good luck!

[1] https://github.com/VirusTotal/yara/issues/1171

**Comment by plusvic** [comment]
This may be because the `pkg-config` package is missing in your system. See:

https://stackoverflow.com/questions/36659867/pkg-check-modules-syntax-error-near-luajit
https://github.com/savoirfairelinux/opendht/issues/253
