### ISSUE TITLE
Add support to combine YR_RULES

### ISSUE THREAD

**Issue by AjayVV** [VirusTotal/yara#1419]
Related: https://github.com/VirusTotal/yara/issues/148

- Add one or more Yara rules to the compiler using `yr_compiler_add_file`, `yr_compiler_add_string` etc.
- Get compiled rules (i.e. `YR_RULES`) from added rules.
- Save the rules `yr_rules_save`
- Either use `yr_rules_scan_file` or create a scanner and then use `yr_scanner_scan_file`
- When needed (e.g. on program start) use `yr_rules_load` and then `yr_scanner_create`

All good. But what if new plain text Yara rules do come? 
One idea is to store all plain text rules, add all of them (plus the new ones) using `yr_compiler_add_file` and repeat the process.
But what if plain text rules are too many? Why store plain text rules as well as the compiled rules (_saving compiled rules to speed up_, obviously). This essentially defeats the whole purpose of `yr_rules_save` !

Another approach is to have **multiple** `YR_RULES` and/or multiple scanner object. This means `yr_scanner_scan_file` must be invoked against all scanner objects!

There should be some approach to add new rules to existing compiled rules (i.e. append to `YR_RULES`).

**Comment by plusvic** [comment]
Unfortunately merging two sets of compiled rules is not viable due to the way in which compiled rules are stored. So this is unfeasible.

**Comment by AjayVV** [comment]
@plusvic What's the best alternative then? Keep both plain text rules and compiled rules stored on disk? And when new plain text rules come in, destroy compiled/scanner, and start again? Or have multiple rules/scanners/compilers?

**Comment by plusvic** [comment]
The exact solution depends on your case, but you will need to store at least the text rules and recompile them again when some change arrives. Whether or not you store the compiled rules as well depends on what you want to achieve. Most system just compile the rules and keep them in memory but don't write them to disk.
