### ISSUE TITLE
Get "condition" from C API?

### ISSUE THREAD

**Issue by CaledoniaProject** [VirusTotal/yara#1424]
Taking this one for example, how do I get the condition from compiled yara rules?

```
rule silent_banker : banker
{
    condition:
        $a or $b or $c
}
```

I've checked the YR_RULE structure, but there's nothing relevant:

```
struct YR_RULE
{
  int32_t g_flags;                  // Global flags
  int32_t t_flags[YR_MAX_THREADS];  // Thread-specific flags

  DECLARE_REFERENCE(const char*, identifier);
  DECLARE_REFERENCE(const char*, tags);
  DECLARE_REFERENCE(YR_META*, metas);
  DECLARE_REFERENCE(YR_STRING*, strings);
  DECLARE_REFERENCE(YR_NAMESPACE*, ns);

  // Used only when PROFILING_ENABLED is defined
  volatile int64_t time_cost;
};
```

**Comment by plusvic** [comment]
Once the rules are compiled the condition is not accesible. The original expression is lost, only the compiled code remains. If you want to parse your YARA rules and extract the conditions from them you can relay in other parsers like https://github.com/VirusTotal/gyp and https://github.com/plyara/plyara.
