### ISSUE TITLE
Strange performance measurements results with simple rules and large files

### ISSUE THREAD

**Issue by snemes** [VirusTotal/yara#1437]
I was doing some naive Yara performance measurements to find out how certain Yara expressions affect the search performance, to be able to write better Yara rules. During this effort I arrived at a strange revelation:

If you have a Yara rule like this:

```
rule test_1 {
    condition:
        uint16(0) == 0x5A4D
}
```

And you try to run it on 2 different 16GB files with random data, where one is starting with "MZ" while the other doesn't, you get a surprising result that the Yara scanning takes almost equally long on both files (around 1 minute), when one would assume that the Yara engine stops scanning after seeing the first two bytes and realizing that the condition can't be satisfied.

My second thought was that it probably has something to do with Yara's preprocessing, and breaking the source file into atoms or something, and probably the processing phase (maybe for the Aho–Corasick pattern matching algorithm) that has to be performed on the file regardless of what the rule is.

I did a second scan with an even more obvious Yara rule:

```
rule test_2 {
    condition:
        true
}
```

However scanning with this rule took a long time as well (around 1 minute on a 16GB file with random contents)

Is this a bug, or something that is intended and by design?

Thanks a lot

**Comment by wxsBSD** [comment]
This is intentional, and comes up for discussion from time to time. You can see https://github.com/VirusTotal/yara/issues/1415 for discussion around it, and why in real-world scenarios this approach is the best one.

**Comment by snemes** [comment]
Cool, thanks a lot of the clarification. Closing issue.
