### ISSUE TITLE
Incorrect WIN_CERTIFICATE alignment in 'pe_parse_certificates' function

### ISSUE THREAD

**Issue by Aleh-Kazakevich** [VirusTotal/yara#1443]
When parsing PE certificate table, the pointer to second and other WIN_CERTIFICATE structure
may not be 8-byte aligned, as required by specification:

`win_cert = (PWIN_CERTIFICATE)(end + (end % 8));`

Example:
end = 0x1234000A, win_cert = 0x1234000c (not 8-byte aligned!)

See the 'pe_parse_certificates' function in the 'pe.c' file
https://github.com/VirusTotal/yara/blob/master/libyara/modules/pe/pe.c#L1507
https://github.com/VirusTotal/yara/blob/master/libyara/modules/pe/pe.c#L1526

**Comment by plusvic** [comment]
If I understand correctly you mean that there are certain PE file that don't follow the specification and don't have the certificate aligned as it should be. Is that what you mean?

Can you sent some of those files that we can use as a reference or for including it as a test case?

**Comment by Aleh-Kazakevich** [comment]
No, the problem is that the 'win_cert' variable itself is not 8-byte-aligned when moving to the next 'WIN_CERTIFICATE' structure.

**Comment by plusvic** [comment]
Oh, I see what you mean. The in way in which the computation is done is incorrect. The correct one would be:

```
win_cert = (PWIN_CERTIFICATE)((end + 7) & -8);
```

**Comment by plusvic** [comment]
Fixed in e4819f6b98ebdd97eff9e32badb6edd519e76dc3
