### ISSUE TITLE
Yara is not working when the rule file is too large

### ISSUE THREAD

**Issue by lizhixiang0** [VirusTotal/yara#1444]
Hi  , I have a problem using Yara . 
My rules file is about 1MB , Then it stopped working  .
![image](https://user-images.githubusercontent.com/54135171/106868479-c9075680-6709-11eb-83c6-4e58376d1b90.png)

So I picked a few rules from the mix and made a small one rules file ,it works !

![image](https://user-images.githubusercontent.com/54135171/106868559-e0464400-6709-11eb-93c0-ea2680fae882.png)

**Comment by norwayfinland** [comment]
What happens if you compile the rules?

```yarac -w ./big_one.yar ./big_one.compiled
yara -rC ./big_one.compiled ./4159eb1059875232444aa59d886739a3/
```

**Comment by wxsBSD** [comment]
It's hard to test this without having access to a reproducible test case. I have a collection of rules that is 1.8MB but spread across multiple files and compiled via a series of `include` statements, so while not exactly the same setup as yours I can't easily reproduce it with a large collection of rules. Is it possible to share the rules (or a dummy set that is large enough to trigger this)?

**Comment by lizhixiang0** [comment]
@norwayfinland  , thank you for your help ，But it didn't respond anything
![image](https://user-images.githubusercontent.com/54135171/106977144-b71ec580-6794-11eb-8c07-7c82ad635c78.png)

**Comment by lizhixiang0** [comment]
@wxsBSD  
Thank you  ，i can share the rules  and I have integrated androguard in Yara . 
Follow this ： https://github.com/Koodous/androguard-yara

[big_one.txt](https://github.com/VirusTotal/yara/files/5929550/big_one.txt)

**Comment by lizhixiang0** [comment]
@wxsBSD  
The malware is 
[sample.zip](https://github.com/VirusTotal/yara/files/5929582/sample.zip)

The small ruleset is 
[small_one.txt](https://github.com/VirusTotal/yara/files/5929584/small_one.txt)

**Comment by lizhixiang0** [comment]
My rule base is not formatted correctly ，Some rules are prefixed  with 'private ' , When I get rid of it, it worked

**Comment by wxsBSD** [comment]
Thanks for the update! Please close this out.
