### ISSUE TITLE
feature idea: seminocase

### ISSUE THREAD

**Issue by 2d4d** [VirusTotal/yara#1451]
hello,

I would like to propose a new kind of string modifier, which would be a compromise between using nocase and the default case sensitive search. the string would be searched in all upper, all lower or how it is written in the strings section. for example:

$ = "Password" seminocase

would search for:

- Password
- password
- PASSWORD

That would create far less atoms then nocase (3 vs 16) but still cover the most common cases.

For example in some rules I look for typelibguids, and some compilers put them in upper case in the binaries, some in lowercase. So the rules look so far like:

        $ = "c335405f-5df2-4c7d-9b53-d65adfbed412" ascii wide nocase
        $ = "858386df-4656-4a1e-94b7-47f6aa555658" ascii wide nocase 
        $ = "ec7afd4c-fbc4-47c1-99aa-6ebb05094173" ascii wide nocase 

Another option would be include both upper and lower cases strings and drop the nocase but that's kind of clumsy compared to just putting the nocase there. Having some kind of seminocase (or however you want to call it) would be the perfect solution. It's not intended to catch camelcase for obfuscation but output of systems, which sometimes use different casing for the whole string.

regards
arnim

**Comment by plusvic** [comment]
We prefer to use string modifiers in cases where there are few other alternatives, or it would require rules with hundreds of different strings. For simple cases like this one you can always rely on explicitly using two or three strings. It's minor inconvenience, but simplifies makes YARA simpler. We are already having problems to accommodate the interaction between different modifiers, and adding more modifiers will make it even harder.
