### ISSUE TITLE
Excluding matches with regex

### ISSUE THREAD

**Issue by eth0izzle** [VirusTotal/yara#1452]
I'm trying to NOT match a rule if it contains a particular string. I know the regexp engine doesn't support negative lookaheads so we have to get creative. I came across #584 but I can't see to get it to work.

    rule username_password_uri : authentication
    {
        strings:
            $match = /([\w+]{1,24})(:\/\/)([^$][^\s";\/\/]{1,}):([^$][^\s";]{1,})@[-a-zA-Z0-9@:%._\+~#=]{1,256}[a-zA-Z0-9()]{1,24}([^\s"]+)/ fullword
	        $not = /([\w+]{1,24})(:\/\/)(username|user|test):(password|pass|test)@[-a-zA-Z0-9@:%._\+~#=]{1,256}[a-zA-Z0-9()]{1,24}([^\s"]+)/ fullword

        condition:
	        for any i in (1..#match) : ( @match[i] != @not[i] )
    }

Given

https://shouldmatch:shouldmatch@hello.com
https://username:password@shouldNOTmatch.com

I would expect $match to match both of those lines, which it does. But $not does NOT match the 2nd line so the rule shouldn't include it. Any ideas?

**Comment by merces** [comment]
I'd create a private rule and negate it in the main rule this way:

```yara
private rule default_field_names {
    strings:
        $field_names = /([\w+]{1,24})(:\/\/)(username|user|test):(password|pass|test)@[-a-zA-Z0-9@:%._\+~#=]{1,256}[a-zA-Z0-9()]{1,24}([^\s"]+)/ fullword
    condition:
        $field_names
}

rule username_password_uri : authentication {
    strings:
        $match = /([\w+]{1,24})(:\/\/)([^$][^\s";\/\/]{1,}):([^$][^\s";]{1,})@[-a-zA-Z0-9@:%._\+~#=]{1,256}[a-zA-Z0-9()]{1,24}([^\s"]+)/ fullword
    condition:
        $match and not default_field_names
}
```

**Comment by eth0izzle** [comment]
Thanks @merces. I couldn't get that to work either. Turns out my example rule was sort-of correct but it's matching on the whole file, not on each match instance. So `username_password_uri ` will match correctly on `https://shouldmatch:shouldmatch@hello.com` but `default_field_names` will also match on `https://username:password@shouldNOTmatch.com`, canceling each other out and not returning a match.

I want to do:
    condition
        $match and not $match matches /(username|user|test):(password|pass|test)/

but that doesn't look possible. Any ideas?

**Comment by eth0izzle** [comment]
I used a `meta` tag in the end that contains a list of patterns that it SHOULDN'T match against and filtered them out in code after yara returns its matches.

**Comment by wxsBSD** [comment]
I know you closed this but `$match and not $not` should work just fine here.
