### ISSUE TITLE
Consistency between versions and release tags?

### ISSUE THREAD

**Issue by mhuth** [VirusTotal/yara#1458]
Hi,

Just wondering if the yara version check between a compiled rule file and yara could be relaxed a little rather than having to match exactly?  Would it be possible to allow, say, the second minor version numbers to be different but the compiled rules file to still be usable?  For example, a rules file compiled with 4.0.2 would still be usable with yara 4.0.5?  Any combination of a 4.0.x compiled rules file and 4.0.y yara version would be ok to use together, but not, say 4.x and 4.y.  Or even a later version of yara, eg 4.0.5 still being able to use an earlier version of a compiled rules file, eg 4.0.2, but not the other way around (eg 4.0.2 yara can't run 4.0.5 rules file).  Or is this just a recipe for disaster?

Thanks for your time.

**Comment by mhuth** [comment]
Actually, looking at this again.  It seems the code in the releases are consistent, ie release 4.0.2 and release 4.0.5 both create and read compiled rules files with hdr.version of 17.  But the latest code in the repo, the major.minor.micro is 4.0.2 and creates compiled rules files with hdr.version 18.  This is a little inconsistent and confusing compared to the code in the releases! :) (and what was tripping me up in my first comment).  I shall just stick to the code in the releases and not build yara from master in the repo.

However I still have a suggestion.  Perhaps the version and the tag (major.minor numbers) could be consistent.  For example, major.minor of 4.0 could correspond to version 40.  Then when you need to change to version 41, update the tags/major.minor to be 4.1.  Then its easy to know which versions of yara are going to work with which versions of a compiled rules file.  That is, if I update to say, yara 4.1, then I know its not going to be able to read my version 40 compiled rules files.

Another suggestion, perhaps add this internal version number to the --version option.  Eg yara -v yields 4.0.5 (internal v17).  And you can find out the version of a compiled rules file with, say, yara -V compiled_rules_file.yar ... 17.

**Comment by wxsBSD** [comment]
Just a quick comment: there is a v4.0.x branch where the releases have been coming from.
