### ISSUE TITLE
Missing copy of GPLv3 for libyara/grammar.c

### ISSUE THREAD

**Issue by joachimmetz** [VirusTotal/yara#1475]
I was not able to find a copy of GPLv3 as indicated by libyara/grammar.c

https://github.com/VirusTotal/yara/blob/2893100786a3e2557d464a3868c963c1e3558d95/libyara/grammar.c

Please add LICENSE.GPLv3 (or equiv) in the root of the source or in a licenses subdirectory

**Comment by plusvic** [comment]
Including a copy of GPLv3 doesn't seems to be a requirement, as the license says:

```
As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton
```

In Bison's website they provide more information: 
https://www.gnu.org/software/bison/manual/html_node/Conditions.html

So, even if Bison itself is licensed under GPL, they include an exception for the Bison-generated code, which can be re-licensed under your own conditions (unless your writing another parser generator).

This seems to be the general consensus:

http://www.cplusplus.com/forum/lounge/11795/
https://arxiv.org/pdf/1412.2963.pdf

**Comment by joachimmetz** [comment]
I see, thx for the context. This is just the 1-to-1 code generated by bison. That answers my concern.
