### ISSUE TITLE
无法解析的外部符号 compile_files

### ISSUE THREAD

**Issue by mfxiaosheng** [VirusTotal/yara#1499]
1>正在生成代码...
1>yara.obj : error LNK2019: 无法解析的外部符号 compile_files，函数 main 中引用了该符号
1>yara.obj : error LNK2019: 无法解析的外部符号 define_external_variables，函数 main 中引用了该符号
1>D:\code\Windows-driver-samples-master\filesys\miniFilter\avscan\yara-master\windows\vs2017\\Debug\yara64.exe : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by plusvic** [comment]
I'm sorry, but you are not providing enough context about this error. Can you explain a bit more about your issue?

**Comment by jianxinguocn** [comment]
> 1>正在生成代码...
> 1>yara.obj : error LNK2019: 无法解析的外部符号 compile_files，函数 main 中引用了该符号
> 1>yara.obj : error LNK2019: 无法解析的外部符号 define_external_variables，函数 main 中引用了该符号
> 1>D:\code\Windows-driver-samples-master\filesys\miniFilter\avscan\yara-master\windows\vs2017\Debug\yara64.exe : fatal error LNK1120: 2 个无法解析的外部命令

Do you have solutions?

**Comment by plusvic** [comment]
It looks like the Visual Studio project for VS2017 is out of date, I recommend using the VS2015 project instead.

**Comment by jianxinguocn** [comment]
> It looks like the Visual Studio project for VS2017 is out of date, I recommend using the VS2015 project instead.

Yes VS2015 is correct! VS2017 project file doesn't work
