### ISSUE TITLE
yara index.yar target-file cant use!

### ISSUE THREAD

**Issue by fuwenbo-linux** [VirusTotal/yara#1504]
when i generate the index.yar after ./index_gen.sh
the error message shows below
error: rule "Windows_Malware" in ./malware/MALW_AZORULT.yar(960): can't open include file: ./webshells/WShell_PHP_Anuna.yar

how to solve it ? ~_~

**Comment by plusvic** [comment]
What `index_gen.sh` are referring to? I think that's from some repository with YARA rules.

**Comment by fuwenbo-linux** [comment]
> What `index_gen.sh` are referring to? I think that's from some repository with YARA rules.

sry,i didnt notice the yara_rule project is anthor repository.
