### ISSUE TITLE
Bug: PDB info is not properly parsed if the address is given via raw offset

### ISSUE THREAD

**Issue by ladislav-zezula** [VirusTotal/yara#1505]
Sample: `0249e00b6d46bee5a17096559f18e671cd0ceee36373e8708f614a9a6c7c079e`

YARA doesn't check any PDB path on this sample. This is because in the `IMAGE_DEBUG_DIRECTORY`, there's:
```
Characteristics   0x00000000
TimeDateStamp   0x545c2f69
MajorVersion   0x0000
MinorVersion   0x0000
Type   0x00000002
SizeOfData   0x00000040
AddressOfRawData   0x00000000
PointerToRawData   0x0000b000
```
The debug info is at raw offset `0x0000b000` in the overlay.

**Comment by plusvic** [comment]
Fixed in #1506
