### ISSUE TITLE
Destroy all YR_RULES associated with a given compiler when yr_compiler_destroy() is called?

### ISSUE THREAD

**Issue by jgegeny** [VirusTotal/yara#1531]
I have not deep dived into the source code yet, but I read the following in the documentation:

> Once yr_compiler_get_rules() is invoked you can not add more sources to the compiler, but you can call yr_compiler_get_rules() multiple times. Each time this function is called it returns a pointer to the same YR_RULES structure. Notice that this behaviour is new in YARA 4.0.0, in YARA 3.X and 2.X yr_compiler_get_rules() returned a new copy the YR_RULES structure.
> 
> Instances of YR_RULES must be destroyed with yr_rules_destroy()
> 

If it returns now the same pointer, would not it be reasonable to save the user from an extra call to yr_rules_destroy() and destroy the rules when the compiler is destroyed?

**Comment by plusvic** [comment]
As the compiler is independent from the rules existing code can destroy the compiler before the rules are actually used. For maintaining backward compatibility we can't asume that the compiler will be maintained in memory as long as the rules are needed.
