### ISSUE TITLE
Root node

### ISSUE THREAD

**Issue by Karlos76** [VirusTotal/yara#1543]
What is this?
Android.Android.WIN32.SpyNote.e
9a2c20b8c411025d37676aff50c1b37b6d9651c592b1c97dc4ab24edc84ba569

**Comment by plusvic** [comment]
What do you mean with this issue?

**Comment by Karlos76** [comment]
I recently did a scan and noticed a malicious file in the Carrier Services system application.  I did a factory reset of the device to remove this malicious file.
