### ISSUE TITLE
Matching regex within specified range

### ISSUE THREAD

**Issue by Still34** [VirusTotal/yara#1547]
## Expected Behavior

Consider the following rule,

```yara
  strings:
    $a = /[A-z0-9]{5,10}/
  condition:
    $a at 0 and $a in (100..200)
```

The expected behavior is `$a` at offset `0x0` and `$a` between offset decimal 100 to 200 should be matched.

## Current Behavior

However, it appears that no matter where the ranges are specified, all matching values throughout the target binary will be added to the results. Is this an intended behavior?

**Comment by plusvic** [comment]
Yes, that's the intended behavior. The condition controls whether or not the rule matches, but it doesn't control the output of the `--print-strings` command-line argument. If the rule matches all the matching strings are printed, regardless of the condition.

**Comment by Still34** [comment]
Is there not a way for it to just perform the search within the specified range? Seems kinda redundant to scan through the entire binary when the condition calls for a range scan.

**Comment by plusvic** [comment]
No, there's no way for specifying the range in which you want to perform the scan. YARA first searches for all the strings (from all the rules) at the same time, and once it knows which are the matching strings it proceeds to evaluate the rule. When the scan phase is executed YARA doesn't know about the range limits imposed by the condition. The reason for this behavior is that YARA is designed with the multi-rule case in mind, in such cases is more efficient to search for all the strings at once in all the file.
