### ISSUE TITLE
Unable to specify aboslute path with namespace in yara and yarac 

### ISSUE THREAD

**Issue by zagge-cgeo** [VirusTotal/yara#1593]
It is not possible to specify an absolute path with a namespace in the command line 

`yara foo:/home/user/yara/rules.yar  .`
`error: could not open file: foo:/home/user/yara/rules.yar`

The file `/home/user/yara/rules.yar`  exists.

It seems this bug was introduced when fixing

https://github.com/VirusTotal/yara/issues/718

**Comment by plusvic** [comment]
Fixed in e21982a77f5534655b697ad0f7f09ad3ddd142bd
