### ISSUE TITLE
The pointer yyptr is not free

### ISSUE THREAD

**Issue by JerryDevis** [VirusTotal/yara#1596]
In the hex_grammar.c, The pointer yyptr is not free.
![image](https://user-images.githubusercontent.com/89641128/143980990-0b250728-a235-4b30-a5f8-becf2676ffe5.png)

**Comment by plusvic** [comment]
`yyptr` is allocated with memory from the stack, via a call to `alloca` (https://man7.org/linux/man-pages/man3/alloca.3.html). This type of allocation is freed when the memory returns, and doesn't need explicit deallocation.

**Comment by JerryDevis** [comment]
> `yyptr` is allocated with memory from the stack, via a call to `alloca` (https://man7.org/linux/man-pages/man3/alloca.3.html). This type of allocation is freed when the memory returns, and doesn't need explicit deallocation.

OK, thank you.
