### ISSUE TITLE
Process scan: target process is killed (OOM)

### ISSUE THREAD

**Issue by msuhanov** [VirusTotal/yara#1620]
Hello.

YARA version: 4.1.3.

In one environment (GNU/Linux), attempts to scan several processes result in the KILL signal being sent to _these processes_ (not to the _yara_ process) by the OOM killer.

Further investigation demonstrated that each process has a large amount of anonymous mappings, most of them have their pages swapped. Reading such memory brings swapped pages into the resident set, and the OOM killer is triggered (against the process being scanned).

I see some tweaks merged into the main branch (https://github.com/VirusTotal/yara/commit/605b2edf07ed8eb9a2c61ba22eb2e7c362f47ba7 and https://github.com/VirusTotal/yara/commit/063cbfb793a9bbf2d996c83a66d8713b0e0e3e1c), but they won't protect against this situation (because mappings are anonymous, there are many of them, and there are multiple processes sharing the same properties).

My proposal is to implement a command-line argument to disable scanning of swapped pages. Later, this functionality could be extended and swapped pages could be read directly from a swap file (thus, memory pressure would affect the scanning process only).

I'm attaching a patch for your review (2021-12-18 08:00 UTC: fixed a wrong type, uploaded again).
[yara_patch_ignore_swapped_pages.txt](https://github.com/VirusTotal/yara/files/7738934/yara_patch_ignore_swapped_pages.txt)

(I will make a pull request once the proposal is accepted.)

**Comment by hillu** [comment]
> I see some tweaks merged into the main branch ([605b2ed](https://github.com/VirusTotal/yara/commit/605b2edf07ed8eb9a2c61ba22eb2e7c362f47ba7) and [063cbfb](https://github.com/VirusTotal/yara/commit/063cbfb793a9bbf2d996c83a66d8713b0e0e3e1c)), but they won't protect against this situation (because mapping are anonymous, there are many of them, and there are multiple processes sharing the same properties).

Have you tried this?

Since I'm responsible for 063cbfb793a9bbf2d996c83a66d8713b0e0e3e1c, I'm curious: With what kinds of processes (which software?) are you running into these problems? Would you mind sharing samples of `/proc/$PID/maps` dumps for those processes?

**Comment by msuhanov** [comment]
These are Java processes running in a production environment. Unfortunately, this is not my system.

**Comment by hillu** [comment]
Again: Have you tried whether the patches, particularly 063cbfb793a9bbf2d996c83a66d8713b0e0e3e1c, do anything to change the situation?

Can you tell us more about the software on those affected systems? How much RAM, how much swap is available? And a dump of `/proc/$PID/maps` would be useful.

**Comment by msuhanov** [comment]
Since there are no updates, I'm closing this issue, although it's not fixed.

**Comment by hillu** [comment]
> Since there are no updates from maintainers, I'm closing this issue, although it's not fixed.

@msuhanov I had asked for some extra information. Ignoring that and then claiming that claiming that there hasn't been a reaction and that the issue hasn't been fixed seems a bit weird.

Have you been able to reproduce the issue with YARA 4.2.0 which has been released in the meantime?
