### ISSUE TITLE
MSVC C++ compilation breaking header

### ISSUE THREAD

**Issue by VelocityRa** [VirusTotal/yara#1635]
This should be changed https://github.com/VirusTotal/yara/blob/master/libyara/include/yara/object.h#L33-L37, it breaks compilation if the user or any other library (gtest in my case) does `std::isnan` (from the `<cmath>` STL header).

**Comment by plusvic** [comment]
Fixed in 074f2467912265867a2eedcdb7c9e2f4227f895b
