### ISSUE TITLE
YARA 4.2.0 getting test-rules failed error 134 on ParrotOS v5.0

### ISSUE THREAD

**Issue by mike1136** [VirusTotal/yara#1666]
Hello everyone,
I tried installing YARA using the installation guide on ParrotOS v5.0, but for some reason it fails the test-rules with the following error:
![image](https://user-images.githubusercontent.com/5704433/160178958-4c3b5d4e-b31a-490e-9f4d-bfcdeab561fe.png)

![image](https://user-images.githubusercontent.com/5704433/160177294-dce6d8ba-29c1-40cd-aad3-16ec293bf0f3.png)

My OS info is this
![image](https://user-images.githubusercontent.com/5704433/160177948-2c29f449-bada-466c-b08a-076a6981b5c9.png)

Is this something that I should check out, or can it be safely ignored?
I tried looking up for any information but couldn't find any.

Thanks in advance for any help

**Comment by wxsBSD** [comment]
Probably safe to ignore if you're not scanning processes. However, @hillu has done work recently in this area so he may want to chime in here.

**Comment by hillu** [comment]
@mike1136 Is the build being performed on a tmpfs? Adding commit 9ab96d1d8f6d6312bda763affc22ec2ee06f3929 should help in that case.

**Comment by mike1136** [comment]
> @mike1136 Is the build being performed on a tmpfs? Adding commit [9ab96d1](https://github.com/VirusTotal/yara/commit/9ab96d1d8f6d6312bda763affc22ec2ee06f3929) should help in that case.

Adding this fixed it.
Thanks!
