### ISSUE TITLE
--skip-larger not working

### ISSUE THREAD

**Issue by BitsOfBinary** [VirusTotal/yara#1677]
For YARA v4.2.0, I can't get the `--skip-larger` flag to work.

I can't see what the cause of this is, but it doesn't seem to take into account the size parameter at all from the command line.

**Comment by BitsOfBinary** [comment]
This was tested on Windows 10 for context

**Comment by plusvic** [comment]
Actually the `--skip-larger` feature was not implemented in Windows at all. I've done it in #1678. Right now I don't have a Windows machine around for testing, could check it works? Here you have a compiled `yara` binary with the fix: [yara-fix_1677-1903-win64.zip](https://github.com/VirusTotal/yara/files/8425220/yara-fix_1677-1903-win64.zip)

**Comment by BitsOfBinary** [comment]
Thank you @plusvic! Just tested the fix locally on my Windows machine, and can see it is skipping files. Looks like your fix does the trick 👍

**Comment by plusvic** [comment]
Great!
