### ISSUE TITLE
Compile Yara 3.1 on Macos

### ISSUE THREAD

**Issue by juju4** [VirusTotal/yara#168]
Hello, 
compiling yara 3.1 on Mac 10.9.4 failed with macports.

There is a small issue with strlcpy (add **APPLE** exclusion to utils.h like *BSD) but after more annoying some internal redefinitions

---

:info:build /bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/clang -DHAVE_CONFIG_H -I. -I..   -I/opt/local/include -O3 -Wall -std=gnu99 -I./include -pipe -Os -std=gnu89 -arch x86_64 -c -o exec.lo exec.c
:info:build libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I.. -I/opt/local/include -O3 -Wall -std=gnu99 -I./include -pipe -Os -std=gnu89 -arch x86_64 -c exec.c  -fno-common -DPIC -o .libs/exec.o
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:29:25: warning: redefinition of typedef 'mutex_t' is a C11 feature [-Wtypedef-redefinition]:info:build typedef pthread_mutex_t mutex_t;
:info:build                         ^
:info:build ./include/yara/types.h:31:25: note: previous definition is here
:info:build typedef pthread_mutex_t mutex_t;
:info:build                         ^
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:32:17: warning: redefinition of typedef 'tidx_mask_t' is a C11 feature [-Wtypedef-redefinition]
:info:build typedef int32_t tidx_mask_t;
:info:build                 ^
:info:build ./include/yara/types.h:34:17: note: previous definition is here
:info:build typedef int32_t tidx_mask_t;
:info:build                 ^
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:114:9: warning: 'MAX_THREADS' macro redefined
:info:build #define MAX_THREADS sizeof(tidx_mask_t) \* 8
:info:build         ^
:info:build ./include/yara/limits.h:25:9: note: previous definition is here
:info:build #define MAX_THREADS     32
:info:build         ^
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:274:9: warning: 'STRING_MATCHES' macro redefined
:info:build #define STRING_MATCHES(x) (x->matches[yr_get_tidx()])
:info:build         ^
:info:build ./include/yara/types.h:170:9: note: previous definition is here
:info:build #define STRING_MATCHES(x) \
:info:build         ^
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:277:16: error: redefinition of '_YR_RELOC'
:info:build typedef struct _YR_RELOC
:info:build                ^
:info:build ./include/yara/arena.h:30:16: note: previous definition is here
:info:build typedef struct _YR_RELOC
:info:build                ^
:info:build In file included from exec.c:29:
:info:build /opt/local/include/yara.h:282:3: error: typedef redefinition with different types ('struct YR_RELOC' vs 'struct _YR_RELOC')
:info:build } YR_RELOC;
:info:build   ^ 
:info:build ./include/yara/arena.h:35:3: note: previous definition is here
[...]

---

Any help?

Thanks

**Comment by aschuster99** [comment]
Try deactivating the old version first (port deactivate yara @<vers>). If that helps, than it's likely a problem with the include search path. I guess that -I./include should go in front of -I/opt/local/include. Is this a problem with the Portfile, or with YARA's Makefile?

**Comment by plusvic** [comment]
Closing as this is a very old issue. Please re-open if still valid.
