### ISSUE TITLE
RE Lexer improperly parsing dashes after character classes

### ISSUE THREAD

**Issue by Sevaarcen** [VirusTotal/yara#1690]
When using a regular expression containing a character class, followed by a dash `-`, followed by anything else, Yara fails with the following error:
```
$ /usr/bin/yara -s ~/testrule.yara ~/yara_test_file.txt 
~/testrule.yara(3): error: invalid regular expression "$": bad character range
```

It appears this error message is related to the following section of the RE lexer, where it doesn't properly look for the ending square bracket of the character range and therefore over-matches on the dash outside.
https://github.com/VirusTotal/yara/blob/7e00915f1594b60fa19b39f29f77c046c99b14fe/libyara/re_lexer.l#L311

This is the test rule I'm using, and the test file being scanned.
```
$ cat ~/testrule.yara 
rule test {
        strings:
                $ = /[0-9]-2/
        condition:
                all of them
}
```
```
$ cat ~/yara_test_file.txt 
1-2-3-4-5
```

Using grep, regex101, or similar, we can confirm the regex works as expected and is valid.
```
$ cat ~/yara_test_file.txt | grep -o "[0-9]-2"
1-2
```

**Comment by plusvic** [comment]
Fixed in a91b8a1eece43f8e32af8988d6d392c335df019f and ee96a35dad4b0b4937e44a3eb8e9fd53c662a777.
