### ISSUE TITLE
How to report potential security issue?

### ISSUE THREAD

**Issue by briangreenery** [VirusTotal/yara#1693]
I think I found a potential security issue, and I created a test that reliably reproduces it. Should I open a github issue with the details, or is there another way that I should report this?

**Comment by plusvic** [comment]
If the issue allows arbitrary code execution or crashing YARA by crafting a malicious rule in source form, you can send me the details to vmalvarez@virustotal.com. Everything else could be reported here I think.

**Comment by briangreenery** [comment]
I sent an email just to be safe. Thanks!
