### ISSUE TITLE
'none' new token doesn't work as expected

### ISSUE THREAD

**Issue by lupiotte** [VirusTotal/yara#1695]
Hello,

From my understanding the "none" statement ("none" keyword https://github.com/VirusTotal/yara/pull/1559/files ) doesn't work as I expect ;). Indeed even if a string appear in a scanned file the expression using "none" will report a true condition.
I have leveraged different version yara-v4.2.1-1934-win64 / yara-master-1798-win64 / yara-4.2.0 with the same issue.
Test done via official precompiled binaries (only x64 version tested) and executed under Windows environement (W10).

BTW you haven't included in your testing rules tests (tests/test-rules.c) which should have highlighted this issue.
![image](https://user-images.githubusercontent.com/8994001/165723072-5dfdb000-5e1d-4eee-84c8-79c9d7141256.png)

Something like:

assert_**false**_rule(
      "rule test { strings: $a = \"dummy1\" $b = \"dummy2\" $c = \"ssi\" "
      "condition: none of them }",
      TEXT_1024_BYTES "mississippi");

assert_**false**_rule(
      "rule test { strings: $a1 = \"dummy1\" $b1 = \"dummy2\" $b2 = \"ssi\""
      "condition: none of ($a*, $b*) }",
      TEXT_1024_BYTES "mississippi");
 
Hope it's help.

_Originally posted by @lupiotte in https://github.com/VirusTotal/yara/issues/1559#issuecomment-1111992280_

**Comment by wxsBSD** [comment]
I think you're right about this. I should have a fix up very soon.

**Comment by wxsBSD** [comment]
At least in my defense this has nothing to do with the `none` keyword. You can get the same behavior with `0 of them` as a condition. ;)

I think this is actually a long standing bug, but either way a fix is incoming!
