### ISSUE TITLE
YR_MICRO_VERSION is still 0 (should be 1)

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1706]
Looks like the newest version of yara has incorrect YR_MICRO_VERSION value specified meaning --version and --help information is inaccurate on terminal.

`https://github.com/VirusTotal/yara/blob/master/libyara/include/yara/libyara.h`

**Comment by xambroz** [comment]
This is also in configure.ac 
AC_INIT([yara], [4.2.0], [vmalvarez@virustotal.com])

**Comment by plusvic** [comment]
Fixed in #1741
