### ISSUE TITLE
Wrong offset used when checking Version string of .net metadata

### ISSUE THREAD

**Issue by dangodangodango** [VirusTotal/yara#1708]
https://github.com/VirusTotal/yara/blob/ee78353155c10c20e0acc630762f5d1e57ce64c4/libyara/modules/dotnet/dotnet.c#L1710-L1728

https://github.com/VirusTotal/yara/blob/ee78353155c10c20e0acc630762f5d1e57ce64c4/libyara/modules/dotnet/dotnet.c#L1637-L1657

The above two places (line 1653 and line 1724) are checking whether metadata version string is fits in pe, Version string offset is `pe->data + offset + sizeof(NET_METADATA)`, and size is `md_len`. But the above code checks the md_len bytes starting from `offset` (which is `metadata_root`)

The correct code should be as follows:
```c
!fits_in_pe(pe, pe->data + offset + sizeof(NET_METADATA), md_len)
```

And in the function `dotnet_is_dotnet`, the variable `offset` is not updated to metadata_root, so in line 1653, `offset` is still the offset of `CLI_HEADER`, this is also a problem.

**Comment by dangodangodango** [comment]
https://github.com/VirusTotal/yara/blob/ee78353155c10c20e0acc630762f5d1e57ce64c4/libyara/modules/dotnet/dotnet.c#L1658-L1676

And in ine 1670, shouldn't it be `entry_offset < 0` instead of `offset < 0`?

**Comment by wxsBSD** [comment]
I think you're right. Any chance you plan to submit https://github.com/dangodangodango/yara/commit/ac715044b529683afe1124c2f6100f330f5afb93 as a PR? I think it is the correct fix (but I haven't tested it to be honest).
