### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [VirusTotal/yara#1726]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@sudhackar) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by plusvic** [comment]
You can wrote to vmalvarez @ virustotal.com

**Comment by plusvic** [comment]
Added a `SECURITY.md` file in 479115720e91e695eb5607a82f5c379ac894eaf6.
