### ISSUE TITLE
Erroneous exit status code reported when using -D

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1752]
I have an old script where I'm using subprocess to run YARA on Windows and it reports a bad exit code leading subprocess to think that it broke when it ran successfully:

```
import subprocess, sys

yara_bin = "yara64" # needs to be on %PATH% or available in current directory
path_to_dotnet_yar = r"/path/to/dotnet_info.yar"

c = subprocess.check_output([yara_bin, path_to_dotnet_yar, "-D", sys.argv[1]])
```

`path_to_dotnet_yar` is a path to a YARA rule containing the following rule:

```
import "dotnet"

rule example_rule
{
condition:
        false
}
```

When run, this script yields:

```subprocess.CalledProcessError: Command '['yara64', 'C:\\Users\\malware\\Documents\\analysis\\dotnet_info.yar', '-D', 'any_dotnet_file_goes_here.bin']' returned non-zero exit status 3221226505.```

When this is run normally on the command line, the correct output is produced.

@wxsBSD has pointed me towards this gist (https://gist.github.com/wxsBSD/1e518cef545fee7bb991a9dc6c14a0f7) which suggests I can do the same thing without subprocess, but this probably still should be resolved for the sake of completeness

**Comment by tlansec** [comment]
Can reproduce same bug on 4.2.0, 4.2.1.

Same bug not reproducable using 4.1.0 binary.

**Comment by wxsBSD** [comment]
I'm able to reproduce this on 4.2.2, 4.2.1 and 4.2.0-rc1, though 4.2.0-rc1 is interesting, but not on 4.1.3. I think the output of 4.2.0-rc1 is a clue to what is going on:

<img width="922" alt="Screen Shot 2022-07-21 at 11 59 39 AM" src="https://user-images.githubusercontent.com/1394879/180260209-99e24223-417d-4cac-928a-e16255a84a53.png">

I'll keep debugging but whatever is going on here is somehow only triggerable via python subprocess, which seems very weird. If I run `yara64.exe -D` directly I don't see anything wrong.

**Comment by wxsBSD** [comment]
OK, this can be reproduced without python at all. I'm able to trigger it with `yara64 -D ..\always_false.yara ..\737233cb62bcacb17ae4e4ce6f321336b8b8578f26a63da7ea695bc73342e276 | more` - it seems to go sideways after the first 0x1000 bytes of output.
