### ISSUE TITLE
Support for ARM64EC and ARM64X

### ISSUE THREAD

**Issue by urianpaul94** [VirusTotal/yara#1774]
Hello,

Does https://yara.readthedocs.io/en/stable/modules/pe.html# support detection of ARM64EC and ARM64X binaries?
More info on that binaries can be found here: https://ffri.github.io/ProjectChameleon/new_reloc_chpev2/

I'd like to create a yara rule to detect all ARM64EC/X binaries from a corpus of Windows binaries.

Thanks,
Paul

**Comment by wxsBSD** [comment]
I don't know if we have constants defined for those but there's no reason you couldn't check the appropriate fields in the NT header with the appropriate bitmask without using the constants.

From a quick glance at the link you sent it should be possible to detect these fairly easily.

**Comment by urianpaul94** [comment]
Ok, thanks.
Then I think that we can close this issue.
