### ISSUE TITLE
Hex rule doesn't work with ascii and base64 modifiers together

### ISSUE THREAD

**Issue by CatyGreen** [VirusTotal/yara#1785]
Hi!

I want to develop a rule that detect an hex pattern both in ascii and base64. My first try was to write this rule:

`$pattern = "\xAA\xBB\xCC\xDD\xEE\xFF" ascii base64`

but it doesn't work when the file contains the hex pattern. To make it work I've to create two rules:
```
$patternHex = "\xAA\xBB\xCC\xDD\xEE\xFF" 
$patternB64 = "\xAA\xBB\xCC\xDD\xEE\xFF" base64
```
Am I doing something wrong? In the documentation it seems that both ascii and base64 can work together.
Thanks

**Comment by wxsBSD** [comment]
This is actually documented in https://yara.readthedocs.io/en/stable/writingrules.html#base64-strings:

```
The interaction between base64 (or base64wide) and wide and ascii is as you might expect. wide and ascii are applied to the string first, and then the base64 and base64wide modifiers are applied. At no point is the plaintext of the ascii or wide versions of the strings included in the search. If you want to also include those you can put them in a secondary string.
```

Exactly why it works this way is a bit complex to explain but it boils down to the way YARA searches and verifies string matches, and making it work the way you want is rather complex.
