### ISSUE TITLE
Possible but with matching when using string offsets

### ISSUE THREAD

**Issue by djlukic** [VirusTotal/yara#1789]
Hi,

I think there is a bug where Yara only matches first occurence of certain strings. Steps to reproduce:

Make **test.txt** and put this content inside
`virustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetcompany`

Ruleset to test with
```
rule test {

	strings:
	
		$a = "virus"
		$b1 = "total"
		$b2 = "google"
		$b3 = "alphabet"
		$b4 = "company"
		
	condition:
	
		$a and all of ($b*) in (@a .. @a + 100)
		
}
```

Rule doesn't match. 

However if you comment out **$b4** it matches.
Why is this happening? Is it because yara only matches the first occurence of strings and doesn't go deeper, meaning it matches **$a, $b1, $b2 and $b3** and because **$b4** isn't there it failes to match. However it should try to match it elsewhere in the file but it apparently doesn't go further.

Thank you!

**Comment by r0ny123** [comment]
It works for me.

**Comment by djlukic** [comment]
> It works for me.

I tried with two different files, no hits.

**Comment by r0ny123** [comment]
```bash
Rony@Rony ~/desktop/test
$ cat test.yar
rule test {

        strings:

                $a = "virus"
                $b1 = "total"
                $b2 = "google"
                $b3 = "alphabet"
                $b4 = "company"

        condition:

                $a and all of ($b*) in (@a .. @a + 100)

}
Rony@Rony ~/desktop/test
$ cat test.txt
virustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetvirustotalgooglealphabetcompany
Rony@Rony ~/desktop/test
$ yara test.yar .
test .\test.yar
```

**Comment by r0ny123** [comment]
Ah sorry, for the confusion. It didn't match. I think `@a` evaluates as the first occurrence of `$a`, this is how it is implemented. So, this is not a bug. 
For `test.txt` to match you can do something like this for now:

```YARA
rule test
{

	strings:

		$a = "virus"
		$b1 = "total"
		$b2 = "google"
		$b3 = "alphabet"
		$b4 = "company"

	condition:

		$a and
		for any i in (1 .. #a) : (
			for all of ($b*) : (
				$ in (@a[i] .. @a[i] + 100)
			)
		)

}
```

**Comment by wxsBSD** [comment]
I think @r0ny123 is right here. Also, here is a concise way of expressing the logic:

```
    for any i in (1..#a):
      (all of ($b*) in (@a[i]..@a[i] + 100))
```

If you are concerned that $a may match a lot of times you can use `math.min(#a, 50)` or some reasonable upper bound in your condition, like this:

```
    for any i in (1..math.min(#a, 50)):
      (all of ($b*) in (@a[i]..@a[i] + 100))
```

**Comment by djlukic** [comment]
Thank you both for the explanation.
