### ISSUE TITLE
Zero bytes slow down scanning workaround

### ISSUE THREAD

**Issue by djlukic** [VirusTotal/yara#1792]
Hi,

Is there a way to specify that certain number of zero bytes is present at given offset without may slow down warning?

This can be useful to warn about certain anomaly in file structure.

Right now in condition you can say uint32(0) == 0x00000000 but what if I wanted to say 20 bytes at offset 20 is all zeroes?

Thanks.

**Comment by plusvic** [comment]
Interesting question. The solution that comes to my mind is using the `hash` module, for example you can write something like 

```
hash.md5(20,20) == "<whichever is the md5 for 20 zeroes>"
```

That should be a lot faster than looking for a string full of zeroes.

**Comment by djlukic** [comment]
Interesting solution but I couldn't do it. I think there is some mismatch with md5 calculation. 
I tried both 
`00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`
and
`0000000000000000000000000000000000000000`
when calculating md5 but couldn't match it with yara rule.

**Comment by plusvic** [comment]
The `md5` for 20 consecutive zeroes is `441018525208457705bf09a8ee3c1093`, that should work.

**Comment by plusvic** [comment]
If you are in Linux, this did the trick for me... 

```bash
$ dd if=/dev/zero bs=1 count=20 | md5
```

**Comment by djlukic** [comment]
Thanks, I did the calculation with Python in the end and was able to detect a sample with Yara.

```
import hashlib

with open(file, 'rb') as f:
    f.seek(20)
    data = hashlib.md5(f.read(20)).hexdigest()
    print(data)
```
