### ISSUE TITLE
yara Accessing data at a given position support  type conversion

### ISSUE THREAD

**Issue by avkiller** [VirusTotal/yara#1800]
Is it possible to support hex -- int compare or hex  convert int 

Case 1
rule test1
{
  
    condition:
       uint32(12)== filesize
}

Case 2 

rule test2
{
  
    condition:
       int(uint32(12))== 2048
}

**Comment by wxsBSD** [comment]
Not sure I understand your question but these are the same thing:

uint8(0) == 16

uint8(0) == 0x10

**Comment by avkiller** [comment]
thank you wxsBSD
