### ISSUE TITLE
Adding our software to the "Who's using YARA" section

### ISSUE THREAD

**Issue by 0x100001** [VirusTotal/yara#1802]
Hey there,

our company added yara support into our monitoring software NetLock.
The user has the possibility of performing scans on new spawned processes or do entire scan jobs.

We would love to be added on the "Who's using YARA" section. Is that possible?

Currently the website and documentation is only availiable in german. It will be translated soon.

Company: 0x101 Cyber Security
Website: https://0x101-cyber-security.de

YARA references:
https://wiki.0x101-cyber-security.de/de/Produkte/NetLock/Management_Console/Clients/YARA_Einstellungen_Jobs
https://wiki.0x101-cyber-security.de/de/Produkte/NetLock/Management_Console/Regels%C3%A4tze/YARA

Thank you,
Nico :)

**Comment by plusvic** [comment]
Sure, just submit a pull request with the desired change to the README.md file.
