### ISSUE TITLE
Behaviour of SCAN_FLAGS_PROCESS_MEMORY

### ISSUE THREAD

**Issue by killswitch-GUI** [VirusTotal/yara#1815]
I dont see a "question" type issue. I was hoping to document on our side what `SCAN_FLAGS_PROCESS_MEMORY` is and make sure we clearly understand why one wouldn't use this every time when scanning process memory?

**Comment by plusvic** [comment]
`SCAN_FLAGS_PROCESS_MEMORY` is set internally when you call `yr_scanner_scan_mem`, and is it not expected to be set by outside callers. The only thing it does is telling YARA that the `entrypoint` keyword should return a memory address and not a file offset.

**Comment by killswitch-GUI** [comment]
> `SCAN_FLAGS_PROCESS_MEMORY` is set internally when you call `yr_scanner_scan_mem`, and is it not expected to be set by outside callers. The only thing it does is telling YARA that the `entrypoint` keyword should return a memory address and not a file offset.

Thanks for this! We are using Go-yara and allows this as a flag.
