### ISSUE TITLE
Why the default value of YR_MAX_ATOM_LENGTH is 4 ?

### ISSUE THREAD

**Issue by X3h1n** [VirusTotal/yara#1816]
Recently, we read the yara source code and find the YR_MAX_ATOM_LENGTH is set to 4. In the limits.h , the YR_MAX_ATOM_LENGTH is defined as maximum size for the substring (atoms) extracted from strings and regular expressions and put into the Aho-Corasick automaton. The maximum allows size for this constant is 255." The larger the value of YR_MAX_ATOM_LENGTH, the more substrings are put into the Aho-Corasick automaton and the shorter the scan time. I don't know if my understanding is correct.
So why YR_MAX_ATOM_LENGTH default value is set to 4? Is 4 a good value obtained after many experiments? Looking forward to your reply, thank you !

**Comment by plusvic** [comment]
The value for `YR_MAX_ATOM_LENGTH` is a tradeoff between scanning speed and size of the compiled rules. With larger values of `YR_MAX_ATOM_LENGTH` the scanning time should be reduced, but the compiled rules grow in size. The 4 value has proven to be a good one in practice.
