### ISSUE TITLE
Question: How can I match multiple import functions with ELF module?

### ISSUE THREAD

**Issue by dmknght** [VirusTotal/yara#1818]
Yara version: 4.2.3
Elf file has structure like this:
```
elf
  symtab
    [54]
			name = "htons@GLIBC_2.2.5"
			value = 0
			size = 0
			type = 2
			bind = 1
			shndx = 0
    [55]
			name = "dup2@GLIBC_2.2.5"
			value = 0
			size = 0
			type = 2
			bind = 1
			shndx = 0
```

From all resources I can find, I can search 1 import function
```
for any i in (0 .. elf.symtab_entries):
  (elf.symtab[i].name == "htons@GLIBC_2.2.5" and elf.symtab[i].type == elf.STT_FUNC)
```
Problem comes when I want to check multiple values. The only solution I can think is
```
for any i in (0 .. elf.symtab_entries):
 (elf.symtab[i].name == "htons@GLIBC_2.2.5" and elf.symtab[i].type == elf.STT_FUNC)
and for any i in (0 .. elf.symtab_entries):
 (elf.symtab[i].name == "dup2@GLIBC_2.2.5" and elf.symtab[i].type == elf.STT_FUNC)
```
It seems works, but it doesn't very good because I have to call multiple for loops.
There's an other way could be a solution but I don't really like it (obfuscated section names)
```
strings:
  $ = "htons" fullword
  $ = "dup2" fullword
for any i in (0 .. elf.number_of_sections):
  (elf.sections[i].name == ".strtab" and all of them)
```

So is there any better method to check multiple imported functions in ELF file?

**Comment by dmknght** [comment]
There's an other case that it seems too complicated with only for loop check: If i want to check if either `execv` or `execve` imported in ELF file and `htons` was imported
```
(
  for any i in (0 .. elf.symtab_entries):
   (elf.symtab[i].name == "execv" and elf.symtab[i].type == elf.STT_FUNC)
  or for any i in (0 .. elf.symtab_entries):
   (elf.symtab[i].name == "execve" and elf.symtab[i].type == elf.STT_FUNC)
) and
for any i in (0 .. elf.symtab_entries):
   (elf.symtab[i].name == "htons" and elf.symtab[i].type == elf.STT_FUNC)
```

**Comment by plusvic** [comment]
Well this could also work...

```yara
for 2 i in (0 .. elf.symtab_entries): (
   elf.symtab[i].type == elf.STT_FUNC and
   (
       elf.symtab[i].name == "htons@GLIBC_2.2.5" or  
       elf.symtab[i].name == "dup2@GLIBC_2.2.5"
   )
)
```

Notice that in this case it's `for 2 i in ...`, which means that at least two of the entries must match the condition inside the `for`. But of course this assumes that you can't have two entries in ` elf.symtab` with the same name. If that's the case the rule above would work, if not, the only solution is the one you found.

**Comment by dmknght** [comment]
> Notice that in this case it's for 2 i in ..., which means that at least two of the entries must match the condition inside the for

Thanks a lot for that. I think i missed it in documentation. But if the condition is more complicated, I think the only solution is multiple for loops (which could be much slower?). Let say that I want to match
- any of ("execv", "execve")
- any of ("dup", "dup2")
- any of ("htons", "htonl")
The condition can look like this
```
for 3 i in (0 .. elf.symtab_entries):
elf.symtab[i].type == elf.STT_FUNC and
   (
      ( elf.symtab[i].name == "htons" or elf.symtab[i].name == "htonl") or
       (elf.symtab[i].name == "exec" or elf.symtab[i].name == "execve") or
     // continue for dup, dup2 check
   )
```
It looks like the condition is similar to `3 of them` instead of `any of ($hton) and any of ($exec) and any of ($dup)`
Btw, i think `dynsym` is undocumented in ELF module?

**Comment by dmknght** [comment]
I think my last syntax can solve this problem (it's ugly because it requires too many for loops, but it's the only thing can do for now) so i'm closing this issue.
I hope Yara provides sort of syntax to do comparison like this in the future
