### ISSUE TITLE
Linker errors when trying to compile libyara as DLL

### ISSUE THREAD

**Issue by ApoIIy0n** [VirusTotal/yara#1866]
**Describe the bug**
When trying to compile libyara as a DLL it gives linker errors.

**To Reproduce**
Config Properties/General/Config type: Dynamic Lib
Config Properties/General/Preprocessor  add YR_BUILDING_DLL

**Expected behavior**
the DLL to be compiled without issues

**Screenshots**
![image](https://user-images.githubusercontent.com/107041454/214011281-15beaef1-017b-4f58-a31e-296c9d85d630.png)
![image](https://user-images.githubusercontent.com/107041454/214011386-64c66b4b-29c5-46b5-bcbb-c3f73f1ea563.png)

**Please complete the following information:**
 - OS: Windows10
 - YARA version: 4.2.3

**Additional context**
N/A

**Comment by ApoIIy0n** [comment]
found a working solution..

  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;CUCKOO_MODULE;HASH_MODULE;DOTNET_MODULE;HAVE_LIBCRYPTO;USE_WINDOWS_PROC;YR_BUILDING_DLL;BUCKETS_128;CHECKSUM_1B</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>..\..\..\libyara;..\..\..\libyara\include;..\..\..;..\packages\YARA.Jansson.x64.1.1.0\include;..\packages\YARA.OpenSSL.x64.1.1.1\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <DisableSpecificWarnings>4005;4273;4090</DisableSpecificWarnings>
      <CompileAs>CompileAsC</CompileAs>
      <ObjectFileName>$(IntDir)/%(RelativeDir)</ObjectFileName>
      <OmitFramePointers>false</OmitFramePointers>
      <PrecompiledHeaderFile />
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
    </ClCompile>
    <Lib>
      <AdditionalDependencies>jansson.lib;libcrypto.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <SuppressStartupBanner>true</SuppressStartupBanner>
      <LinkTimeCodeGeneration>false</LinkTimeCodeGeneration>
      <AdditionalLibraryDirectories>..\packages\YARA.OpenSSL.x64.1.1.1\lib;..\packages\YARA.Jansson.x64.1.1.0\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalOptions>/IGNORE:4221</AdditionalOptions>
    </Lib>
    <Link>
      <AdditionalDependencies>msvcrt.lib;Ws2_32.lib;crypt32.lib;..\packages\YARA.Jansson.x64.1.1.0\lib\jansson.lib;..\packages\YARA.OpenSSL.x64.1.1.1\lib\libcrypto.lib;..\packages\YARA.OpenSSL.x64.1.1.1\lib\libssl.lib;advapi32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>
      <GenerateDebugInformation>No</GenerateDebugInformation>
      <ShowProgress>LinkVerboseLib</ShowProgress>
    </Link>
    <ProjectReference>
      <LinkLibraryDependencies>false</LinkLibraryDependencies>
    </ProjectReference>
  </ItemDefinitionGroup>

compiles succesful on VS2022 as well.

**Comment by ThouSandThorChang** [comment]
When i use dll，yr_compiler_add_file() will error in yyrestart()，could u help me？

**Comment by plusvic** [comment]
Which error do you get?

**Comment by ApoIIy0n** [comment]
> Which error do you get?

@plusvic could you help me out with the correct settings for compiling the DLL? I thought I had it all worked out, everything was working fine, but the moment I thought I was close to be done with my project, I added multiple yara files  (just simple ones no errors in those) but the moment I have more than 1, I get system.accessviolationexception.. I got a working older dll from someone else then it all works like a charm, though I'd like to be more up2date as well.

**Comment by ApoIIy0n** [comment]
Issue is still there with the current build 4.5.1 anyone with a solution? re-opened this one since it seems to be not looked at..

**Comment by ApoIIy0n** [comment]
> Can you try following the steps listed in #1592 ? Step 7 should no longer be necessary.

Same results the moment I start scanning I get the following error:
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOf(Byte ByRef, Byte, Int32)
   at System.String.strlen(Byte*)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at ProjectV2.Wrappers.Yara.Rule..ctor(YR_RULE)
   at ProjectV2.Wrappers.Yara.YaraRules+<>c.<ExtractData>b__21_0(YR_RULE)
   at System.Linq.Enumerable+SelectEnumerableIterator`2[[ProjectV2.Wrappers.Yara.Interops.Types+YR_RULE, PName, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToList()
   at ProjectV2.Wrappers.Yara.YaraRules.ExtractData()
   at ProjectV2.Wrappers.Yara.YaraRules..ctor(IntPtr)
   at ProjectV2.Wrappers.Yara.Compiler.GetRules()
   at ProjectV2.Modules.Yara+<Start>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[ProjectV2.Modules.Yara+<Start>d__16, PName, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null]](<Start>d__16 ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[ProjectV2.Modules.Yara+<Start>d__16, PName, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null]](<Start>d__16 ByRef)
   at ProjectV2.Modules.Yara.Start()
   at PName.Program.Main(System.String[])

**Comment by le-jou** [comment]
So this is no longer about compiler errors when building the DLL as mentioned in your initial bug report?
It might be better to move this to a new issue then.

I have a similar use case, calling yara from managed code and for me it is working fine. Can you please provide a minimal project to reproduce this error?

**Comment by ApoIIy0n** [comment]
> So this is no longer about compiler errors when building the DLL as mentioned in your initial bug report? It might be better to move this to a new issue then.
> 
> I have a similar use case, calling yara from managed code and for me it is working fine. Can you please provide a minimal project to reproduce this error?

Thanks for pointing me out towards the right direction, i had quite a few alignment errors 🙈
