### ISSUE TITLE
Warnings when compiling yara

### ISSUE THREAD

**Issue by KevinW1998** [VirusTotal/yara#1869]
**Describe the bug**
Visual Studio 2022 showed me a couple of warnings that might be of interest and might want to get fixed:

```
yara\grammar.y(1110): warning C4701: potentially uninitialized local variable 'ref' used
yara\libyara\atoms.c(960): warning C4701: potentially uninitialized local variable 'best_atom' used
yara\re_grammar.c(1888): warning C4702: unreachable code
yara\libyara\exec.c(1170): warning C4701: potentially uninitialized local variable 'r1' used
yara\hex_grammar.c(1743): warning C4702: unreachable code
```

Warnings are based on libyara version 4.2.2

The first warning seems to be already fixed with #1702

**To Reproduce**
Compile yara

**Expected behavior**
No warnings if possible

**Screenshots**

**Please complete the following information:**
 - OS: Windows 10
 - YARA version: 4.2.2

**Additional context**

```
yara\libyara\atoms.c(960): warning C4701: potentially uninitialized local variable 'best_atom' used
```
https://github.com/VirusTotal/yara/blob/master/libyara/atoms.c#L960
```
yara\re_grammar.c(1888): warning C4702: unreachable code
```
https://github.com/VirusTotal/yara/blob/master/libyara/re_grammar.c#L1778
```
yara\libyara\exec.c(1170): warning C4701: potentially uninitialized local variable 'r1' used
```
https://github.com/VirusTotal/yara/blob/master/libyara/exec.c#L1417
```
yara\hex_grammar.c(1743): warning C4702: unreachable code
```
https://github.com/VirusTotal/yara/blob/master/libyara/hex_grammar.c#L1664

**Comment by plusvic** [comment]
Some of these warnings should be fixed in https://github.com/VirusTotal/yara/commit/d88f485da8571c675d1ececd336029fcc32906cd. Unfortunately not all of them can be fixed as they are in code automatically generated by Bison.
