### ISSUE TITLE
Detection 

### ISSUE THREAD

**Issue by AzmanMSIKing** [VirusTotal/yara#1878]
Virustotal has failed to detect 7zip,iso,rar files.

**Comment by plusvic** [comment]
Do you mean that it didn't detect files contained inside 7zip, iso and rar? Notice that YARA is not able to decompress or extract content from such file formats.

**Comment by AzmanMSIKing** [comment]
Oooo now i understood.i need to extract the files then i need to upload the
file then i will see the detection.

Excuse me another question,is that possible to check cracked software to
this website?

I succeeded to check the moded apk,apks but I don't know that this website
can check the cracked application of windows or Linux or mac files.

**Comment by plusvic** [comment]
I assume that you are referring to the www.virustotal.com website, if that's the case the answer is yes, you can upload any file you want. Notice however that this repository is for the YARA project, not for the www.virustotal.com site.
