### ISSUE TITLE
Iterating arrays

### ISSUE THREAD

**Issue by wxsBSD** [VirusTotal/yara#190]
In my authenticode branch I've got code that looks like this:

```
begin_struct("signature");
    declare_string("issuer");
    declare_string("subject");
    declare_integer("version");
    declare_string("algorithm");
    declare_string("serial");
    declare_string("notBefore");
    declare_string("notAfter");
end_struct("signature");
```

This works well for binaries that are signed only once (the vast majority) but it is possible to have more than one signature on a binary. To deal with this I'm moving my code to look like:

```
begin_struct_array("signature");
    declare_string("issuer");
    declare_string("subject");
    declare_integer("version");
    declare_string("algorithm");
    declare_string("serial");
    declare_string("notBefore");
    declare_string("notAfter");
end_struct_array("signature");
```

Where each element in the array is a structure representing the attributes of the certificate used in that signature. I'd like to be able to express this logic in a yara rule:

```
pe.signature.serial == "00:11:22:33" or
pe.signature.issuer contains "Microsoft"
```

I don't particularly care which of the signature array matches, as long as one of them matches. The best way I can see to do this right now is to express this via a function which walks the array, like this:

```
pe.signature.serial_equals("00:11:22:33") or
pe.signature.issuer_contains("Microsoft")
```

These functions would walk each item in the array and return if it matches. This is not how I would like to do it as it's cumbersome and doesn't fit in with the way other things like imphash() work. I suspect this will require some grammar changes to support it, but I think it would make writing and using modules easier.

Am I incorrect in reading things? Is there something I missed?

**Comment by plusvic** [comment]
Five years later array iterators are finally implemented in https://github.com/VirusTotal/yara/pull/1141
