### ISSUE TITLE
dotnet Module Bug

### ISSUE THREAD

**Issue by ddash-ct** [VirusTotal/yara#1906]
**Describe the bug**
When attempting to use the `dotnet` module, consistently observe errors being thrown like:
```
yara.Error: could not map file "XXXX" into memory
```

This has been observed with .NET compiled binaries such as the following:
* [f80f60eecf158405054740197f47d443032b96dc0c7081de49b37cb8bb5bf7d7](https://www.virustotal.com/gui/file/f80f60eecf158405054740197f47d443032b96dc0c7081de49b37cb8bb5bf7d7/details)
* [90fc1a784942396bec1faafaf6555e40cd24be1734334e7cb4a10f30d3617112](https://www.virustotal.com/gui/file/90fc1a784942396bec1faafaf6555e40cd24be1734334e7cb4a10f30d3617112/details)
* [236b372521a9a802336ec58b724b1893204a6b67054589ca7801fadda52db515](https://www.virustotal.com/gui/file/236b372521a9a802336ec58b724b1893204a6b67054589ca7801fadda52db515/details)  

This becomes particularly problematic when running a rule against a repository of files since it crashes scanning

**To Reproduce**
Have a rule which imports the `dotnet` module and runs against one of the above samples

**Expected behavior**
The `dotnet` module should support those samples, but it would be ideal if this didn't crash scanning when using the recursive option.

**Screenshots**
N.A

**Please complete the following information:**
 - OS: Windows 11
 - YARA version: 4.3.0

**Additional context**
N/A

**Comment by wxsBSD** [comment]
This was recently fixed. My hope is that there will be a 4.3.1 released soon as using the module on windows results in unreliable scanning behavior.

**Comment by plusvic** [comment]
Fixed in #1902
