### ISSUE TITLE
Scan hanging when scanning Pulse Audio Process

### ISSUE THREAD

**Issue by humpalum** [VirusTotal/yara#1929]
**Describe the bug**
When scanning the "pulse audio daemon"-process my yara scan hangs even when using --timeout.

**To Reproduce**
1. Create empty Yara Rule 
2. Run Yara on pulseaudio pid

**Expected behavior**
Process should end. At the latest when timeout is reached

**Screenshots**
We have done some debugging and could figure out the following infos: 
![image](https://github.com/VirusTotal/yara/assets/11175099/b56ba8ee-599e-4dbd-8e30-39b1395180bb)
![image](https://github.com/VirusTotal/yara/assets/11175099/e1ee29a6-dd90-4a88-a6c5-f656ffd06795)
![image](https://github.com/VirusTotal/yara/assets/11175099/d797e0ce-c333-4a39-9a14-4b1ab1e33a6d)
![image](https://github.com/VirusTotal/yara/assets/11175099/0bc8d430-3de1-480b-8304-a99141223874)
![image](https://github.com/VirusTotal/yara/assets/11175099/664cbbb3-f51c-4a01-ab6c-f51ff238c4c4)

**Please complete the following information:**
 - OS: ArchLinux - 6.3.5-arch1-1
 - YARA version: 4.3.1and latest master

**Comment by secDre4mer** [comment]
Also can happen with pipewire. pipewire memory maps files in /dev/snd (with 00:05 device ID), just like pulseaudio.

**Comment by plusvic** [comment]
Now that #1999 has been merged this issue should be fixed.
