### ISSUE TITLE
Is there any way to avoid multiple duplicate lines regex match?

### ISSUE THREAD

**Issue by gaohang** [VirusTotal/yara#1932]
just like https://github.com/VirusTotal/yara/issues/504

when I use regex rule in yara, it match the same line multiple times. How to avoid it or is there any usage for this condition?

**Comment by plusvic** [comment]
Can you provide some example of a rule, input file and results you are expecting?

**Comment by gaohang** [comment]
rule $re = /ab.{,4}/ 
match result:  abc ab. ab.c ab.cd
desired result: the longest match, like ab.cd
