### ISSUE TITLE
About release 4.4.0

### ISSUE THREAD

**Issue by chenrui333** [VirusTotal/yara#1964]
👋 it looks like 4.4.0 release did not get completed (ie the release is not marked as latest release), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/142900

**Comment by plusvic** [comment]
Yes, it intentional, I just release it as `4.4.0-rc1` now.

**Comment by chenrui333** [comment]
the tag seems mismatched with the release title 😬 
![image](https://github.com/VirusTotal/yara/assets/1580956/ebf0e9c9-0382-4bc7-8fdd-07dd22e2594a)

**Comment by chenrui333** [comment]
any way, that is helpful. thanks!
