### ISSUE TITLE
calloc behavior on AIX platform

### ISSUE THREAD

**Issue by asalih** [VirusTotal/yara#1980]
According to the [documentation](https://www.ibm.com/docs/en/aix/7.2?topic=m-malloc-free-realloc-calloc-mallopt-mallinfo-mallinfo-heap-alloca-valloc-posix-memalign-subroutine#malloc__basetrf1-gen2267__title__1) AIX returns NULL when requested size is 0 but also returns NULL if you provide 0 to count parameter.  In this example rule below, there is no strings definition in it, rule successfully compiles with given variable but afterwards when I try to create a scanner with the compiled rules, `yr_scanner_create ` function returns `insufficient memory` error. The reason is; `new_scanner->matches` is NULL because of the calloc behavior. To avoid this, `#define _LINUX_SOURCE_COMPAT` must be added to [mem.c](https://github.com/VirusTotal/yara/blob/d3998267e85db8e04868e104815edfd7563b9f71/libyara/mem.c#L110).

```
rule find_by_name 
{
    meta:
        description = "Find files by name."

    condition:
        file_name == "Task.dat"
}
```

**Comment by hillu** [comment]
Interesting. The manpage for malloc and friends on my Debian system list this as nonportable behavior. IMHO, the correct response is to rewrite those allocations rather than telling the compiler to use glibc-compatible variants of those library functions.

**Comment by asalih** [comment]
Thank you for the fix, @hillu. The only concern with these changes is that, from now on, in addition to the NULL check on a calloc call, there must also be relevant count control, similar to your additional checks. However, due to the common behavior of calloc on Linux, it might be overlooked and become implicit knowledge, potentially leading to oversights. Adding the `_LINUX_SOURCE_COMPAT` macro with a conditional compilation directive can prevent future problems, what do you think?

**Comment by plusvic** [comment]
I have similar concerns. It's very easy to re-introduce issues like this in the future.
