### ISSUE TITLE
How to get condition string from rule via C API?

### ISSUE THREAD

**Issue by mavam** [VirusTotal/yara#1998]
Say I'm processing matches in this callback:

```cpp
int callback(YR_SCAN_CONTEXT* context, int message, void* message_data, void* user_data);
```

I get a `YR_RULE*` by casting `message_data`, and I've looked for a "condition" member in the the underlying `YR_RULE` struct, but I can't find anything here.

As I am reporting matches, it would be quite valuable context to also report the textual condition.

**Comment by plusvic** [comment]
You can't, compiled rules don't retain the original source code, so the condition's text is lost after compilation.
