### ISSUE TITLE
hash.h excepted an identifier

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [VirusTotal/yara#2028]
**Describe the bug**
I got error at hash.h which says excepted identifier
**To Reproduce**
Just create libyara64.lib from visual studio 2019 then add to project example like this #pragma comment(lib, "yara\\libyara64.lib")
then add yara.h #include "yara\\yara.h"
**Expected behavior**
I excepted yara.h should be work without errors

**Screenshots**
![image](https://github.com/VirusTotal/yara/assets/142328963/01b2842e-65fe-4b55-beed-2bd3b1197457)

**Please complete the following information:**
 - OS: Windows 10
 - YARA version: Latest commit 4.3.2

**Additional context**
I tried to use yara.h in my C++ program but then I got that error.
Here is the hash.h `code `/*
Copyright (c) 2013. The YARA Authors. All Rights Reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef YR_HASH_H
#define YR_HASH_H

#include "stddef.h"
#include "integers.h"
#include "utils.h"

typedef struct _YR_HASH_TABLE_ENTRY
{
  void* key;
  size_t key_length;
  char* ns;
  void* value;

  struct _YR_HASH_TABLE_ENTRY* next;

} YR_HASH_TABLE_ENTRY;

typedef struct _YR_HASH_TABLE
{
  int size;

  YR_HASH_TABLE_ENTRY* buckets[1];

} YR_HASH_TABLE;

typedef int (*YR_HASH_TABLE_FREE_VALUE_FUNC)(void* value);
typedef int (*YR_HASH_TABLE_ITERATE_FUNC)(
      void* key, size_t key_length, void* value, void* data);

uint32_t yr_hash(uint32_t seed, const void* buffer, size_t len);

YR_API int yr_hash_table_create(int size, YR_HASH_TABLE** table);

YR_API void yr_hash_table_clean(
    YR_HASH_TABLE* table,
    YR_HASH_TABLE_FREE_VALUE_FUNC free_value);

YR_API void yr_hash_table_destroy(
    YR_HASH_TABLE* table,
    YR_HASH_TABLE_FREE_VALUE_FUNC free_value);

YR_API int yr_hash_table_iterate(
    YR_HASH_TABLE* table,
    const char* ns,
    YR_HASH_TABLE_ITERATE_FUNC iterate_func,
    void* data);

YR_API void* yr_hash_table_lookup(
    YR_HASH_TABLE* table,
    const char* key,
    const char* ns);

YR_API void* yr_hash_table_remove(
    YR_HASH_TABLE* table,
    const char* key,
    const char* ns);

YR_API int yr_hash_table_add(
    YR_HASH_TABLE* table,
    const char* key,
    const char* ns,
    void* value);

YR_API int yr_hash_table_add_uint32(
    YR_HASH_TABLE* table,
    const char* key,
    const char* ns,
    uint32_t value);

YR_API uint32_t yr_hash_table_lookup_uint32(
    YR_HASH_TABLE* table,
    const char* key,
    const char* ns);

YR_API void* yr_hash_table_lookup_raw_key(
    YR_HASH_TABLE* table,
    const void* key,
    size_t key_length,
    const char* ns);

YR_API void* yr_hash_table_remove_raw_key(
    YR_HASH_TABLE* table,
    const void* key,
    size_t key_length,
    const char* ns);

YR_API int yr_hash_table_add_raw_key(
    YR_HASH_TABLE* table,
    const void* key,
    size_t key_length,
    const char* ns,
    void* value);

YR_API int yr_hash_table_add_uint32_raw_key(
    YR_HASH_TABLE* table,
    const void* key,
    size_t key_length,
    const char* ns,
    uint32_t value);

YR_API uint32_t yr_hash_table_lookup_uint32_raw_key(
    YR_HASH_TABLE* table,
    const void* key,
    size_t key_length,
    const char* ns);

#endif
`Line 53 :   YR_HASH_TABLE_ENTRY* buckets[1];
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0040	expected an identifier	HydraDragonAV	C:\Users\victim\Documents\HydraDragonAV\HydraDragonAV\yara\yara\hash.h	53		
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2059	syntax error: 'constant'	HydraDragonAV	C:\Users\victim\Documents\HydraDragonAV\HydraDragonAV\yara\yara\hash.h	53		
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2143	syntax error: missing ';' before '}'	HydraDragonAV	C:\Users\victim\Documents\HydraDragonAV\HydraDragonAV\yara\yara\hash.h	55		
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2238	unexpected token(s) preceding ';'	HydraDragonAV	C:\Users\victim\Documents\HydraDragonAV\HydraDragonAV\yara\yara\hash.h	55

**Comment by HydraDragonAntivirus** [comment]
Solution 1: Remove this line then it's fixed.

**Comment by vhavel** [comment]
Is it possible the source file you're compiling defines `buckets` preprocessor macro as an integer literal? Try `#undef buckets` before including yara.h

**Comment by HydraDragonAntivirus** [comment]
> Is it possible the source file you're compiling defines `buckets` preprocessor macro as an integer literal? Try `#undef buckets` before including yara.h

Yes you are right. The problem is solved.
