### ISSUE TITLE
Release v4.4.0?

### ISSUE THREAD

**Issue by vt-alt** [VirusTotal/yara#2042]
Aren't v4.4.0 was already released at 2023-09-15?

**Comment by plusvic** [comment]
It looks like I mistakenly added a tag `v4.4.0` back then, but the intention was to tag it as `v4.4.0-rc1`. Sorry for the confusion.

**Comment by vt-alt** [comment]
Well, downstream distributions was already released that rc1 as 4.4.0, see the log https://repology.org/project/yara/history

**Comment by plusvic** [comment]
I left the `4.4.0` as it was, and the most recent release is now `4.5.0`.

**Comment by vt-alt** [comment]
Thanks!
