### ISSUE TITLE
[Yara 4.5.0][Build error] --- pread64 not found on Alpine Linux

### ISSUE THREAD

**Issue by nivscadafence** [VirusTotal/yara#2050]
Yara build on Alpine Linux fails:

`libyara/proc/linux.c: In function 'yr_process_fetch_memory_block_data':
libyara/proc/linux.c:252:9: warning: implicit declaration of function 'pread64'; did you mean 'pread'? [-Wimplicit-function-declaration]
  252 |     if (pread64(
      |         ^~~~~~~
      |         pread
  CCLD     libyara.la
copying selected object files to avoid basename conflicts...
  CCLD     yara
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ./.libs/libyara.so: undefined reference to `pread64'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1735: yara] Error 1
make[1]: Leaving directory '/tmp/sources/yara-4.5.0'
make: *** [Makefile:1190: all] Error 2
The command '/bin/sh -c cd /tmp/sources &&     tar -zxf yara-${YARA_VERSION}.tar.gz && cd yara-${YARA_VERSION} &&     ./bootstrap.sh && ./configure --with-crypto --enable-magic && make && make install && make check' returned a non-zero code: 2`

**Comment by vthib** [comment]
On which version of Alpine do you have this issue?

This is very likely due to musl 1.2.4, a fix is in progress here: https://github.com/VirusTotal/yara/pull/2048

**Comment by nivscadafence** [comment]
docker image:

python:3.9-alpine

**Comment by plusvic** [comment]
Should be fixed in 833a580430abe0fbc9bc17a21fb95bf36dacf367

**Comment by fwosar** [comment]
Given that the build is broken on Linux right now, any chance for a point release that includes the fix that could be propagated to the various dependency managers, @plusvic?

**Comment by plusvic** [comment]
Yes, I think it's time for a new release.
