### ISSUE TITLE
I have a question about the order in which internal rules are parsed

### ISSUE THREAD

**Issue by helloobaby** [VirusTotal/yara#2055]
When I compile Yara rules for a folder, and then use this compiled single rule to scan a specified file, what is the parsing order of some internal rules?

To put it more bluntly, I want certain rules to be parsed first. Can Yara do it?

**Comment by helloobaby** [comment]
I tested it and found that the parsing order of compiled rules should be consistent with the order of yr_compiler_add_file, is that right?

**Comment by plusvic** [comment]
Yes, rules will be parsed in the order they are added with `yr_compiler_add_file`, and they will be executed in that order too.
