### ISSUE TITLE
Windows Defender detects YARA as Malware!!

### ISSUE THREAD

**Issue by screeck** [VirusTotal/yara#2060]
Im trying to install yara with vcpkg using command:
.\vcpkg.exe isntall yara
Installation got interrupted by windows defender, that identified yara as a backdoor malware.
I've also checked binaries and both of then got flagged as malware in VirusTotal.
Is is false positive?
Anyone encoutered this?
![fsrgdsr](https://github.com/VirusTotal/yara/assets/58401384/d3178120-bd46-4f2b-b42f-1d83aa879c54)
![ssfefse](https://github.com/VirusTotal/yara/assets/58401384/4fab6c80-e3d5-4aa8-afdf-3a5926036425)

**Comment by plusvic** [comment]
That's probably a false positive. However, I can't make any guarantee about any binaries published by `vcpkg`. I can make guarantees about the files published as part of [release](https://github.com/VirusTotal/yara/releases) in this repository.
