### ISSUE TITLE
ERROR_TOO_MANY_SCAN_THREADS

### ISSUE THREAD

**Issue by nevoeitan** [VirusTotal/yara#2068]
Hey, in the yara docs it is stated about error ERROR_TOO_MANY_SCAN_THREADS - "Too many threads trying to use the same YR_RULES object simultaneously. The limit is defined by YR_MAX_THREADS in ./include/yara/limits.h".
But upon searching the error references in the code it doesn't actually seems to be used.
Will appreciate a response whether or not this error is actually relevant. Thanks in advance.

**Comment by plusvic** [comment]
I've removed all references to this error from the documentation. It was relevant in the past, but is not used anymore.
