### ISSUE TITLE
Build fails for Ubuntu 22.04

### ISSUE THREAD

**Issue by DavidConnack** [VirusTotal/yara#2082]
**Describe the bug**
Building Yara from source in AWS Codebuild using the [Ubuntu](https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard/7.0) runtime fails with the following error:

```
no acceptable sed could be found in $PATH
make[1]: *** [Makefile:1909: libyara/modules/tests/la-tests.lo] Error 1
```

**To Reproduce**

```
apt-get install -y automake libtool make gcc pkg-config
curl -OL https://github.com/VirusTotal/yara/archive/refs/tags/v4.5.0.tar.gz
tar -zxf v4.5.0.tar.gz
cd yara-4.5.0
./bootstrap.sh
./configure
make
make install
make check
```

**Expected behavior**
Yara should build with out any errors.

**Screenshots**

**Please complete the following information:**
 - OS: Ubuntu 22.04 specifically  [Codebuild](https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard/7.0)
 - YARA version: 4.5.0

**Additional context**
I have confirmed that sed does exist:

```
which sed
/usr/bin/sed
```

**Comment by DavidConnack** [comment]
`/usr/bin:/usr/local/bin/sbt/bin:/root/.goenv/shims:/root/.goenv/bin:/go/bin:/root/.phpenv/shims:/root/.phpenv/bin:/root/.pyenv/shims:/root/.pyenv/bin:/root/.rbenv/shims:/usr/local/rbenv/bin:/usr/local/rbenv/shims:/root/.dotnet/:/root/.dotnet/tools/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tools:/codebuild/user/bin`

What is strange is that I see this in the logs:
`checking for a sed that does not truncate output... /usr/bin/sed`

**Comment by DavidConnack** [comment]
It was a pebcak error 😅.
I was running my script using `source` which for some reason caused it to fail.
Ive refactored my script and removed the `source` and it now builds correctly.

Thanks for your help!

**Comment by plusvic** [comment]
That's interesting. Good to know.
