### ISSUE TITLE
pe.signatures[n].issuer not working at the lasts version

### ISSUE THREAD

**Issue by Vendettail** [VirusTotal/yara#2094]
for version 4.0.2 the following code working well:
`
		for all n in (0..pe.number_of_signatures):
		(	
			not pe.signatures[n].issuer contains "Microsoft"
		)
`
but for version 4.5.1 it's not.
some for the 'subject' field, I do not know when it starts to fail.

**Comment by wxsBSD** [comment]
Do you have a hash that triggers this?

**Comment by Vendettail** [comment]
e81f3632a177cc70e45b405c4383e4f11e4e1661158127dfb29615db769b68dd

**Comment by Vendettail** [comment]
> Do you have a hash that triggers this?

e81f3632a177cc70e45b405c4383e4f11e4e1661158127dfb29615db769b68dd

**Comment by wxsBSD** [comment]
Ah, I see what is going on here: `pe.signatures` array indexing starts at zero. In your example, the first time through the loop it will evaluate to true (it does not contain "Microsoft") but the second time through (when `n` is 1) `not pe.signatures[n].issuer contains "Microsoft"` is undefined.

What you want to do is `for all n in (0..pe.number_of_signatures - 1): (not pe.signatures[n].issuer contains "Microsoft")`

I'm guessing b7da5d2835cc4cf8a15027da30265addab1a4be5 has something to do with this change?

**Comment by Vendettail** [comment]
ha, so the "bug" belongs to the oldest versions, not the new ones, at the older version the contains operation returns true (?) for undefine so it "works", do I get it right?

**Comment by wxsBSD** [comment]
I think so. Not entirely sure to be honest.

**Comment by Vendettail** [comment]
@wxsBSD tnx!
