### ISSUE TITLE
Link of Windows YARA install is not working.

### ISSUE THREAD

**Issue by MuMuuuu** [VirusTotal/yara#2095]
**Describe the bug**
https://yara.readthedocs.io/en/v3.5.0/gettingstarted.html
[Download Windows binaries](https://b161268c3bf5a87bc67309e7c870820f5f39f672.googledrive.com/host/0BznOMqZ9f3VUek8yN3VvSGdhRFU/) Link redirects to wrong google drive.

**Expected behavior**
Links to [release page](https://github.com/VirusTotal/yara/releases/tag/v4.5.1)

**Comment by plusvic** [comment]
The old link is only present in older versions of the documentation, starting with version 4.0.0 the link points to GitHub releases. Unfortunately I can't update the old versions of the documentation.
