### ISSUE TITLE
Where to get GPG key to verify release commit?

### ISSUE THREAD

**Issue by vt-alt** [VirusTotal/yara#2105]
**Describe the bug**
Location of public key to verify the release commit is unknown.

**To Reproduce**
```
$ git verify-commit v4.5.2
gpg: Signature made Tue Sep 10 11:52:59 2024 MSK
gpg:                using RSA key A65644273CF477F05B0A6F1B8DCC0C6CA10F526A
gpg: Can't check signature: No public key
```

**Please complete the following information:**
 - OS: ALT Linux
 - YARA v4.5.2
 - 
**Additional context**
I tried these locations
- https://github.com/virustotal.gpg no key data
- https://github.com/plusvic.gpg key but it does not verify
- https://github.com/web-flow.gpg does not verify either
- hkps://keyserver.ubuntu.com does not have key `A65644273CF477F05B0A6F1B8DCC0C6CA10F526A`.

**Comment by plusvic** [comment]
I've uploaded my public key to https://keyserver.ubuntu.com/, please try again.

**Comment by vt-alt** [comment]
Thanks!
