### ISSUE TITLE
static secure coding

### ISSUE THREAD

**Issue by jhjo-jhjo** [VirusTotal/yara#2118]
yara is wonderful library.
I am using version 4.2.3, but yara library is not complied with secure coding.
what version  is satisfied with secure coding?

**Comment by jhjo-jhjo** [comment]
as I know, secure coding can be tested in static and runtime analysis.
for example, codesonar or Coverity Static Analysis !

**Comment by plusvic** [comment]
I still don't know what do mean exactly. I use Coverity for finding issues (https://github.com/VirusTotal/yara/blob/master/.github/workflows/coverity.yml) and also use oss-fuzz.
