### ISSUE TITLE
Yara doesn't compile on RHEL6

### ISSUE THREAD

**Issue by apolkosnik-old** [VirusTotal/yara#212]
I was trying to compile v3.2.0 on RHEL6, then the latest from git, and I ran into this:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -O3 -Wall -std=gnu99 -I./include -pthread -MT modules/hash.lo -MD -MP -MF modules/.deps/hash.Tpo -c modules/hash.c -o modules/hash.o >/dev/null 2>&1
/bin/sh ../ylwrap grammar.y y.tab.c grammar.c y.tab.h grammar.h y.output grammar.output -- byacc  -d
byacc: e - line 95 of "/home/test/yara/libyara/grammar.y", syntax error
%debug
^
make[2]: **\* [grammar.c] Error 1
make[2]: Leaving directory `/home/test/yara/libyara'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/test/yara'
make: **\* [all] Error 2

**Comment by 0xAli** [comment]
I have the exact same issue, updated byacc to 20141128 - still have same error.

I tried removing that %debug line and/or the lines after/before it and it didn't matter still got the same error.

**Comment by frbapolkosnik** [comment]
I've got another case of this, but this time I looked at the output from configure.
Installing flex and bison fixed the issue.
