### ISSUE TITLE
PE module: `is_pe` depends on PE Machine type being known, but there are additional types

### ISSUE THREAD

**Issue by wesinator** [VirusTotal/yara#2125]
The `is_pe` logic depends on the value at the machine type location in the PE header being in the list of machine types defined in the PE module. So if there is a PE with a machine type that isn't yet in YARA, YARA will incorrectly fail to detect the file as a PE.
This was mentioned in #231, and there are still other machine types that are not yet listed in the PE machine types enum (working on a PR).
The Microsoft documentation seems to be incomplete or out-of-date, and has at least two places in the docs with slightly different lists. Whether this field is technically required and exhaustive by the PE spec, there are new machine types that have been added or discovered, e.g. [CHPEv2 (0x3a64)](https://wbenny.github.io/2018/11/04/wow64-internals.html) 

I tested this by modifying a PE machine type field to the CHPEv2 machine which is not currently in the enum of machine types in yara.
The PE module fails to detect the file as a PE.

**Expected**: `pe.is_pe` evaluates to true on characteristics other than PE machine type; if the value found at the machine type location of the PE is not in the enum, but other conditions match a PE, then is_pe should evaluate to true.

[NO_TRAIN]::

**Comment by plusvic** [comment]
I've done the same test with different results. I took a PE file and modified the machine type field and the module `pe.is_pe` field keeps being true. By reviewing the code I don't see that this field depends on the machine type.

**Comment by wesinator** [comment]
Ah, I apologize - the issue exists in v4.1.3 but not the latest version

Best,

[NO_TRAIN]::
