### ISSUE TITLE
Matching file name

### ISSUE THREAD

**Issue by vient** [VirusTotal/yara#269]
I didn't find any information about rules based on file names, so I assume they don't exist for now. Please add checking file names just like in usual rules, for example, I usually save YARA output to log.txt and I don't want to check this file by YARA started in parent folder recursively.

**Comment by marnao** [comment]
Why not use an external variable?

**Comment by vient** [comment]
I don't understand how external variable can help here, please explain if you know.

**Comment by marnao** [comment]
This isn't a perfect solution because you can't use yara's native recursive feature for multithreading, but you could use parallel instead of xargs here to make this faster.

$ cat test.yara
rule testrule
{
    condition:
        not ext_filename matches /log.txt$/i
}

$ find testfolder -type f
testfolder/testfile2
testfolder/testfile1
testfolder/log.txt

$ find testfolder -type f | xargs -I@ yara -d "ext_filename=@" test.yara @
testrule testfolder/testfile2
testrule testfolder/testfile1

**Comment by marnao** [comment]
To your point, I don't think having filename as a native variable is a bad idea either. There might be a good reason why this hasn't been done already. I do believe this is a suitable workaround though.

**Comment by vient** [comment]
Oh, it is a solution, of course, but I'm working on Windows from cmd. Maybe it's time to try cygwin ot mingw console. Thanks!

**Comment by wxsBSD** [comment]
This has been brought up before and there's answers and options presented in #202.

**Comment by gwillem** [comment]
@marnao's solution is not very performant when scanning terabytes of customer files, due to yara startup and compile overhead per file.

**Comment by gwillem** [comment]
More profit when filename is available as condition: you can flag files with unexpected content. For example, `<?php` in an image file.

**Comment by bmagistro** [comment]
There is what I would call related work going on in #350.  I tend agree with the points made in #202 in that a filename may not always apply, such as when scanning blocks of memory.

I would also caution you about relying on the filename to identify what kind of file it is.  Microsoft seems to leverage the extension a lot.  While it may be useful as a user or if doing malware analysis (ex. this one always drops file named Y), I would not depend on it to identify the type of file.  Coming from a primarily *nix environment, file extensions are more of a "convenience" than a required item for the system to understand what type of file it is.  If trying to do what you suggest of looking for `<?php` in an image file, take a look at the [Magic Module](http://yara.readthedocs.io/en/v3.5.0/modules/magic.html) which you can call with `mime_type` and say  something like `if == /^image\// && any of $unwanted_vars`.

**Comment by gwillem** [comment]
Thanks for the Magick suggestion! Caveat: not all image-disguised PHP malware has an actual image byte header (just plain PHP).

**Comment by moradcom4ever** [comment]
just add  (( filename = "test.exe" )) to conditions
