### ISSUE TITLE
Ability to express string result in a list of strings

### ISSUE THREAD

**Issue by wxsBSD** [VirusTotal/yara#300]
I've been racking my brain for a bit trying to come up with a way to express this, and I'm slowly coming to the conclusion that it can't be done. Figure I might as well ask for help and see if it is a good idea here.

I want to be able to express that the result of a function be somewhere in a list of values. For example, if I know a binary has 10 resources and that the contents of those resources are static I should be able to hash them and check the result. This can be done with:

```
hash.md5(pe.resources[0].offset, pe.resources[0].length) == "foo" and
hash.md5(pe.resources[1].offset, pe.resources[1].length) == "bar" and
...
```

I can simply put more or less lines in depending upon the level of certainty I want. This works but requires that the resources be in a consistent order every time. Ideally I'd like to express this as:

```
for 5 i in (0..pe.number_of_resources - 1):
  (hash.md5(pe.resources[i].offset, pe.resources[i].length) in ("foo", "bar", "baz", "pants", "blah"))
```

**Comment by plusvic** [comment]
What about this?

```
for 5 i in (0..pe.number_of_resources - 1):
  (
    hash.md5(pe.resources[i].offset, pe.resources[i].length) == "foo" or
    hash.md5(pe.resources[i].offset, pe.resources[i].length) == "bar" or 
    hash.md5(pe.resources[i].offset, pe.resources[i].length) == "baz" or
    hash.md5(pe.resources[i].offset, pe.resources[i].length) == "pants" ...
  ))
```

But it would be great if it could be expressed the way you propose, it's shorter and clearer. I'm going to take this into account as part of future improvements I'm thinking about.

**Comment by wxsBSD** [comment]
That would work, and would no longer require the resources to be in the same order. The downside is that it would have to calculate the hash multiple times until a match was found for that iteration of the loop. Ideally it should calculate the hash once and then iterate through all possible results until a match is found.

Thanks for taking this into consideration!

**Comment by plusvic** [comment]
Closing, as the downside mentioned by wxsBSD is already fixed too. The `hash` module caches the latest hash calculated from a given offset,length pair.
