### ISSUE TITLE
Fail to compile on Solaris 11 missing ptrace.h

### ISSUE THREAD

**Issue by awatkins1966** [VirusTotal/yara#318]
Hi,

Tried compiling yara 3.3 on Solaris 11 and get missing sys/ptrace.h since this is no longer available in Solaris11. 

make[2]: Entering directory `/tmp/yara-3.3.0/libyara'
depbase=`echo proc.lo | sed 's|[^/]*$|.deps/&|;s|.lo$||'`;\
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -O3 -Wall -Wno-deprecated-declarations -std=gnu99 -I./include -D_REENTRANT -pthreads -MT proc.lo -MD -MP -MF $depbase.Tpo -c -o proc.lo proc.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -O3 -Wall -Wno-deprecated-declarations -std=gnu99 -I./include -D_REENTRANT -pthreads -MT proc.lo -MD -MP -MF .deps/proc.Tpo -c proc.c  -fPIC -DPIC -o .libs/proc.o
In file included from /usr/include/fcntl.h:11:0,
                 from proc.c:145:
/usr/include/sys/feature_tests.h:354:2: error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications  and pre-2001 POSIX applications"
proc.c:148:24: fatal error: sys/ptrace.h: No such file or directory
compilation terminated.

Thanks,

Andrew

**Comment by plusvic** [comment]
Closing this issue as it's very old and support for Solaris is not priority right now. If someone volunteers to make YARA work on Solaris I would accept patches.
