### ISSUE TITLE
Macro redefinition when compiling with VS2015

### ISSUE THREAD

**Issue by JusticeRage** [VirusTotal/yara#339]
The `snprintf` macro seems to have been introduced in Visual Studio 2015, which breaks the build on windows. I have made changes at https://github.com/JusticeRage/yara/commit/b7048bbbeab384f335b78412ae484bb9fa70718e that fix it. For some reason, my repo isn't recognized as a fork of yours so I haven't managed to create a pull request, so sorry about that.

EDIT: I missed one in the latest version: at [`strutils.h:27`](https://github.com/plusvic/yara/blob/master/libyara/include/yara/strutils.h#L26), the following could be used:

```
#ifdef _WIN32
# if !defined(snprintf) && _MSC_VER < 1900
#   define snprintf _snprintf
# endif
# define strcasecmp _stricmp
# define strncasecmp _strnicmp
#endif
```

**Comment by plusvic** [comment]
Already fixed.
