### ISSUE TITLE
[feature] multiple yara rule files as input

### ISSUE THREAD

**Issue by shibumi** [VirusTotal/yara#344]
Hello,
I  am not sure if this feature is already done. But i would suggest a parameter for the use of more than one yara rule..

I have for example a directory with different yara rules in it and i want to use all rules to scan another directory **without** merging all yara rules together...

some like this:

`yara -rg /home/user/yararules/linux/* /home/user/malware/`

**Comment by plusvic** [comment]
I'm going to consider this feature. In the meanwhile you can have master file with "include" directives to all the other file you have in the directory. You have to create this file, but at least you don't have to merge all your rules together.

**Comment by shibumi** [comment]
awesome thx!

**Comment by xdanx** [comment]
+1

**Comment by mylamour** [comment]
You can read dir and use `yr_compiler_add_file`  to add all rules, finally, you can load the whole dir rules. Also, you can use `yara-python` to load different  rules.  and this script maybe useful for you. https://github.com/Neo23x0/Loki/blob/master/loki.py

**Comment by DigiAngel** [comment]
+1

**Comment by plusvic** [comment]
Since YARA 3.7.0 you can pass multiple files in the command-line. Wildcards are not supported though.

**Comment by erikdemarco** [comment]
> I'm going to consider this feature. In the meanwhile you can have master file with "include" directives to all the other file you have in the directory. You have to create this file, but at least you don't have to merge all your rules together.

Any update?
