### ISSUE TITLE
-D option not thread safe and dump JSON?

### ISSUE THREAD

**Issue by wxsBSD** [VirusTotal/yara#354]
The -D option causes multiple prints to the screen to interleave when running multithreaded. This isn't a huge deal because it isn't a commonly done operation but I'm creating this issue so it isn't lost. I have plans to tackle this after my next pull request.

One thing that would be nice is if the -D option dumped in JSON format. It would make it much easier to ingest and parse with other tools. Any thoughts on that?

**Comment by moofusecurity** [comment]
+1 for JSON

**Comment by 79617261** [comment]
+1 to JSON too

**Comment by wxsBSD** [comment]
For those playing along at home an easy work around was committed to yara-python which exposes module callback data as a dictionary which you can then serialize to json if you want.
