### ISSUE TITLE
Please mention autoconf and libtool as dependencies in documentation 

### ISSUE THREAD

**Issue by intelemetry** [VirusTotal/yara#363]
https://yara.readthedocs.org/en/v3.4.0/gettingstarted.html#compiling-and-installing-yara
The configure script is actually launched by ./bootstrap.sh which should be mentioned in addition to the need for autoconf and libtool.

**Comment by intelemetry** [comment]
Please mention: libjansson-dev, libmagic-dev for cuckoo and magic configure.sh flags 
Please mention: libssl-dev for openssl (--with-crypto) flag 

This is for debian/ubuntu and derivative systems.

**Comment by intelemetry** [comment]
Please mention flex as dependency.

**Comment by Themercee** [comment]
Thanks @intelemetry for talking about these dependencies, I got problem installing it because they were missing

**Comment by plusvic** [comment]
Fixed in 18500039fe2246ddfb62a0533b37e2ad12cad9df
