### ISSUE TITLE
Invalid Field Name Error Tied to Missing Package

### ISSUE THREAD

**Issue by jxb5151** [VirusTotal/yara#378]
Hello,

When creating a rule where I used the 'pe' module to review the number of signatures in a file, I had Yara throw the following message 'invalid field name "number_of_signatures"'. My rule was working on other machines, but not for the one I was developing on which I found odd. After a bit of troubleshooting I found that I needed to install the package openssl-devel on my CentOS box (libssl-dev for Ubuntu) and recompile and install Yara. Once I did this, my rule worked as desired. 

I found it strange that I was able to successfully compile and install Yara without this package, which seems necessary in order to use some of the features of the pe module. 

I'd like to suggest looking into a way to make it more obvious to a user they might be missing this  requirement when installing Yara. 

Thanks,
Jason

**Comment by wxsBSD** [comment]
It seems reasonable to dump out what will and won't be built after configure finishes detecting things. In your particular case it isn't finding OpenSSL properly.

**Comment by plusvic** [comment]
I agree with that too

**Comment by jxb5151** [comment]
Rock on :)

**Comment by Neo23x0** [comment]
Interesting - I get this error using the prebuilt 3.5.0 package for Windows. (Python 2.7)

**Comment by plusvic** [comment]
./configure now warns you when OpenSSL wasn't found in your system.
