### ISSUE TITLE
Add ability to process overlays in PE Module

### ISSUE THREAD

**Issue by blaquee** [VirusTotal/yara#432]
It would be neat to have the ability to write rules that can identify appended data in a pe file (overlays)
something like:

```
rule overlay
{
   condition:
     pe.has_overlay
}

```

or access to overlay information such as offset and length (pe.overlay.length and pe.overlay.offset)

**Comment by merces** [comment]
Hi @blaquee,

I recently needed that too. Here is a rule that can tell you whether overlay is present or not:

	import "pe"

	private rule has_overlay {
	   condition:
	      uint8(pe.sections[pe.number_of_sections - 1].raw_data_offset + pe.sections[pe.number_of_sections - 1].raw_data_size)
	}

	rule my_rule {
	   strings:
	      $mz = "MZ" ascii
	   condition:
	      $mz at 0 and
	      has_overlay
	}

But I also agree will be nice to have it available in Yara, so I made a patch for this in my fork at https://github.com/merces/yara/commit/566786820036f78d21703ac63e5a59eaec499268. Not sure if @plusvic would accept a PR for this though.

Cheers,
Fernando

**Comment by wxsBSD** [comment]
I don't think you can always rely upon section ordering.

**Comment by merces** [comment]
Hi @wxsBSD

Can you please clarify? I don't really care about section ordering, I just go to the last section header to get its offset and size. Are you suggesting the last section header may not represent the last section on physical file?

Thanks,
Fernando

**Comment by wxsBSD** [comment]
Yes, that is what I'm suggesting.

**Comment by mrexodia** [comment]
I think the only way is to keep track of the highest raw offset and determine the location of the overlay that way.

Here is some code that works for it. https://github.com/x64dbg/GleeBug/blob/master/GleeBug/Static.Pe.cpp#L225

**Comment by wxsBSD** [comment]
I think that is the right way too. I've got some prototype code which does it, but I need to clean it up a bit. Hopefully sometime in the next couple of weeks.

**Comment by merces** [comment]
Thank you for the ideas. I've updated the patch. Have a look at  https://github.com/merces/yara/commit/39447516d82454f46988fac7313aebe8ce356f88 please. ;)
