### ISSUE TITLE
Error scanning... Could not open file 

### ISSUE THREAD

**Issue by shlomikl** [VirusTotal/yara#436]
Hi Guys,
I am new to Yara.
So.. I created a very simple rule with condition true which means every file that Yara will scan will be detected as infected using this rule.

I ran from windows command line the rule on a file with Japanese filename and got the following error.   

> error scanning c:\??????.txt: could not open file

I am using windows 7, with English char set machine.
What went wrong here?
Because as much as I see this, it is very severe issue, because someone can create a malicious file with this filename and walk through undetected. 
Am I right?

**Comment by hillu** [comment]
The precompiled YARA binaries (both 32 and 64 bit) import the "ANSI" variants such as `CreateFileA` and `CreateFileMappingA` from `KERNEL32.DLL`. Those don't accept wide characters. (This should be changed, in my opinion.)

**Comment by shlomikl** [comment]
OK, thank you for your response.
With your permission, I have another question...
Are the rules in Yara Rules repository (http://yararules.com/) are being examined by some qualified Yara developers? 
In other words, Is it safe to use this repository?

**Comment by Neo23x0** [comment]
No. It's not. 
I don't know exactly what you mean with "safe to use". There are rule sets of higher and lower quality. You should never delete on a YARA rule match unless you are absolutely sure that this is what you want. 

I contrast to common Antivirus solutions, YARA based solutions tend to report on suspicious objects that are neither clean nor malicious. An antivirus has to decide if something is good or bad without any user interaction. 
Many YARA rules that you can find online produce a lot of false positives.

**Comment by shlomikl** [comment]
OK. Thank you for your answer.

**Comment by pe3zx** [comment]
I found the same issue when trying to match an encrypted file from ransomware which is full of non-ANSI characters. Agree with @hillu, this should be changed.
