### ISSUE TITLE
pe: Corner cases

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#441]
# Corner cases in importing or exporting names

I have been looking for corner cases in the PE module by auto-generating rules from [pefile](https://github.com/erocarrera/pefile)'s verdict and passing them to YARA. So far, I am using malware samples from Virusshare for this.

This issue is intended to track those differences.
## The set of valid characters is not complete.

An ASCII minus sign (2e) is a perfectly valid character for DLL names. Commit da6790b0b2d0896a4857ba193ad71b2990e47b79 addresses this.
## Trailing spaces in imported DLLs are ignored.

A simple "hello world"

<pre>
#include <stdio.h>
int main() { puts("hello world"); return 42 }
</pre>

(built using MinGW GCC) can still be loaded and executed after the following change, at least on XP:

<pre>
 00005570: 1460 0000 1460 0000 1460 0000 1460 0000  .`...`...`...`..
-00005580: 1460 0000 6d73 7663 7274 2e64 6c6c 0000  .`..msvcrt.dll..
+00005580: 1460 0000 6d73 7663 7274 2e64 6c6c 2020  .`..msvcrt.dll  
 00005590: 2020 2020 0000 0000 0000 0000 0000 0000      ............
</pre>

Things are not as simple as I initially thought: Chaniging `"msvcrt.dll"` to `"msvcrt"` apparently causes the PE loader to silently add the `".dll"` as the library is still found. In this case, adding a trailing space (resulting in `"msvcrt\x20"`) causes the PE loader to look for `"msvcrt\x20.dll"` -- which leads to an error message.
## File name without terminating null character at EOF

`VirusShare_00000/VirusShare_39440a85aa6e4556858110163bfe99d5` contains the filename `shell32.dll` right at the end of file, without a terminating null character. YARA ignores this name altogether, pefile thinks that the DLL name is `shell32.dl`, with the last letter mising.. The executable loads fine and it does import `shell32.dll`.

Commit c3eb21b0d6a44cb8f50b751c2c71ae69e0264792 addresses thiis.
## Strings (file / function name) without terminating null character at end of section

This is a variation on the previous observation.
`VirusShare_00000/VirusShare_0fd036bc0df937872913f0b9cc26dcd5` has a small overlay that becomes part of what YARA thinks is a function. (pefile gets this [wrong](https://github.com/erocarrera/pefile/issues/114), in a different way.)

<pre>
00028dd0  6f 61 64 4c 69 62 72 61  72 79 41 00 00 00 6c 73  |oadLibraryA...ls|  
00028de0  74 72 63 6d 70 69 41 20  0d 0a 3c 69 66 72 61 6d  |trcmpiA ..*ifram| 
00028df0  65 20 73 72 63 3d 68 74  74 70 3a 2f 2f 77 77 77  |e src=http://www|
00028e00  2e 67 6f 6f 67 6c 65 2e  63 6f 6d 20 77 69 64 74  |.google.com widt|
00028e10  68 3d 30 20 68 65 69 67  68 74 3d 30 3e 3c 2f 69  |h=0 height=0**/i|
00028e20  66 72 61 6d 65 3e 0d 0a                           |frame*..|
</pre>

## Parsing imports stops altogether on first invalid DLL name

See f468d9c1a7316dac18f8c812da7c0e7d9215354d for a fix.
## Import: ILT vs. IAT

`pefile.py` looks at the Import Lookup Table (referenced via OriginalFirstThunk) and the Import Address Table (via FirstThunk). There are cases where OriginalFirstThunk points to a valid address but the ILT makes no sense which leads yara to not find any imports at all. (more investigation / better explanation needed.)
## RVA-to-offset calculations may not be complete

Binaries where the import directory sits somewhere between sections can still be loaded, but YARA misses the imports because the RVA->offset calculation returns no valid value for them. Commit 446939351079ae45690f5f68635a4837ec0fd706 addresses this.

**Comment by plusvic** [comment]
Good job catching those corner cases.
