### ISSUE TITLE
Returning ERROR_WRONG_ARGUMENTS from Hash module and scanning a process

### ISSUE THREAD

**Issue by bmagistro** [VirusTotal/yara#452]
If a rule such as the one below is included scanning a process, the return is "ERROR_WRONG_ARGUMENTS" which causes scanning to be aborted.  In this case it looks like the culprit is `offset < context->mem_block->base`.  My thinking is that it should follow [https://github.com/plusvic/yara/issues/381] which would instead allow the rule set to continue to run.  This may be something that is better solved by keeping file/directory and pid rule files split.

```
import "hash"
rule rule1 {
  condition:
    hash.md5(0,filesize) == "ded77e167425bf97d4d09cb4d4e7b6e6"
}
```

Thoughts?

**Comment by plusvic** [comment]
Fixed in 17e0fc4590a1777fc4fc249ee154def203a56112.
