### ISSUE TITLE
Travis no longer compiles, tests any code.

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#465]
Since [build #102](https://travis-ci.org/VirusTotal/yara/builds/138869433), corresponding to commit b11898b, Travis no longer runs the `./configure && make && make check` line. I can't see anything in that commit that may have broken the Travis integration.

**Comment by plusvic** [comment]
Really weird :(

**Comment by hillu** [comment]
Must have been a problem on Travis' side. Everything seems to be fine now.
