### ISSUE TITLE
Is the license change as simple as this?

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#470]
Hi Victor,

don't you have to get permission from the individual copyright holders before changing the license?

I agree with changing the YARA license to BSD-3-clause.

Cheers,
-Hilko

**Comment by plusvic** [comment]
You're probably right. As the list is short enough I'm going to ask individual copyright holders their opinion about this change.

**Comment by wxsBSD** [comment]
I thought so too, but I'm also in favor of this change. No need to mail me!

**Comment by NtReleaseEpinephrine** [comment]
I use a modified version of YARA in an incredibly large, non-open-source project... but I am unsure of how I'm meant to approach the licensing of it. How would one go about being compliant with YARA's license whilst stating a different license for the non-YARA parts? I've done some research but I'd rather not make a mistake and break the rules, so hopefully someone can provide more insight to help me.

**Comment by wxsBSD** [comment]
IANAL but it’s just 3 clause BSD, which boils down to keep our copyright and license on the files on which they appear in both src and binary form (ie: give us credit for our work) and don’t use our names as endorsements. BSD licenses are considered permissive in that you can incorporate them into a closed source project provided you meet those 3 (in this case) conditions.
