### ISSUE TITLE
internal err 30, too many hits

### ISSUE THREAD

**Issue by jaroslavnahlik** [VirusTotal/yara#473]
when badly written, too common rule happens, i.e. 

rule Rulename
{
 strings:
        $s02 = { 00 } 

condition:
        $s02 at (filesize - 1)
}

result is "internal error 30" message. in old issues i found same incident with too many hits on rule. apparently, it is same situation.

to recognize which rule it triggered and for what reason, display for example "internal error 30, too many hits at Rulename" what will be understand simply.

**Comment by plusvic** [comment]
Already fixed in latest version.
