### ISSUE TITLE
[docs] Remove a duplicated semicolon

### ISSUE THREAD

**Issue by NoviceLive** [VirusTotal/yara#482]
Hi, https://github.com/VirusTotal/yara/blame/master/docs/yarapython.rst#L132 renders incorrectly.

![yarapy](https://cloud.githubusercontent.com/assets/7678237/17253335/513248e6-557e-11e6-9239-7de17cbc2f1e.png)

**Comment by plusvic** [comment]
Fixed in e36464f4a220a94890ebaa8501f6bc5691a5f0c7
