### ISSUE TITLE
why are you returning an exit code of 1 for yara --help

### ISSUE THREAD

**Issue by blacktop** [VirusTotal/yara#485]
I was trying to do a CI workflow, but running yara --help failed the test.

Why not exit 0?

**Comment by plusvic** [comment]
The latest version returns EXIT_SUCESS when you run it with --help. Are you using the latest one?

**Comment by blacktop** [comment]
I am now !!! 😄 thank you for such a great tool !! https://github.com/blacktop/docker-yara
