### ISSUE TITLE
windows/lib/libeay64.lib and others built with VS2010

### ISSUE THREAD

**Issue by jpvlsmv** [VirusTotal/yara#495]
I've been trying to build yara-python with submodule 74734418a256c5304ccaf1d322c57e305ff75362 yara (v3.5.0) on Python 3.5 (Anaconda3) amd_64 with the Microsoft Visual C++ Build Tools 2015 (aka Visual Studio 14.0, but only the command line)

The linker complains:

```
   Creating library build\temp.win-amd64-3.5\Release\yara.cp35-win_amd64.lib and
 object build\temp.win-amd64-3.5\Release\yara.cp35-win_amd64.exp
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol _vsnwprintf
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol vfprintf
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol __iob_func
build\lib.win-amd64-3.5\yara.cp35-win_amd64.pyd : fatal error LNK1120: 3 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
```

According to [http://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2](url), this is caused by having parts compiled with different versions of Visual Studio.

I can't see how to rebuild windows/lib/libeay64.lib, but I can see that this one was built with Visual Studio 10.0. (strings libeay64.lib | grep cl.EXE).

I downloaded the VS14.0-precompiled 1.0.1t from [http://www.npcglib.org/~stathis/blog/precompiled-openssl/](url), and overwrote libeay64.lib with the openssl-1.0.1t-vs2015.7z\openssl-1.0.1t-vs2015\lib64\libeay32MT.lib

This worked (it's the 64-bit version since it is in lib64, even though it's named eay32) and yara-python is happy with the results.  (There is one failure in setup.py test: testCompare fails on data['constants']['foo'], but I can't imagine how that could be related to this lib)

If useful, I can try to put together a pull request to add the right windows\lib\vsXXXX into the /LIBPATH variables and move libeayXX.lib there, or to just replace the current file in its current location.

**Comment by kallanreed** [comment]
There was a lot of push back to checking in the new VS2015 binaries. Ended up settling on a nuget package that contained the binaries. See #414 

It looks like the current binaries are out of date as of July 1 when OpenSSL was updated in this project.

**Comment by plusvic** [comment]
The VS 2010 project is not supported anymore and the VS 2015 project has been revamped to make use of NuGet.
