### ISSUE TITLE
Regression in Hexstring Parsing (Throwing Syntax Error)

### ISSUE THREAD

**Issue by securitykitten** [VirusTotal/yara#496]
When running the following rule in Yara 3.4.0 no error is generated, but it fails to compile in the latest version of Yara (3.5.0)

The rule is here -> https://github.com/mattulm/sfiles_yara/blob/master/malware/RomeoFoxtrot.yara

Commands are posted below

Yara version
```
$ yara -v
yara 3.4.0
```

Running the rule
```
$yara -s RomeoFoxtrot.yar file
$
```

And with Yara 3.5
```
$ yara -v
yara 3.5.0
```

Running the rule
```
$yara -s RomeoFoxtrot.yar file
RomeoFoxtrot.yar(50): error: invalid hex string "$connect": syntax error, unexpected '|', expecting _BYTE_ or _MASKED_BYTE_ or '(' or '['

```

**Comment by plusvic** [comment]
Same than #481
