### ISSUE TITLE
Syntax error in rules with jump inside group in Yara 3.5

### ISSUE THREAD

**Issue by arbor-jjones** [VirusTotal/yara#498]
Seemed to work (or at least not throw errors) in Yara 3.4 and prior

In 3.5, seeing

> test.yara(4): error: invalid hex string "$hex_string": syntax error, unexpected '[', expecting _BYTE_ or _MASKED_BYTE_ or '('

With a rule of this form and also throws an error after removing the | and leaving the parens. Removing the parens at that point makes it function fine or replacing the static jumps with appropriate number of ?? will also work, but that's not easily doable with the ranges

```
rule JumpExample
{
        strings:
           $hex_string = { F4 23 ([4-6] | ff) 62 B4 }

        condition:
           $hex_string
}
```

A number of the yara rules available from the Operation Blockbuster report by Novetta and others were what first turned me onto a possible issue:

> hxxp://www.operationblockbuster.com/YaraSigs.zip

**Comment by plusvic** [comment]
Same than #481
