### ISSUE TITLE
Using pe module with yara-python

### ISSUE THREAD

**Issue by tincho9** [VirusTotal/yara#499]
I was looking in the documentation, and did not find it.
Is it possible?

**Comment by wxsBSD** [comment]
The modules are part of YARA, and yara-python is just a python interface to libyara. Just write your rules using the PE module normally and use them in yara-python.

**Comment by plusvic** [comment]
And the documentation is at http://yara.readthedocs.io/en/latest/modules/pe.html

**Comment by cgupta6** [comment]
I resolved it using and worked for me:
pip install --global-option="build" --global-option="--enable-cuckoo" --global-option="--enable-magic" yara-python
