### ISSUE TITLE
Segfault on invalid regex patterns

### ISSUE THREAD

**Issue by ghost** [VirusTotal/yara#503]
The **invalid** regex pattern `\x` produces a segfault.
Isn't there a way to _detect_ invalid regex patterns before attempting to match them?

Test data:

```
rule test: error
{
    meta:
        description = "Tests yara against an invalid regex pattern."

    strings:

        $r2 = /this is an invalid regex pattern: \x/

    condition:
        all of them
}
```

**Comment by plusvic** [comment]
Which version of YARA are you using?

**Comment by Daxda** [comment]
I *think* I'm on the master branch of this repo.
yara tells: 3.5.0

**Comment by plusvic** [comment]
Interesting, I tested the rule with the latest version and didn't get a segfault. Can you provide a dump file or any other detail about your system configuration?

**Comment by Daxda** [comment]
Sorry for the wait. I think I figured out where core dumps are located :)
I uploaded the core dump on my website: [https://echo.rip/downloads/core.yara.1000.b435b42205bb462ca7664b3f07a68e6a.4849.1471359155000000000000.lz4](here

Please notify me when you've obtained the file so I can remove it from my webserver.

**Comment by plusvic** [comment]
I can't load the dump file in my system. What operating system are you using?

**Comment by Daxda** [comment]
Arch Linux. Could I help you in any other way?

**Comment by maxvonhippel** [comment]
The dump url points to a GitHub 404 now.  Did this ever get resolved?

**Comment by hillu** [comment]
@maxvonhippel no, it did not. As of 6fd48837b98747264e3c1b8476e0b271935aab36, I can still reproduce the segfault on Debian unstable/amd64.

**Comment by hillu** [comment]
The bug manifests itself in [`read_escaped_char()`](https://github.com/VirusTotal/yara/blob/master/libyara/re_lexer.l#L518) where the EOF condition is not triggered.
