### ISSUE TITLE
Regex matching multiple times on greedy mode

### ISSUE THREAD

**Issue by Xumeiquer** [VirusTotal/yara#504]
I don't know if the following behaviour is either the desired or not, but I can't understand it. I'll apreciate it, if someone could explain it to me.

Having the following yara rule
```
rule test_rule
{
    strings:
        $a = /[A-Za-z0-9]{2,}/
    condition:
        $a
}
```

And checking the rule against a text file with this content
```
abcdefghijklmnopqrstuvwxyz
 ```

Finally, running yara I get the following result
```
yara -s test.yar test.txt
test.yar(5): warning: $a is slowing down scanning (critical!)
test_rule test.txt
0x0:$a: abcdefghijklmnopqrstuvwxyz
0x1:$a: bcdefghijklmnopqrstuvwxyz
0x2:$a: cdefghijklmnopqrstuvwxyz
0x3:$a: defghijklmnopqrstuvwxyz
0x4:$a: efghijklmnopqrstuvwxyz
0x5:$a: fghijklmnopqrstuvwxyz
0x6:$a: ghijklmnopqrstuvwxyz
0x7:$a: hijklmnopqrstuvwxyz
0x8:$a: ijklmnopqrstuvwxyz
0x9:$a: jklmnopqrstuvwxyz
0xa:$a: klmnopqrstuvwxyz
0xb:$a: lmnopqrstuvwxyz
0xc:$a: mnopqrstuvwxyz
0xd:$a: nopqrstuvwxyz
0xe:$a: opqrstuvwxyz
0xf:$a: pqrstuvwxyz
0x10:$a: qrstuvwxyz
0x11:$a: rstuvwxyz
0x12:$a: stuvwxyz
0x13:$a: tuvwxyz
0x14:$a: uvwxyz
0x15:$a: vwxyz
0x16:$a: wxyz
0x17:$a: xyz
0x18:$a: yz
```

When I expect something like the following
```
yara -s test.yar test.txt
test.yar(5): warning: $a is slowing down scanning (critical!)
test_rule test.txt
0x0:$a: abcdefghijklmnopqrstuvwxyz
```
because the regex is greedy and it should catch the longest string and not all the substrings. This means that yara is executing the whole rule on each offset and this behaviour is slowing down the rule instead of executing the rule just one time because de regex is greedy.

**Comment by plusvic** [comment]
Yes, that's the intended behaviour. Suppose that your condition is "$a at 0x6", in this case the rule is expected to match, because the regexp matches at position 0x6 too. YARA reports all the offsets where a regexp/string matches.
