### ISSUE TITLE
bug in handling \r

### ISSUE THREAD

**Issue by HostageBrain** [VirusTotal/yara#506]
I'm using yara from python with such rule (just an example for illustration of a problem):

```
rule my_rule {
strings:
$a = {
50 45 00 00
}
condition:
$a
}
```

where braces near hex digits located in different lines, and where each line ends with windows end-of-line \r\n - nothing works. I've got this tracelog:

```
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    rules = yara.compile(source=rule_body, error_on_warning=True)
yara.SyntaxError: syntax error, unexpected '{', expecting _REGEXP_
```

and when I'm deleting all \r from file - everything works fine.
Console utility - yara64.exe - works fine when there are \r or \r\n, but not \r\r.
Why yara-python & yara64.exe behavior differs - I don't know.

I think problem is in file libyara/lexer.l:
`\{(({hexdigit}|[ \-|\?\[\]\(\)\n\t]|\/\*[^*]*\*\/)+|\/\/.*)+\} {`
must be
`\{(({hexdigit}|[ \-|\?\[\]\(\)\n\r\t]|\/\*[^*]*\*\/)+|\/\/.*)+\} {`

**Comment by plusvic** [comment]
Fixed in f4b535fa2b8adb73a0494b8f96d16af0c920180d
