### ISSUE TITLE
Entropy and PE64 files not working ?

### ISSUE THREAD

**Issue by Chandlr** [VirusTotal/yara#508]
iam doing a simple check:
(math.entropy(0, filesize) > 7.0)
and it seems it doest work with PE64 files but PE32 anyone know why ?

**Comment by wxsBSD** [comment]
Can you share an example file that works and one that doesn't?

**Comment by Chandlr** [comment]
Sorry i noticed with yara gui that they had lower than 7.0 entropy
they are vmprotectsdk protected files. So the section itself was higher but 
"(math.entropy(0, filesize)" is not
