### ISSUE TITLE
Rule compilation time increase between 3.4.0 and 3.5.0

### ISSUE THREAD

**Issue by ewil** [VirusTotal/yara#510]
I upgraded from 3.4.0 to 3.5.0 and noticed an increase in compilation time from instant to about 20 seconds. I was able to identify the rule causing the problem:

https://github.com/godaddy/yara-rules/blob/master/emotet.yara#L33

It's a long rule being program-generated but it was highly effective and useful. Compilation hasn't been a problem before but with 3.5.0 the performance hit in compilation is prohibitive for my use case.

I profiled libyara to try to help debug this and found that the majority of time is spent in the function _yr_ac_find_suitable_transition_table_slot() at https://github.com/VirusTotal/yara/blob/master/libyara/ahocorasick.c#L454.

A picture of the call stack is below:

![yr_ac_find_suitable_transition_table_slot](https://cloud.githubusercontent.com/assets/1305683/18188461/2bf601fe-7067-11e6-94d1-c2b5d8f06123.PNG)

I tried to follow the code to understand the root cause but don't know enough about the context. Any advice appreciated. Thanks!

**Comment by plusvic** [comment]
Very interesting issue. YARA 3.5 improves the scanning time at the cost of spending more time compiling the rules, but you have hit one of the worst cases for the _yr_ac_build_transition_table function. Let me see what can I do to improve the compilation time in these extreme cases.

**Comment by dcode** [comment]
Complete yara noob here, but would it be possible to make the optimization optional at compile time, similar to GCC w/ -O flags? I recompile yara rules often to get latest updates.

**Comment by plusvic** [comment]
#873 reduces compilation time. In this particular case from ~6 seconds to ~1 second in my machine.
