### ISSUE TITLE
Segfault on invalid imports

### ISSUE THREAD

**Issue by fumfel** [VirusTotal/yara#516]
Invalid import `"\x00"` causes a **segfault**.

Tested on yara 3.5.0 (cloned today from master).

Test data:
`import "\x00"`

Valgrind output: https://gist.github.com/fumfel/497b0863667d4cd4a1819872328e5b6d

Bug exists in **yara/libyara/hash.c**:
- https://github.com/VirusTotal/yara/blob/f502bdf4903545cfc75dfe15bed650138da53a81/libyara/hash.c#L73
- https://github.com/VirusTotal/yara/blob/03c2aac2c1253b096342cf4b745d66e448c7d110/libyara/hash.c#L183
- https://github.com/VirusTotal/yara/blob/03c2aac2c1253b096342cf4b745d66e448c7d110/libyara/hash.c#L93

Bug found with american fuzzy lop.

**Comment by fumfel** [comment]
Problem still exists, tested repo HEAD: a0bb3836f16e3c5d0c2a1da097a1ebacbebc3a94.

**Comment by wxsBSD** [comment]
Fix is up. I'd be curious if you are able to trigger this any other way, especially via modules parsing files. :)
