### ISSUE TITLE
Double free on invalid regexp 

### ISSUE THREAD

**Issue by fumfel** [VirusTotal/yara#517]
Null bytes in regexp causes **double free memory corruption**.

Tested on yara 3.5.0 (cloned today from master) - [test data](https://github.com/VirusTotal/yara/files/471917/yara_double_free.txt)

Valgrind output - https://gist.github.com/fumfel/f300effa99b87a2a90f9db2a91a7d751

Bug exists in **yara/libyara/lexer.l**:
- https://github.com/VirusTotal/yara/blob/master/libyara/lexer.l#L562

I would like to thank @psrok1 for help.

Bug found with american fuzzy lop.

**Comment by fumfel** [comment]
[Another payload - free() execution with address (0xdeadbeef) located after string name.](https://github.com/VirusTotal/yara/files/472126/segfault_deadbeef.txt)

**Comment by psrok1** [comment]
It seems that token /[NUL]/ is interpreted by lexer as "empty regexp", which is not properly handled. Lexer produces regexp token with yylval from previous token.

Bug appears in this commit:
https://github.com/VirusTotal/yara/commit/11fd5e4784fa135cbdb64906cc628edb9e9d50ee#diff-f33cc51a50dcf0e802a78296718f6b6c

**Comment by plusvic** [comment]
Fixed in 658aec6227a61b848f66b004ebd16fadcf24b5e7
