### ISSUE TITLE
was 3.5.0 retagged?

### ISSUE THREAD

**Issue by ilovezfs** [VirusTotal/yara#518]
A homebrew user reported a checksum mismatch for the 3.5.0 tarball: https://github.com/Homebrew/homebrew-core/issues/4822

And indeed it seems to have changed as described. Was 3.5.0 retagged? It's our policy to confirm nothing malicious has happened upstream whenever a checksum changes without the version also changing.

**Comment by plusvic** [comment]
Yes, it was retagged. You can safely update to the new checksum.

**Comment by ilovezfs** [comment]
@plusvic thanks for confirming!
