### ISSUE TITLE
Missing include uinstd.h in Windows

### ISSUE THREAD

**Issue by Mi4uric3** [VirusTotal/yara#519]
Hi,

I'm not very experienced with Git, so this might be a problem on my side.
I just cloned the project and opened the Visual Studio 2015 solution and tried to compile x86-Release, but in `libyara/lexer.c`, line 759 the `#include <uinstd.h>` can't be found. It is used in line 3261: `len = read(rules_fd, buf, sizeof(buf))`
I read that this file is a UNIX typical file which doesn't exist on Windows platforms.

Best Regards,
Maurice

**Comment by kallanreed** [comment]
Introduced in c48cea7b5363f06f4a87d1524655735ef3699b64

**Comment by hillu** [comment]
@Mi4uric3 Please have a look if PR #520 (commit 9a7a1ec21c4a0601acc27cf010856d6cf1da8b8c) fixes the issue for you. (I don't have a Visual Studio compiler available.)

**Comment by kallanreed** [comment]
The tests aren't currently built in the Windows projects but unistd.h was also referenced in the test that was added for this.

Sent from my iPhone

On Sep 17, 2016, at 05:58, Hilko Bengen <notifications@github.com<mailto:notifications@github.com>> wrote:


@Mi4uric3<https://github.com/Mi4uric3> Please have a look if PR #520<https://github.com/VirusTotal/yara/pull/520> (commit 9a7a1ec<https://github.com/VirusTotal/yara/commit/9a7a1ec21c4a0601acc27cf010856d6cf1da8b8c>) fixes the issue for you. (I don't have a Visual Studio compiler available.)

-

**Comment by hillu** [comment]
* Kyle Reed:

> The tests aren't currently built in the Windows projects but unistd.h
> was also referenced in the test that was added for this.

Right...

After looking at the libc documentation on MSDN, I found that there are
open(), read(), functions after all.

I'll be updating my patch once more.

Cheers,
-Hilko

**Comment by kallanreed** [comment]
I think you still want ReadFile instead of read. ReadFile doesn't require the C runtime library which is why (I think) the rest of the Windows code is using the Win32 APIs. @plusvic is that correct?

Sent from my iPhone

On Sep 17, 2016, at 08:57, Hilko Bengen <notifications@github.com<mailto:notifications@github.com>> wrote:

* Kyle Reed:

> The tests aren't currently built in the Windows projects but unistd.h
> was also referenced in the test that was added for this.

Right...

After looking at the libc documentation on MSDN, I found that there are
open(), read(), functions after all.

I'll be updating my patch once more.

Cheers,
-Hilko


-

**Comment by plusvic** [comment]
Yes, I agree with @kallanreed in using the ReadFile instead. All other Windows-specific code interacts with the Windows API directly.

**Comment by hillu** [comment]
@plusvic The latest incarnation of my PR does use ReadFile both in the
lexer and in the test code.

**Comment by kallanreed** [comment]
This still doesn't work, the lexer.c needs to be regenerated and checked in. @hillu if you can regenerate that would be helpful.

**Comment by hillu** [comment]
* Kyle Reed:

> This still doesn't work, the lexer.c needs to be regenerated and checked in. 
> @hillu if you can regenerate that would be helpful.

Mhm. Would it make sense to remove flex- and bison-genrated files and
only include them in release tarballs?

-Hilko

**Comment by plusvic** [comment]
I regenerated lexer.c. The problem with removing flex- and bison-generated files from the repository is that Windows users usually don't have flex nor bison, so the files are not auto-generated for them.
