### ISSUE TITLE
No CI for Windows

### ISSUE THREAD

**Issue by kallanreed** [VirusTotal/yara#523]
The Windows project is somewhat broken right now - *ix specific code introduced by contributors and it looks like there was an update to OpenSSL that may have caused some import regressions.

Ideally Windows would be CI, Travis doesn't support Windows. I'm taking a look at AppVeyor which is free for open source projects.

If I can get it working on my fork, it would be useful to add AppVeyor CI to keep this project from regressing on Windows. Also, AppVeyor could be used to build Windows releases and deploy NuGet packages.

https://ci.appveyor.com/project/kallanreed/yara

**Comment by plusvic** [comment]
That would be a great contribution. Most people don't have a Windows setup
to test their changes and it would be nice if we can detect this kind of
issues promptly.

**Comment by hillu** [comment]
Related to this: Cross-building using MinGW on Travis. #525

**Comment by kallanreed** [comment]
@plusvic check out https://ci.appveyor.com/project/kallanreed/yara/history and https://ci.appveyor.com/project/kallanreed/yara/build/1.0.9 (for details) and see if this is sufficient. I'm trying to figure out PR integration, tests and even have it publish binaries to the feed.

If you want to integrate, you'll need to set up an account on AppVeyor with an account that can admin the yara repo.

**Comment by plusvic** [comment]
I've created an account but need to take a look on how to configure everything. Do you have any guidelines?

**Comment by kallanreed** [comment]
I'll send the yaml file from my set up. It's also possible to add a yaml file to the root (like travis) and have it "just work" but I haven't tried that yet.

**Comment by kallanreed** [comment]
I've added the appveyor.yml to PR #526 with info on getting everything set up.
