### ISSUE TITLE
Master no longer compiles on VS2015 - PE type moved into header and is conditionally compiled out.

### ISSUE THREAD

**Issue by kallanreed** [VirusTotal/yara#524]
Changes introduced in 7f1596d5b802567a0b81d95ddd0f6b3ebb234d6a cause numerous compiler errors in Visual Studio 2015.

Affected files are pe.c and pe_utils.c

**Comment by hillu** [comment]
This may be the same issue I ran into while cross-compiling with MinGW, `PE`, `IMPORTED_FUNCTION`, `IMPORTED_DLL` are not defined.

**Comment by plusvic** [comment]
Fixed
