### ISSUE TITLE
[ Extending-Moule ]: How to record matched results.

### ISSUE THREAD

**Issue by cuckoomodify** [VirusTotal/yara#540]
Hi,
    Does yara extending  moule support recording matched result ? Like recording matched strings in rule.strings when a rule match file or string datas, so that we can know what matched.
    How can I add strings which matched in my own module to rule.strings ? 
    Please take a little time to help me resolve this problem, thank you!

**Comment by plusvic** [comment]
No, modules don't have access to the list of matching strings. What modules do is exposing extra information to YARA that can be used in rules, but they don't have control over the matching strings.
