### ISSUE TITLE
RfC: Split headers into public and private API

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#541]
It was brought to my attention by @comawill today that while some header files
that get installed via "make install" include config.h -- which
is not installed:
- mem.h: definition of yr_malloc and friends based upon configure
  parameter
- strutils.h: aliasing of snprintf, stri(n)cmp, definition of
  strlcpy, strlcat, memmem... (determined through configure)
- utils.h: Various compiler-specific settings, assert (config
  parameter), the recently introduced byte-sswapping
  operations (variant determined through configure), bit
  twiddling macros

I have not specifically looked for other, indirect uses yet, but
I think that none of the functions and macros I have listed above
should be considered part of YARA's public API. I therefore
propose that we try moving the three files to a different
subdirectory, perhaps libyara/include/internal, make the
necessary changes so that they are no longer included from heaer
files that _are_ part of the public API.

**Comment by fooinha** [comment]
This is a problem to whom wishes to use libyara.

```c
~/yara-3.5.0+dfsg# echo -e "#include <yara.h>\nint main(int argc, char **argv) { return 0; }" > /tmp/foo.c && gcc -E  -c /tmp/foo.c -lyara
# 1 "/tmp/foo.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "/tmp/foo.c"
# 1 "/usr/include/yara.h" 1 3 4
# 33 "/usr/include/yara.h" 3 4
# 1 "/usr/include/yara/utils.h" 1 3 4
In file included from /usr/include/yara.h:33:0,
                 from /tmp/foo.c:1:
/usr/include/yara/utils.h:34:20: fatal error: config.h: No such file or directory
 #include <config.h>
                    ^
compilation terminated.
```

**Comment by plusvic** [comment]
This shouldn't be an issue anymore as we stoped using `config.h`.
