### ISSUE TITLE
YR_TRYCATCH unmasks all signals which causes segfault

### ISSUE THREAD

**Issue by Professor-plum** [VirusTotal/yara#544]
The new YR_TRY_CATCH routine in 3.5.0 clears all signal masks here https://github.com/VirusTotal/yara/blob/master/libyara/exception.h#L108 
this will cause a seg fault if there are any pending masked signals.
Shouldn't we just unmask the particular signal we are interested in and only _after_ the sig handler is already setup?  
If the intent of line 108 is to just retrieve the current mask status then the second parameter should be NULL.

**Comment by plusvic** [comment]
@hillu Could you take a look at this?

My guess is that the intention with line 108 is getting the current mask in order to restore it later in line 120. But according to the documentation `sigsetjmp` saves the current mask if the second argument is non-zero, and the mask should be restored by `siglongjmp`. So, are the calls to `pthread_sigmask` actually necessary?

**Comment by hillu** [comment]
* Victor M. Alvarez:

> @hillu Could you take a look at this?
>
> My guess is that the intention with line 108 is getting the current
> mask in order to restore it later in line 120. 

That's what I must have had in mind. But setting act.sa_mask (the signal
mask to be used when the handler is run) makes no sense, it should
probably be pthread_sigmask(SIG_SETMASK, NULL, &oldmask) as suggested.

> But according to the documentation sigsetjmp saves the current mask if
> the second argument is non-zero, and the mask should be restored by
> siglongjmp.  So, are the calls to pthread_sigmask actually necessary?

Looks like it. Let me see if I can come up with a proper test setup for
this.

Cheers,
-Hilko

**Comment by hillu** [comment]
@Professor-plum Are you sure that you noticed a segmentation fault? I can demonstrate that the process is terminated by default action if a signal (e.g. `SIGUSR1`) is pending, but not actually a segmentation fault.

**Comment by Professor-plum** [comment]
I can confirm the latest commit fixes the issue for us,  thank you!
