### ISSUE TITLE
Previously valid wildcard feature now causes rule error in 3.5

### ISSUE THREAD

**Issue by bmboyle** [VirusTotal/yara#545]
When moving from Yara 3.4 to 3.5, certain Yara rules started to cause compilation errors. The issue deals with wild cards at the start and end of OR statements in rules. Here is an example of a rule that is now invalid in 3.5 and what it takes to resolve it:

Invalid - $a = { 11 22 33 (44 | [1-3] 55) 66 }
Valid    - $a = { 11 22 33 (44 | ?? 55 | ?? ?? 55 | ?? ?? ?? 55) 66 }

It seems like the compiler/validator was changed to catch wildcards at the start and end of rules but treats entries in OR blocks the same way. Being able to do blocks like [1-3] within OR blocks is a valuable feature and is more readable than expanding them out.

**Comment by plusvic** [comment]
Same than #481.
