### ISSUE TITLE
Feature Request: Add a Ruby binding

### ISSUE THREAD

**Issue by fabianfrz** [VirusTotal/yara#547]
Add a Ruby binding either by FFI or as a native extension. The gem available (yara) does not seem to work with the current version of yara.

**Comment by plusvic** [comment]
This is worth a separate project and I'll leave it to the community. A [previous effort](https://github.com/SpiderLabs/yara-ruby) was abandoned long ago. I guess Ruby is not that popular among the anti-malware community and there's no enough demand for this, but if anyone wants to implement Ruby bindings for YARA I'll be happy to support it.

**Comment by fabianfrz** [comment]
I wrote a minimalistic one but I don't think it is production ready (It compiles and it can scan a file and returns a `Hash`, containing the result. Seems to work but crashes on old Ruby versions < 2.4).
I can give you access if you like.
