### ISSUE TITLE
Feature req: only scan specific files

### ISSUE THREAD

**Issue by gwillem** [VirusTotal/yara#550]
Thanks for making yara! 

Many hosting providers use it to scan their customer's document root for malware. This process would be greatly sped up if you could restrict the amount of data to scan. For example: only scan files with newer ctime (for nightly scans).

The subject has been brought up before in slightly different form (https://github.com/VirusTotal/yara/issues/202) and was then dismissed. Any chance you would reconsider it?

**Comment by maxvonhippel** [comment]
This is easily accomplished in bash, so I see no reason why it should be implemented natively in Yara.  For example, to only scan files with newer ctime:
````BASH
find /path/to/dir -type f -print0 | xargs -0 ls -t | while read file
do
if test `find "$file" -mmin +120`
then
yara my_rules_file "$file"
fi
done
````

**Comment by gwillem** [comment]
@maxvonhippel yes, but at a big performance cost: forking yara, and loading all the rules for every file. Hosting providers usually have billions of (mostly small) files.

**Comment by gwillem** [comment]
Here's a quick benchmark:

```
$ time yara -r rules.yar magento-2.1.3

real	0m4.946s
user	0m3.036s
sys	0m1.024s

$ time (find magento-2.1.3 -type f | xargs -n1 yara rules.yar)

real	1m16.679s
user	0m1.812s
sys	0m2.624s

$ yarac rules.yar rules.yarac
$ time (find magento-2.1.3 -type f | xargs -n1 yara rules.yarac)

real	0m41.485s
user	0m0.584s
sys	0m2.072s
```

So even with precompiled yara rules, launching a yara executable per file is still 8x slower on a typical web application (Magento).

**Comment by wxsBSD** [comment]
Can you do this in python? Compile the rules once then walk the filesystem applying logic you want to each file? You could even distribute this to multiple processes each with their own compiled rule set.

**Comment by gwillem** [comment]
@wxsBSD yup! [Sample Python scanner](https://github.com/gwillem/magento-malware-scanner/blob/d61e94f4087b90c802736ae8e8b58e1a97aec659/tools/scan.py):

```
# time python3 scan.py -r rules.yar magento-2.1.3

real	0m4.104s
user	0m3.384s
sys	0m0.712s
```

It's even faster ;)
