### ISSUE TITLE
elf.entry_point is UNDEFINED on some files

### ISSUE THREAD

**Issue by HostageBrain** [VirusTotal/yara#560]
Here are 2 examples for reproducing the bug.
I don't know where to upload binary files - so, I made 'sfk bin-to-src' and uploaded result on pastebin - you can easily convert them back to binary form. (both files are malware samples, so I'm not sure you should add them to tests after fix :)

11a13d2eeb71573178d7686930340c51c8f3ce26 - http://pastebin.com/ZwQUeQZY - It's elf for MIPS architecture. elf.entry_point is 0xfffabadafabadaff (UNDEFINED), but actually it must be 0x12C.

1fe1872cf18cd0101f0870ca58f68d6686010326 - http://pastebin.com/kSfhEvrL - It's elf for ARM architecture. elf.entry_point on my pc (windows, x64 bits) is also 0xfffabadafabadaff (UNDEFINED), but actually it must be 0xA4.

I've checked entry point calculation in: ida pro & radare2 - both show the same value.

**Comment by hillu** [comment]
Yeah, both of those files are for big-endian architectures and yara's elf module does not deal with that. Fix coming up.

**Comment by plusvic** [comment]
Fixed in 53ddc4a8f7cf423a53168eefc10ae6c13dba67f8
