### ISSUE TITLE
_CONCAT is a reserved identifier

### ISSUE THREAD

**Issue by StephanTLavavej** [VirusTotal/yara#564]
yara/libyara/include/yara/modules.h defines `_CONCAT` which is a `_Leading_underscore_capital` identifier reserved for use by the compiler and standard library. MSVC's STL actually defines its own `_CONCAT` macro (now in `<type_traits>` in MSVC 2017).

It appears that yara's `CONCAT` is the public interface, while the reserved `_CONCAT` is an implementation detail. Therefore, the fix should be simple: rename `_CONCAT` to anything non-reserved, like `CONCAT_IMPL`.

**Comment by plusvic** [comment]
Fixed in bf32e1e27a75459821bb41285517f245875260ba

**Comment by StephanTLavavej** [comment]
This avoids the conflict, but please note that `_YR_CONCAT` is still a reserved identifier, because it begins with an underscore and a capital letter. `YR_CONCAT_IMPL` would be non-reserved.
