### ISSUE TITLE
How can determine the number of times a character string appears in an address range

### ISSUE THREAD

**Issue by Bi3g0** [VirusTotal/yara#569]
#a == 6: times that the string appears in the whole file
How can I determine  the number of times that a string appears in an address range?

**Comment by Bi3g0** [comment]
I want to do like this: #a == 6 in (0..100)

**Comment by wxsBSD** [comment]
What about this:

```
wxs@wxs-mbp yara % cat foo
FOObarFOO
wxs@wxs-mbp yara % cat test2.sig
rule test {
  strings:
    $a = "FOO"
  condition:
    #a == 2 and
    for all i in (1..#a):
      (@a[i] >= 0 and @a[i] <= 100)
}
wxs@wxs-mbp yara % ./yara test2.sig foo
test foo
wxs@wxs-mbp yara %
```

**Comment by Bi3g0** [comment]
Sorry, my English is not good.I think I may not be clear about my problem. I want to count how many times the string appears in an address range.
like this：#a == 2 in (0..100) or #a==3 in (50..100)

**Comment by wxsBSD** [comment]
I think this does what you want, though I haven't tested it.

```
(
  #a == 2 and
  for all i in (1..#a):
    (@a[i] >= 0 and @a[i] <= 100)
)
or
(
  #a == 3 and
  for all i in (1..#a):
    (@a[i] >= 50 and @a[i] <= 100)
)
```

**Comment by Bi3g0** [comment]
I think yara can't meet my condition. 
#a： how many times the string appears in the file or process memory . Not  an address range.
`(
  #a == 3 and
  for all i in (1..#a):
    (@a[i] >= 50 and @a[i] <= 100)
)`
In this condition, $a cat't appears in the (0..49). I want to count the times that $a appears in only (50..100)
![image](https://cloud.githubusercontent.com/assets/18691823/20958754/37ff8aa2-bc92-11e6-9e34-2cc276bea0bf.png)
![image](https://cloud.githubusercontent.com/assets/18691823/20958762/40301980-bc92-11e6-9079-f838d7db8305.png)
And of course, yara match nothing.
![image](https://cloud.githubusercontent.com/assets/18691823/20958776/4d8c8870-bc92-11e6-8fae-336d8b9cd52e.png)
Thank you the same to you.

**Comment by wxsBSD** [comment]
I think I see now. You don't care how many times the string matches in total. As long as some number of them are in a given range.

**Comment by plusvic** [comment]
What you need is:
```
for 3 i in (1..#a): (@a[i] >= 50 and @a[i] <= 100)
```

**Comment by Bi3g0** [comment]
@plusvic  Thank you，this is what I want!
![image](https://cloud.githubusercontent.com/assets/18691823/20994183/e2872c4a-bd29-11e6-9973-432174914679.png)
![image](https://cloud.githubusercontent.com/assets/18691823/20994195/ed1814ee-bd29-11e6-8aa8-2bcc4c1b84aa.png)
![image](https://cloud.githubusercontent.com/assets/18691823/20994207/fb9f2ffc-bd29-11e6-8ba5-679eed3ad605.png)
@wxsBSD Thank you all the same, my english is not good,so I can't express clearly.

**Comment by wxsBSD** [comment]
I had typed that out in one of my replies but decided against submitting it because I thought you wanted _EXACTLY_ 3 matches in a given range, instead of _AT LEAST_ 3 matches in that range but the rest of the matches could be anywhere. In any case, glad you got it solved and sorry I didn't post that solution. :)

**Comment by zixty** [comment]
Hi 
do you know any way to count the @ characters
I try to create a rule that counts the emails after the TO:

rule mail 
{
strings:
$a = "To:"
$b = "@"		
condition:
($a) and (#b) > 2
}
