### ISSUE TITLE
3.5.1 bugfix release?

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#573]
The yara package that I maintain in Debian/unstable currently has some patches for big-endian fixes and exception handling. Looking over the commit histrory it occured to me that some of the fixes for parsing bugs should be easy to cherry-pick onto v3.5.0. Are we interested in providing a tagged bugfix-only release?

**Comment by plusvic** [comment]
I think it's a good idea. I don't have enough time to devote to prepare a v3.5.1 but if someone volunteer it would be great.

**Comment by hillu** [comment]
I'd be happy to pull those patches together. FTR, so far the Debian package contains:
- big-endian fixes: a9a1105d923912a27546e5a8940ec1ddc19cd1be, d272b9c742e15d6767f20a7f1c01579b468cceee, d3b77eb1e9ee4731ea11c39fceb262cf4f2b006f
- better signal handling: 8b2b6b8f82b8a8a8830bae122474b39ac2814fc6, 0b3d9a93276d3364b2a3561995d27e8b4a137134, ddd5e975f2c36323e408e0eeedd56db59e0148a0
- sigsegv handling: 35f01653ab162d4302faebcfa36b349b4141344a

I'd also add fixes for the various parser failures. Just tell me how to proceed.

**Comment by plusvic** [comment]
We already have a 3.5 branch (https://github.com/VirusTotal/yara/commits/3.5), you can handpick those commits fixing bugs and apply them to the 3.5 branch. We then create a 3.5.1 release based on that branch.

**Comment by plusvic** [comment]
Closing this issue as 3.6.0 is already released.
