### ISSUE TITLE
YARA C API yr_compiler_add_file() crashes

### ISSUE THREAD

**Issue by iamAzeem** [VirusTotal/yara#574]
Hi,

I'm using `YARA C API` on `Windows 7 (32-bit)` with `Qt 5.7`.
When I load a rules files using `yr_compiler_add_file()`, it crashes with a `segmentation fault`.
Rules file is okay. I used the `yr_compiler_add_string()` function instead and it worked fine.

Anyone experienced the same issue?

**Comment by hillu** [comment]
* Azeem Sajid:

> I'm using YARA C API on Windows 7 (32-bit) with Qt 5.7.
> When I load a rules files using yr_compiler_add_file(), it crashes with a segmentation fault.
> Rules file is okay. I used the yr_compiler_add_string() function instead and it worked fine.
>
> Anyone experienced the same issue?

Just a guess: If YARA and Qt have been linked against different versions
of the Microsoft C runtime library, there may be different assumptions
about the FILE implementation (i.e. struct layout).

In any case, a stack trace of the crash would help in finding out what
happened here.

**Comment by iamAzeem** [comment]
@hillu 
I think you guessed it right. :)
YARA C API was built using VS on Windows 7 and I didn't build Qt. I used the binary package for Windows. Unfortunately, stack trace is not available for the crash. Anyway, I'd try to get a stack trace for it and post it here.

Thanks!
