### ISSUE TITLE
How can I match a string variable which is used in the follow?

### ISSUE THREAD

**Issue by Bi3g0** [VirusTotal/yara#577]
Like this:
`
String a = "test1";
System.out.println(a);
`
`
String b = "test2";
System.out.println(b);
`
I want to match "a" or "b" and so on.
![image](https://cloud.githubusercontent.com/assets/18691823/20958930/47a133ce-bc93-11e6-9bdb-dd934aec18bc.png)

**Comment by Bi3g0** [comment]
How can I get the character which  I can get its virtual address？
Like this:
$a = "yara" and @a[1]=0
hao can I get "y" from @a[1]?

**Comment by Bi3g0** [comment]
I want to kown if there are any other methods like backreferrences.

**Comment by nanshihui** [comment]
i got the same problem

**Comment by plusvic** [comment]
Can you elaborate a little more about what do you want to accomplish? The description of this issue is a bit cryptic.

**Comment by nanshihui** [comment]
rule catch_evil_data: ni
{
    meta:
        description="get evil tcp traffic"
    strings:
     $tcp_reaffic = /tcp:.*/

    condition:
	 "evail_data" in $tcp_reaffic
}

i want catch the special data in tcp data, so   i have to get tcp data, then i want search label in tcp data

**Comment by plusvic** [comment]
What's the format of the data you pass to YARA?

**Comment by nanshihui** [comment]
string  like 
"tcp:asdasdasdasd
tcp:asdasdasdsad
tcp:ssssss"

**Comment by plusvic** [comment]
So, what about this?

```
rule catch_evil_data
{
  strings:
    $evil = /tcp:\w*evil_data/
  condition:
    $evil
}
```

**Comment by nanshihui** [comment]
thanks anyway.    what i want to express is that 
 rule catch_evil_data: ni
{
meta:
description="get evil tcp traffic"
strings:
$tcp_traffic = /tcp:.*/

condition: "evail_data" in $tcp_traffic and $tcp_traffic matches /abc.*bcd/

},
which means  i will use tcp_traffic several times for different purpose.

**Comment by plusvic** [comment]
That can't be done. What you can do is using as many regexps as you need.
