### ISSUE TITLE
Making General rules and scanning of kmalloc spaces in kernel

### ISSUE THREAD

**Issue by viper2020** [VirusTotal/yara#579]
Hi,

I have five rootkit samples (LKM) and I wrote some YARA rules by disassembling the malicious object files.For all those five samples,I generated one rule each which is unique forthat rootkit. When scanning I am able to find out the malware samples that I specified.

I am looking to make some general rules that apply to all these five rootkit samples.

Is there any method to prepare some general rules for all those samples?

Also, Is YARA able to scan vmalloc/kmalloc space in Kernel?

**Comment by plusvic** [comment]
YARA only scans user memory space, not kernel space. Regarding how to create rules for your rookit samples, I'm afraid that's a very specific question out of the scope of this page. But the first step is finding the patterns that those rootkits have in common.
