### ISSUE TITLE
yr_rules_scan_file() return error "could not open file"

### ISSUE THREAD

**Issue by MrJeffyw** [VirusTotal/yara#581]
when I use yr_rules_scan_file() in my code,it returns "could not open file". The file I scan is "C\windows\system32\ntdll.dll".Who knows the reason?

**Comment by hillu** [comment]
> when I use yr_rules_scan_file() in my code,it returns "could not open file". The file I scan is "C\windows\system32\
> ntdll.dll".Who knows the reason?

It should be C: (with a colon). Are you escaping the backslash
characters in your string?

**Comment by plusvic** [comment]
I'm closing this issue because it looks like a problem with the file path. Re-open the issue if you are still getting the same error after escaping backslashes and adding the missing colon.

**Comment by MrJeffyw** [comment]
> I'm closing this issue because it looks like a problem with the file path. Re-open the issue if you are still getting the same error after escaping backslashes and adding the missing colon.

It is my input error!Do not you see that......
