### ISSUE TITLE
How to print matched rules  in YARA

### ISSUE THREAD

**Issue by viper2020** [VirusTotal/yara#588]
Hi all,

I saw in the documentation that if we use '-s' option, we can print all matched strings in the rule.

I am not getting any printed strings if I use '-s' option.

There was an output when I used '-r' option.

Can somebody help me with this?

Thanks

**Comment by wxsBSD** [comment]
You will need to provide more details here. Can you provide a single rule and input file which exhibits this behavior? What are you expecting to see that isn't there?

**Comment by plusvic** [comment]
Closing because not enough information was provided.
