### ISSUE TITLE
Division operator in conditions interpreted as start-of-regex

### ISSUE THREAD

**Issue by Northern-Lights** [VirusTotal/yara#591]
I have this `for` iteration which I would like to use to detect if at least half of these strings `$s1` are within 100 bytes of each other:

`for (#s1/2) i in (1..#s1) : (@s1[i+1] - @s1[i] < 100)`

However, this does not work because the `/` is interpreted as the beginning of a regex.

Yet, the following would work:

`for (#s1+2) i in (1..#s1) : (@s1[i+1] - @s1[i] < 100) // 2 more than the number of $s1`
`for (#s1*2) i in (1..#s1) : (@s1[i+1] - @s1[i] < 100) // 2x more than the number of $s1`

**Comment by plusvic** [comment]
The division operation in YARA is a backslash (\) like the integer division in C.
