### ISSUE TITLE
yara doesnt builds on osx

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#603]
```
libyara.c:41:10: fatal error: 'openssl/crypto.h' file not found
#include <openssl/crypto.h>
         ^
1 error generated.
```

this kind of errors shouldnt pass the configure step

tested on git and 3.5.0

**Comment by Neo23x0** [comment]
# Option 1
https://yara.readthedocs.io/en/v3.5.0/gettingstarted.html#installing-on-mac-os-x-with-homebrew

# Option 2
Install OpenSSL via Homebrew

```
$ brew update 
$ which openssl  
/usr/bin/openssl 
$ brew install openssl
$ brew link openssl --force 
$ which openssl 
/usr/local/bin/openssl
```

# Option 3
Disable OpenSSL.
./configure --disable-shared --disable-magic --disable-cuckoo --without-crypto

**Comment by trufae** [comment]
Fixed using the 2nd option but setting up the proper CFLAGS/LDFLAGS before running configure in https://github.com/radare/radare2-extras/commit/2c06304977477a94f51a5da092d87cfd754b8ddf

**Comment by trufae** [comment]
this sohuld be checked by configure imho

**Comment by plusvic** [comment]
In cccfce3f9fb3ea45f3562550e7fc78d5a22f2a56 configure.ac was changed to check for header files too.
