### ISSUE TITLE
Feature request: Get file information such as filesize or pe.imphash()

### ISSUE THREAD

**Issue by bestksw** [VirusTotal/yara#605]
Hi, all.

Is there a way to get "filesize" or "pe.imphash()" internal values from YARA results?
Of course, I can extract these values by using third party libraries, but I want to use the values, which makes you not to use additional third party libraries.

If it's impossible, I would like to request a feature that Yara returns the internal values to outside through "meta" section like below.

```
rule test {
	meta:
		i_want_to_know = pe.imphash()
    condition:
        true
}
```

Thanks in advance.

**Comment by hillu** [comment]
* Sangwon Kim:

> Is there a way to get "filesize" or "pe.imphash()" internal values from YARA results?
> Of course, I can extract these values by using third party libraries, but I want to use the values, which makes
> you not to use additional third party libraries.

I think what you are suggesting would be quite useful for debugging.

**Comment by wxsBSD** [comment]
It could be easy enough to make YARA print the result of any function call, but filesize might be a bit harder as that is a keyword in the language.

**Comment by bestksw** [comment]
I think printing the result of function call is enough. The filesize value is easy to get than others.

**Comment by dzzie** [comment]
I added a debug function like this to my build of libyara and it has been really handy for signature writing and understanding the internal values output such as

`
pe.dbg(pe.imphash()) 

for all i in (0 .. pe.number_of_sections -1):(
            pe.dbg( 
                pe.sections[i].name,
                math.entropy(
                    pe.sections[i].raw_data_offset, 
                    pe.sections[i].raw_data_size
                )
            )
        )
`
The current prototypes I am supporting include:
`
  declare_function("dbgw", "s", "i", dbgw); //wide string version for resource names
  declare_function("dbg", "s", "i", dbg);   //string  
  declare_function("dbg", "i", "i", dbgi);      //int 
  declare_function("dbg", "f", "i", dbgf);    //float
  declare_function("dbg", "sf", "i", dbgsf);   //string , float
  declare_function("dbg", "si", "i", dbgsi);    // string , int
  declare_function("dbg", "is", "i", dbgis);   // int , string
  declare_function("dbg", "ii", "i", dbgii);     // int , int 
  declare_function("dbg", "ss", "i", dbgss);  //string , string
`
Sample implementations:
http://sandsprite.com/blogs/index.php?uid=7&pid=478#dbg
