### ISSUE TITLE
when yara matches  one rule  then it returns .it does not  contine to match other rules  how i can do this  .when i use yara   it returns all rules  

### ISSUE THREAD

**Issue by Z000000** [VirusTotal/yara#611]
when yara matches  one rule  then it returns .it does not  contine to match other rules  how  can  i do this  when i use yara   it returns all rules   it wastes much time and cpu

**Comment by wxsBSD** [comment]
Can you give an example set of rules, a file to test against and exactly how you are running YARA?

**Comment by Z000000** [comment]
example      rule  test   string  $1 =“a” 
                      rule test2  string $2="b"


file stream    can match rule test test 1    i want it just return rule test then   break     argv just -r

**Comment by wxsBSD** [comment]
There is the -l argument to yara for this.

**Comment by Z000000** [comment]
but  it matches  less than without it  when i test

**Comment by wxsBSD** [comment]
I'm not sure what you're saying. Can you please provide an exact copy and paste of what is happening, and then point out what you expect to happen?
