### ISSUE TITLE
Wild-Cards

### ISSUE THREAD

**Issue by mattjang96** [VirusTotal/yara#612]
Hello YARA developers. 
I will keep my question short for your convenience: 

I understand that we are allowed to use wild-cards and jumps for hex strings in the cases that we want to include all the possibilities that the '?' wild-card can possess.

My question is, is this possible with strings? That is, can we use wild-card in text strings? For instance, can YARA find a string like "UNION ? SELECT" such that the '?' can represent any string? I have also thought of doing something like: "UNION [-] SELECT" or "UNION [a-z] SELECT" with jumps. Is this possible? If not, is there another way of doing this? Thank you for your time.
- Matt

**Comment by plusvic** [comment]
Hi Matt,

That's not possible with text strings, but you have regular expressions for those cases. You could use /UNION .* SELECT/  or /UNION [a-z] SELECT/. Check this: 

http://yara.readthedocs.io/en/v3.5.0/writingrules.html#regular-expressions
