### ISSUE TITLE
Match Location

### ISSUE THREAD

**Issue by mattjang96** [VirusTotal/yara#613]
Hello YARA developers.
I will keep my question short for your convenience:

When running YARA to check for matches within a file, YARA returns the rule name as well as the file that matched, and if requested with '-s' option, it returns the string that matched as well as the line location within the file. For instance:
RuleName File.txt
0x37c7a7:$str37: UNION

My question is, is there a way that I can use YARA so that it prints not only the line location like 0x37c7a7 above, but also the full line content (i.e. print the entire line in the file that matched)?
It looks something like this in my head:
RuleName File.txt
0x37c7a7:$str37: UNION "(?=.*(UNION.*ALL.*SELECT))"

Thank you for your time.

**Comment by plusvic** [comment]
No, YARA doesn't have the notion of "line", because it wasn't designed with text files in mind. YARA treats all files as a sequence of raw bytes.
