### ISSUE TITLE
Yara match output in the JSON format

### ISSUE THREAD

**Issue by chintanhshah** [VirusTotal/yara#615]
Hey guys , 

Just wanted to quickly check if Yara 3.5.0 or pervious version can produce the matched output in the JSON format . This is required to make the parsing little easier for us. If not , is there anything else I can use to generate JSON output for the matched strings 

Regards
Chintan

**Comment by wxsBSD** [comment]
Is using the python module possible?

**Comment by chintanhshah** [comment]
Ya. that sounds doable ..Thanks ..
