### ISSUE TITLE
Support more than one yara file as input

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#629]
right now yara forces you to use yarac to create a new yara file to use it as input for yara, but yarac doesnt supports precompiled yara files as input, so it is not possible to generate a combined one in case you want to use more than one rule.

So the only option here is to run yara twice. This looks to me like a limitation of the tool, because r2yara supports loading several yara files using the API.

**Comment by plusvic** [comment]
`yara` doesn't force you to use `yarac`, that's optional. `yarac` is used mainly when you want to use the same rules over and over again, so you don't need to compile the rules multiple times. If I understood right you have rules in more than one files and you want to be able to scan a file with all the rules contained in those multiple files, right?

**Comment by trufae** [comment]
Yes, the thing is that you cant use the compiled yara files as sources for yarac or even pass more than one rule to yara. I fixed this by running the tool more than once. But this is far from optimal because of the lack of ortogonality

**Comment by bartblaze** [comment]
@trufae How I solve this is to merge the rules I create into one 'superrule', not sure if that would fit your needs however.

**Comment by radare** [comment]
No that doesn't works for me because i have several groups of yara rules and i want the user to use N of them of choice, so if i do what you want i have the following options:

* distribute the sources (not an option)
* build all NxN combinations of all rules to match user's choice (impractical)
* run yara N times (slow)

In fact r2 yara plugin can do that, i dont see what's the limitation in yara to not do so.

**Comment by plusvic** [comment]
Implemented in 632a6ab2411ab9e296ce05224199f1e3927f487a.

**Comment by radare** [comment]
thanks!

**Comment by cgupta6** [comment]
Is there a way to recursively pick all the rule-files under specified folder? and create a single compiled yara binary file?
