### ISSUE TITLE
No yarad

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#630]
Once yara rules are compiled there's no way to decompile them

**Comment by wxsBSD** [comment]
I looked into doing this a while ago and a lot of it is easily reversed. The biggest problems I ran into are regex and conditions. The regular expressions compile down to special code for the regex implementation in YARA to run, and conditions are special code running on the YARA virtual machine. The rest of it was easy enough to get back into source form.

May I ask why you want this?

**Comment by plusvic** [comment]
I'm curious about this too.

**Comment by trufae** [comment]
It turns out that yarac doesnt verify the source and destination file properly and my wip yara rule got overwritten by the compiled form. Also, there was an error while parsing the stc because of a mistake, so i basicaly lost all the work i did. I didnt filled an issue for that because i had to finish the thing so ill do more testing and report that issue properly. Meanwhile i though that having this tool would helped me.

**Comment by jbgalet** [comment]
A few months ago I wrote this (https://github.com/jbgalet/yaradec). As said before, it has some limitations regarding regex and conditions. Hope this helps.

**Comment by plusvic** [comment]
Recovering the source rules from compiled ones is unfeasible.
