### ISSUE TITLE
YR_TRYCATCH installs an exception handler for entire process, not handling access violations

### ISSUE THREAD

**Issue by rspeaker** [VirusTotal/yara#632]
The YR_TRYCATCH macro defined in libyara/exception.h installs a vectored exception handler using AddVectoredExceptionHandler.  This exception handler applies to the entire process that is hosting the libyara module and not just the thread that is currently using yara to scan a memory buffer.

The exception handler itself is defined like this:

static LONG CALLBACK exception_handler(
    PEXCEPTION_POINTERS ExceptionInfo)
{
  int tidx = yr_get_tidx();

  switch(ExceptionInfo->ExceptionRecord->ExceptionCode)
  {
    case EXCEPTION_IN_PAGE_ERROR:
    case EXCEPTION_ACCESS_VIOLATION:
      if (tidx != -1 && exc_jmp_buf[tidx] != NULL)
        longjmp(*exc_jmp_buf[tidx], 1);

      assert(FALSE);  // We should not reach this point.
  }

  return EXCEPTION_CONTINUE_SEARCH;
}

The tidx variable will be set to -1 whenever yara is not currently scanning a memory buffer.   This means that if some other thread that is not currently processing a yara request triggers an EXCEPTION_IN_PAGE_ERROR or EXCEPTION_ACCESS_VIOLATION, this exception_handler will hit the assert(FALSE) block which in debug mode will result in immediate termination even if there is another exception handler present.

A secondary problem with this is that because tidx will be set during the entirety of yr_rules_scan_mem_blocks, and that function makes callbacks that are external to the library

e.g.:
callback(CALLBACK_MSG_SCAN_FINISHED, NULL, user_data);

This means that any EXCEPTION_IN_PAGE_ERROR/EXCEPTION_ACCESS_VIOLATION exception that is triggered by the *callback* will be silently ignored as well.  This can cause problems if the callback was trying to handle its own exceptions.

Its not immediately obvious to me why a process-wide vectored exception handler is needed as opposed to just a normal try/catch to handle the paging exceptions.

**Comment by plusvic** [comment]
@hillu, I think @rspeaker is right, and this issue applies to Linux too. Any thoughts?

**Comment by hillu** [comment]
@rspeaker Using normal `_try`/`_catch`/`_finally` would have meant breaking building with MinGW. I just took another look at the MSDN documentation on [Structured Exception Handling](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680657.aspx) and the semantics of `AddVectoredExceptionHandler()` and friends regarding multiple threads are not immediately obvious to me.

Regarding callbacks: I think you are correct in that we should restore the previous behavior for the callback duration. However, it is my opinion that if an application sets up custom exception handler in its callback code, it takes the responsibility to restore the previous state at function exit. (This is something that ought to be mentioned in the documentation.)

@plusvic The callback issue exists on Unix, too.

**Comment by rspeaker** [comment]
@hillu and @plusvic  First thank you for your responses and looking into the issue.

I agree the msdn documentation is not very clear but I can confirm that the vectored exception handlers apply to the entire process and not just the thread that added the handler.   The reason I know this is that the problem I ran into that got me looking at this was that some other thread in my process was doing memory mapped I/O and triggering EXCEPTION_IN_PAGE_ERROR exceptions.  Those exceptions were being caught by yara's exception_handler and were hitting the assert(false) in that handler since the "if (tidx != -1 && exc_jmp_buf[tidx] != NULL)" clause returns false given that it wasn't a yara thread that tripped the exception.  In release builds this wasn't a problem but in debug builds the assert(false) aborts the process.  So minimally I think the assert needs to be adjusted since any other thread that raises those two exception codes while the vectored exception handler is active will trip the assert.  This wouldn't happen every time one of those exceptions occurred since the exception handlers were added/removed so t he assert only gets tripped when the other thread happened to trip one of those exceptions while yara was in the middle of scanning a buffer.   Ideally yara wouldn't install any process wide exception handlers and instead just wrap the scan portions in individual exception blocks so that they only apply to the current thread.

With respect to MinGw, it looks like this blog has some useful  macros that can be adapted to mimic the Microsoft compilers _try/_catch logic which might be able to be leveraged if the native _try/_catch can't be used:

http://www.programmingunlimited.net/siteexec/content.cgi?page=mingw-seh

**Comment by hillu** [comment]
@rspeaker Are you using the Microsoft compiler or MinGW? I suppose we could add a simple `__try / __except` while I keep convincing myself that the frame-based exceptions have in fact been fixed in MinGW in the last few months.

**Comment by rspeaker** [comment]
Yes I'm using Visual Studio 2015 to compile

**Comment by hillu** [comment]
Could you give my attempt at fixing this a try? (I don't have a Windows-based build setup to test this with.)

**Comment by rspeaker** [comment]
Sure.  I'm a bit swamped at the moment but will give it a shot sometime later today.

**Comment by rspeaker** [comment]
Changes look good.  I did have to make one small tweak to your code to get it to compile GetExceptionInformation is a function and your code was missing the () to invoke it.  I am no longer seeing the exception_handler get invoked for non-yara exceptions.

Thanks for looking into this.

**Comment by hillu** [comment]
@rspeaker Did you write a small program to test the fix that you can share?

**Comment by rspeaker** [comment]
Sorry for delayed response.   I did not write a test program for this but was using my existing application to verify your changes.

**Comment by hillu** [comment]
can you describe what effects you were looking for in your existing application? Did you provoke a crash while a different thread was executing one of the `yr_rules_scan_*` functions?

**Comment by rspeaker** [comment]
Yes I was triggering exceptions from other threads that had their own exception handler defined while yara was scanning files and with a breakpoint on yara's exception handler to make sure it was not invoked.  Prior to your changes yara's exception handler was being called and it was tripping the assert(false) which killed the process.

**Comment by hillu** [comment]
While `__try/__except` works for MSVC, I haven't gotten `__try1/__except1` to work with MinGW so far, even with recent patches. I think I'll keep using `AddVectoredExceptionHandler` with MinGW but take remove the `assert(false)`...

**Comment by hillu** [comment]
@rspeaker Sorry to bother you again... Would you mind re-testing with the original code, with the `assert(false)` simply removed?

**Comment by rspeaker** [comment]
That was actually how I worked around the issue to begin with so I know that works as a work around.

**Comment by hillu** [comment]
Thank you! Now I know what to do. :-)
