### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by HufkensJeroen** [VirusTotal/yara#649]
On the https://yara.readthedocs.io/en/v3.5.0/gettingstarted.html#compiling-and-installing-yara page are missing some small parts of the commands.

The following commands "sudo apt-get automake libtool make gcc" & "sudo apt-get flex bison" is missing "install" behind the "apt-get".

On the GitHub page https://github.com/VirusTotal/yara/blob/v3.5.0/docs/gettingstarted.rst these commands are already fixed.

Can these fixes be pushed to the read the docs page?

Kind regards,
Jeroen Hufkens & Maxim Vandebroeck
Nynox NV

**Comment by plutec** [comment]
I think it will be fixed in the next release, when he generates the documentation for the new version.

**Comment by plusvic** [comment]
Fixed as the new documentation was published.
