### ISSUE TITLE
assert in yr_arena_coalesce

### ISSUE THREAD

**Issue by HostageBrain** [VirusTotal/yara#654]
in grammar.y in boolean_expression handling code present 

```
        compiler->last_result = yr_parser_emit(yyscanner, OP_AND, &and_addr);

        ERROR_IF(compiler->last_result != ERROR_SUCCESS);

        // Now we know the jump destination, which is the address of the
        // instruction following the AND. Let's fixup the jump address.

        fixup = compiler->fixup_stack_head;

        // We know that the AND opcode and the following one are within the same
        // page, so we can compute the address for the opcode following the AND
        // by simply adding one to its address.

        *(void**)(fixup->address) = (void*)(and_addr + 1);
```

The problem is in case - when OP_AND becames last byte in page. In my case it's:
page->size = 0x20000
page->used = 0x1ffff
and OP_AND placed in offset 0x1fffe
and then 
`*(void**)(fixup->address) = (void*)(and_addr + 1);`
started to point to byte: one after last used byte) 0x1ffff
and when yr_arena_coalesce iterates over relocs, one reloc_target isn't in any page

```
  // Relocate pointers.
  reloc = big_page->reloc_list_head;

  while (reloc != NULL)
  {
    reloc_address = (uint8_t**) (big_page->address + reloc->offset);
    reloc_target = *reloc_address;

    if (reloc_target != NULL)
    {
      page = _yr_arena_page_for_address(arena, reloc_target);
      assert(page != NULL);
      *reloc_address = page->new_address + (reloc_target - page->address);
    }

    reloc = reloc->next;
  }
```

bcs in _yr_arena_page_for_address code looks like:
 ```
 while (page != NULL)
  {
    if ((uint8_t*) address >= page->address &&
        (uint8_t*) address < page->address + page->used)
      return page;
    page = page->next;
  }
```

so, as workaround I've changed:
`(uint8_t*) address < page->address + page->used)`
to
`(uint8_t*) address <= page->address + page->used)`
but it's workaround to yara stop crashes))

Probably must be used somehow yr_arena_write_data from grammar.y->boolean_expression handling code to ensure that 'used' field increased accordingly.

**Comment by plusvic** [comment]
@HostageBrain can you share the rules that are triggering this issue?

At which point are your page in the state `page->size = 0x20000 page->used = 0x1ffff`? It's before or after calling `yr_parser_emit(yyscanner, OP_AND, &and_addr)` ?

**Comment by HostageBrain** [comment]
I'm not sure if I can share rules or not - but anyway you can't compile them bcs I'm using custom module. But I will try to generate rules which are triggered this assert.

`page->size = 0x20000 page->used = 0x1ffff` is after calling `yr_parser_emit(yyscanner, OP_AND, &and_addr)`

**Comment by HostageBrain** [comment]
the problem is: when you are writing `*(void**)(fixup->address) = (void*)(and_addr + 1);` - there is no guarantee any data will be located by this address

**Comment by plusvic** [comment]
If you can enter into our [Gitter channel](https://gitter.im/VirusTotal/yara?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) i can help you to debug the issue.

**Comment by plusvic** [comment]
@HostageBrain check out branch `issue_654` and let me know if it solved the problem.

**Comment by HostageBrain** [comment]
checked. everything works) problem solved)
