### ISSUE TITLE
~new warning in visual studio & one missing file

### ISSUE THREAD

**Issue by HostageBrain** [VirusTotal/yara#655]
**strange warning**
libyara\include\yara/re.h(146): warning C4200: nonstandard extension used : zero-sized array in struct/union
it's about construction:
```
struct RE
{
  uint32_t flags;
  uint8_t code[0]; // <--- it's about this one. what this construction means?)
};
```

**missing file**
In \windows\vs2010 file pe_utils.c isn't included in solution

**Comment by plusvic** [comment]
The warning has been disabled. The VS2010 project has been completely removed from the repository as it has become a maintenance burden.
