### ISSUE TITLE
Support preprocessor for the yara rules

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#656]
You can reuse `spp` if you want, it's a generic preprocessor i wrote many years ago and its now integrated within rasm2 to handle includes, ifdefs, variables, etc...

What i need here is:

* Conditionals depending if yara is compiled with a specific module so i can show a warning or include a different rule.

* The checks for those conditionals may be also defined by the user, so you would be able to do something like yarac -DMY_RULES=1 ...

* This requires a way to use warning() and error() from that yara syntax.

**Comment by plusvic** [comment]
This has been a desired feature for a long time (see #61).

**Comment by radare** [comment]
here's the code of spp https://github.com/radare/spp

feel free to use it and abuse it

**Comment by plusvic** [comment]
Closing is this is a duplicate of #61.
