### ISSUE TITLE
yara - to read the rules from stdin

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#657]

**Comment by hillu** [comment]
On Linux, running `yara /dev/stdin somefile` will do what you want.

**Comment by MatthewHannigan** [comment]
The man page says this works:

`$ cat /foo/bar/rules | yara -r /foo

              Scan all files in the /foo directory and its subdirectories. Rules are read from standard input.`

But it doesn't.  Perhaps support '-' to indicate stdin?

**Comment by hillu** [comment]
`yara -r - /foo` would try to open a file `-` to read the rules from, so that would not work. The manpage is clearly wrong.

**Comment by MatthewHannigan** [comment]
Yes, I know; I was suggesting a change.  Sorry for not being clearer.
Hyphen is a common convention to indicate stdin for a file.
The current man page (3.7.0) does not use hyphen.

**Comment by MatthewHannigan** [comment]
FWIW, you can also do (in bash)
 `yara <(cat malware/*.yar) thisdir`
At least it seems to mostly work.  One file indicated a syntax error.
