### ISSUE TITLE
Allow regex search of pe imports/exports

### ISSUE THREAD

**Issue by rspeaker** [VirusTotal/yara#663]
A challenge I recently ran into while using the yara pe module was that I wanted to classify a binary based on an imported dll name, but the dll in question included a version number as part of its name so was changing with each version of the product.   

As of version 3.6.0 the pe module supports 3 different ways of looking for imported dll's and functions:

imports(dll_name, function_name) 
imports(dll_name) 
imports(dll_name, ordinal) 

In all 3 of those, the dll_name is treated as an exact string match (case insensitive).   This is a request to consider extending the pe module to either support a new variant of the imports function that accepts a regex dll_name / function name, or to expose imported functions as an array rather than a function so that the matching condition can be defined in the yara rule itself rather than in the function.  Example:

for any i in (1..pe.num_imports) pe.import[i].dll_name matches /foo/i

**Comment by plusvic** [comment]
Implemented in #898.
