### ISSUE TITLE
commented line causing syntax errors

### ISSUE THREAD

**Issue by marnao** [VirusTotal/yara#667]
Reproducible on yara 3.6, however yara 3.4 handles this just fine:

$ cat testrule
rule testrule
{
        // }
        strings:
            $ = "abc"
        condition:
            any of them
}

$ ./yara3.4 testrule testrule
testrule testrule

$ ./yara3.6 testrule testrule
testrule(3): error: syntax error, unexpected _HEX_STRING_, expecting '{'

Changing to a block comment fixes the issue:
$ cat testrule
rule testrule
{
        /* } */
        strings:
            $ = "abc"
        condition:
            any of them
}

$ ./yara3.6 testrule testrule
testrule testrule

**Comment by plusvic** [comment]
This is because comments are now allowed inside hex strings (see #455) , and YARA is identifying the sequence `{ // }` as an hex string. Unfortunately this ambiguity doesn't have an easy solution and this is a very uncommon edge-case, so it won't be fixed.

**Comment by marnao** [comment]
makes sense. thanks for the quick response.
