### ISSUE TITLE
how to block empty body

### ISSUE THREAD

**Issue by graz68a** [VirusTotal/yara#677]
Hello

I am using yara rules to check email for spam and malware. How to write a yara rule to 
detect an email with an empty body ?

Thank you
Graziano

**Comment by plusvic** [comment]
Please use the [forum](https://groups.google.com/forum/#!forum/yara-project) for this kind of questions. Let's use this place for bugs, issues and feature requests only.

**Comment by graz68a** [comment]
ok thank you ( and sorry !)
