### ISSUE TITLE
New documentation referring to old values

### ISSUE THREAD

**Issue by srikwit** [VirusTotal/yara#680]
Yara 3.6.1 documentation referring to 3.6.0
Please view [this](https://github.com/VirusTotal/yara/blob/v3.6.1/docs/gettingstarted.rst) 
Also the default document loaded at readthedocs.io is for 3.6.0

**Comment by plusvic** [comment]
That's intended. The documentation won't be updated for revisions, only for major and minor version increases. New revisions only include bug fixes, no new features that require updating the documentation.
