### ISSUE TITLE
I can't install Yara on Windows 

### ISSUE THREAD

**Issue by cobrimusic** [VirusTotal/yara#681]
Hi everyone. I have a problem, I want to work with Yara in Windows 64 bits, I donwloaded the binares, the exe files, I put them in a Folder y my Dekstop and for the terminal I go for them 
`C:\User\MYUSER\Dekstop\Yara` and I wirte only the file name `C:\User\MYUSER\Dekstop\Yara\yara64.exe` and it show me the next message
`yara: wrong number of arguments
usage: yara [OPTION]... RULES_FILE FILE | DIR | PID
Try '--help' for more options` but I can't do anything.  Somebody can help me? What happend?

**Comment by wxsBSD** [comment]
There is no installer for YARA. What you did is actually run the YARA program and are seeing the help message. I think you want to read http://yara.readthedocs.io/en/v3.6.0/gettingstarted.html#running-yara-for-the-first-time for details on how to use YARA.

**Comment by cobrimusic** [comment]
Hi wxsBSD. I've read the docs, but I don't understand how install Yara in Windows, in the Windows part there is a link with the binaries files for Yara in a Zip File and I thought that I need to run for the terminal windows.

**Comment by plusvic** [comment]
@cobrimusic YARA doesn't need to be installed, you just need to copy the EXE files to some place in your system as you already did.  The file`yara64.exe` is YARA's command-line tool, and it receives
two arguments: a file with the yara rules, and the file/folder/process that you want to scan. See this: http://yara.readthedocs.io/en/v3.6.0/commandline.html

For this kind of questions please use the [forum](https://groups.google.com/forum/#!forum/yara-project). Open an issue only for reporting bugs and ask for new features.
