### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by yoni1** [VirusTotal/yara#687]
The website and README.md have an example YARA rule with a meta field called `thread_level`. Maybe I don't understand something, but isn't it supposed to be `threat_level`?

**Comment by plusvic** [comment]
Fixed in af0c74545731d2fecdcb67f4ea338ce9b39bb1db

**Comment by sparecycles** [comment]
@plusvic Can we get this fixed on the `gh-pages` site, too?

https://github.com/VirusTotal/yara/blob/d2d7d20ac7c3c54f8aaf7fc05e974df39aed2e5c/index.html#L52

**Comment by plusvic** [comment]
Done!
