### ISSUE TITLE
Yara - Cuckoo module : Error scanning <file_to_scan>:  internal error: 6

### ISSUE THREAD

**Issue by FluffyAlpaca** [VirusTotal/yara#689]
Hello, 
I wanted to test the Cuckoo module but I encountered this error : 
error scanning ./testJS1: internal error: 6

I launched the following command : 
yara -x cuckoo=./report1.json ./behavior_rule_1 ./testJS1

Report1.json is the report file generated by the Cuckoo sandbox after the analysis of testJS1. 
Behavior_rule only contains one rule : 
        cuckoo.network.http_request(/http:\/\/www\.google\.fr/)
TestJS1 is a file written in javaScript doing various actions for the test purposes.

Do you have any idea where it would come from ? Don't hesitate to tell me if you need any more information.

**Comment by plusvic** [comment]
It looks like the JSON file couldn't be loaded for some reason. Can you provide the JSON report?

**Comment by FluffyAlpaca** [comment]
Yes sure, thank you for your answer. Here it is.
[report1.zip](https://github.com/VirusTotal/yara/files/1104678/report1.zip)

**Comment by FluffyAlpaca** [comment]
I thought that my problem was perhaps because my file is too heavy... Or is it a normal sized report ? How can I get more information about this error ?

**Comment by plusvic** [comment]
I found the root cause of this issue. The error is caused by the null characters embedded in the string at line 7254. I've fixed it with this commit a13cf411c1db7858a1886c6d67d0b058891e05f2

**Comment by FluffyAlpaca** [comment]
Thank you, it worked !
