### ISSUE TITLE
Tags starting with numbers causes syntax error

### ISSUE THREAD

**Issue by instacyber** [VirusTotal/yara#690]
Creating rules with tags that start with a numerical value fails YARA syntax checks and causes an error. While not common, there are situations where this functionality would be useful.

An example rule:

```
rule tag_number_test : malware 123rat
{
    strings:
        $ = "foo"

    condition:
        all of them
}
```

Running this rule results in the following error:

> $ yara -r test.yara samples/
> test.yara(1): error: syntax error, unexpected _NUMBER_, expecting '{'

Confirmed that this error occurs in YARA 1.7.2, 3.4, 3.5.

**Comment by wxsBSD** [comment]
This is intentional. Tags must be valid identifiers and identifiers can not start with numbers. They follow the same rules for identifiers in C.

**Comment by plusvic** [comment]
As @wxsBSD said this is intentional. Tokens starting with digits are treated as numbers, if we accept identifiers starting with numbers we can not distinguish if 100KB is an identifier or a number (like in `filesize > 100KB`)
