### ISSUE TITLE
yara-python 3.6.2 hangs at _yr_get_next_block in proc.c

### ISSUE THREAD

**Issue by fyrestone** [VirusTotal/yara#699]
I debug the libyara, found this:
![image](https://user-images.githubusercontent.com/6308809/27785367-f4e8edc2-600f-11e7-8787-755d5a9e786f.png)
`address = (uint8_t*) address + mbi.RegionSize;`
is equal to
`address -= 1`
and call GetLastError() got:
GetLastError()
299
I checked the VirtualQueryEx return value is equal to sizeof(mbi)

**Comment by fyrestone** [comment]
It seems that x32 libyara scan a x64 process will run into dead loop, the address is overflowed.

**Comment by plusvic** [comment]
This should be fixed with c16c7d90cd31eb7fe73dd7f95bd2518da5c84c89. Any confirmation will be welcomed.
