### ISSUE TITLE
Yara API:  Openned file was not closed in some case

### ISSUE THREAD

**Issue by baiweiguo** [VirusTotal/yara#706]
When I use yara api such as yr_rules_scan_file, I found handle leak . Some  case like compiling in 32-bit machine but using in 64-bit mashine without using -D_FILE_OFFSET_BITS=64, fstat will be failed. At this time, the scanned file was opened, but return value is not ERROR_SUCCESS . However，when close file fd, it needs return value is ERROR_SUCCESS ，as follows:
![image](https://user-images.githubusercontent.com/3157054/28195928-e68be162-687f-11e7-9c87-9f2e010bcb88.png)

![image](https://user-images.githubusercontent.com/3157054/28195958-1b97ca7e-6880-11e7-9487-243f1f87709a.png)

**Comment by plusvic** [comment]
Fixed in 9e7390c5756f9af91c1df9f007a24317eddd2b80
