### ISSUE TITLE
Use tags in rule conditions

### ISSUE THREAD

**Issue by plusvic** [VirusTotal/yara#71]
_From [golgotr...@gmail.com](https://code.google.com/u/114188526611906850564/) on January 29, 2013 11:44:46_

I think that It will be very useful if we can reference rule tags in the condition of the rule like in this example:

rule banker_1 : malware
{
  strings:
   $a = "bankofamerica.com" 
  condition:
   $a and 2 of :banker: and 2 of :suspicious: and :packers:
}

To hit banker_1 first need to hit 2 rules with banker tag and one rule with suspicious tag and one from packers.

rule Trojan_Agent : malware
{
  condition:
   4 of :suspicious:
}

I think it will be handy to discover unknow malware

_Original issue: http://code.google.com/p/yara-project/issues/detail?id=71_

**Comment by dkindlund** [comment]
Developing a full-fledged rules engine in YARA may cause significant performance/resource issues, long term.  I'd recommend keeping YARA fast/agile.  There are plenty of ways to achieve this type of logic as a post-processing operation (after YARA results are provided).
