### ISSUE TITLE
[yarac] Drive letter considered as namespace

### ISSUE THREAD

**Issue by bdr00** [VirusTotal/yara#718]
Passing absolute paths on windows causes yara to omit the drive letter from the path and use it as a namespace, which could also result in using a wrong path:
![image](https://user-images.githubusercontent.com/24456233/28872388-9dc6ee6a-7791-11e7-9995-d136fb7211ef.png)

Possible solution could be to restrict namespace length to a minimum of 2 letters and check that whenever a [colon is found](https://github.com/VirusTotal/yara/blob/v3.6.3/yarac.c#L249).

**Comment by plusvic** [comment]
Fixed in 632a6ab2411ab9e296ce05224199f1e3927f487a
