### ISSUE TITLE
Assertion `branch_size + jmp_size < INT16_MAX' failed

### ISSUE THREAD

**Issue by fumfel** [VirusTotal/yara#725]
**Assertion `branch_size + jmp_size < INT16_MAX' failed**

Tested on HEAD: 651976f3750c8dc0b576e8aa1258ad9e92584328

[Faulting rule](https://github.com/VirusTotal/yara/files/1242156/yara_assert_fail.txt)

To reproduce: `yara yara_assert_fail /usr/bin/strings`

Context:

``yara: re.c:1068: int _yr_re_emit(RE_EMIT_CONTEXT *, RE_NODE *, int, uint8_t **, size_t *): Assertion `branch_size + jmp_size < INT16_MAX' failed.
Aborted``

**Comment by plusvic** [comment]
Fixed in cb5cb2885e8ecec7c704a3573aee9dbb2b6fc3af
