### ISSUE TITLE
Imports incorrectly identified

### ISSUE THREAD

**Issue by securitykitten** [VirusTotal/yara#730]
When looking at a binary with invalid imports (`258dddb24c37220704b41d4f488b38d7f710896ab122a7a12a2a5cda9c3d0794`) the number of imports is incorrectly calculated.

Version of yara
```
$ yara -v
3.6.3
```

Running yara with the -D option to see the number of imports (output snipped for readibility), returns that the executable contains only 1 import.
```
$ yara -D foo.yar 258dddb24c37220704b41d4f488b38d7f710896ab122a7a12a2a5cda9c3d0794
pe
	number_of_signatures = 0
	signatures
	number_of_resources = 1
	resources
...snip...
	number_of_exports = UNDEFINED
	number_of_imports = 1
...snip...
```

When looking up the executable in Virustotal, it was able to identify that it contained invalid imports and calls out several of the kernel32.dll functions (copy and pasted from there)
```
*invalid*
UpdateWindow
KERNEL32.dll
GetACP
lstrcpynW
GetSystemInfo
GlobalSize
CreateProcessW
FindClose
GetProcAddress
VirtualAlloc
LoadLibraryA
```

Thanks!

**Comment by wxsBSD** [comment]
I checked into this and it's parsing it right. All the things that virustotal reports as functions from KERNEL32.DLL are actually parsed, as are all the invalid things. :)

Here's proof:

```
wxs@wxs-mbp yara % cat foo.yara
import "pe"

rule a {
  condition:
    pe.imports("KERNEL32.DLL", "GetACP") and
    pe.imports("KERNEL32.DLL", "lstrcpynW") and
    pe.imports("KERNEL32.DLL", "GetSystemInfo") and
    pe.imports("KERNEL32.DLL", "GlobalSize") and
    pe.imports("KERNEL32.DLL", "CreateProcessW") and
    pe.imports("KERNEL32.DLL", "FindClose") and
    pe.imports("KERNEL32.DLL", "GetProcAddress") and
    pe.imports("KERNEL32.DLL", "VirtualAlloc") and
    pe.imports("KERNEL32.DLL", "LoadLibraryA")
}
wxs@wxs-mbp yara % ./yara foo.yara ~/Desktop/invalid_imports
a /Users/wxs/Desktop/invalid_imports
wxs@wxs-mbp yara %
```

What's misleading here is that ```number_of_imports``` is actually the number of DLLs imported, not the total number of functions. One could make an argument for adding a ```number_of_imported_functions``` though we may want to consider being slightly more strict in what we consider valid, because the number we would report would be higher than VT.

**Comment by securitykitten** [comment]
Thanks for the information @wxsBSD it sounds like everything is working as intended.  

I like your idea of `number_of_imported_functions`.  

Given the current implementation of imports and the PE module I'm not sure the best way to search for the mangled names in the import table, but I suppose that is a conversation for a different day.

Thanks again.

**Comment by wxsBSD** [comment]
It's untested but you could try ```pe.imports("\x41\x41\x41")``` or whatever the bytes are which make up the DLL you're intersted in. I suspect it's not going to give you much value though.
