### ISSUE TITLE
Command to list the modules installed

### ISSUE THREAD

**Issue by plutec** [VirusTotal/yara#737]
In order to see the modules compiled with yara, we can include a command like:
```
$yara -xl
pe
elf
cuckoo
math
[...]
```

**Comment by silascutler** [comment]
I'd like to see this also

**Comment by elhoim** [comment]
+1

**Comment by geekscrapy** [comment]
Came here to leave a +1!
This is really important with appliance based tech which bundles YARA, _sometimes_ developers miss out this information in the documentation...
