### ISSUE TITLE
Positives is no longer supported in yara

### ISSUE THREAD

**Issue by mingwayzhang** [VirusTotal/yara#738]
Dear Author of Yara,

I recently used VirusTotal hunting rules and find that several fields including "positives" are no longer supported but still shown as examples in [malware hunting rules](https://www.virustotal.com/intelligence/help/malware-hunting/#file-types). Would you please specify how to filter files using detection rate in yara? Thanks.

**Comment by plusvic** [comment]
Some variables like "positives", "file_type", "signatures" and so on are supported in VirusTotal's Malware Hunting, but not in VirusTotal's Retrohunt. Also keep in mind that those variables are specific to Malware Hunting, not YARA in general.
