### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by kevien** [VirusTotal/yara#742]
what's ide you used? CLion?

**Comment by plusvic** [comment]
For general questions like this one please use the forum: https://groups.google.com/forum/#!forum/yara-project

If your question is which IDE do I use for developing YARA the answer is none. I use a code editor, I started with Sublime Text, tried Atom for a while, and now I'm using Visual Studio Code. I build YARA with a plain `make` from the command line, and sometimes use XCode for debugging.

**Comment by kevien** [comment]
thanks
