### ISSUE TITLE
rules test crashes on AIX

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#762]
Hi,

I am working on getting YARA 3.6.3 to run on an AIX/POWER machine. Things are mostly looking good, so far I found just one crashing test in `test-rules.c:1178`.
```
assert_regexp_syntax_error("\\x");
```
I can't use a debugger right now, so I had to resort to printf debugging.

Here's some system info:
```
$ gcc -dumpmachine
powerpc-ibm-aix6.1.1.0
$ gcc --version
gcc (GCC) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ flex --version
flex 2.5.37
$ bison --version
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by plusvic** [comment]
This could be related to #695. I did some experimentation with an ARM CPU and the same test crashed because of a bug in flex (see: https://github.com/VirusTotal/yara/commit/4d3d586adf1ae7856dda4186d812243e0b401dc0). After upgrading to flex 2.6.4 the problem disappeared.

**Comment by hillu** [comment]
Spot on! 4d3d586 builds and tests fine on the AIX box, the previous commit crashes `test-rules`.

**Comment by plusvic** [comment]
Btw, if you can test the latest version in `master` in AIX/PowerPC it would be great. I want to release version 3.7.0 soon, and it would be great if we confirm that it runs in as many platforms as possible.

**Comment by hillu** [comment]
All tests run fine. `./configure --disable-shared`, with OpenSSL installed.

When do you plan to release 3.7?

**Comment by plusvic** [comment]
By mid November I think.
