### ISSUE TITLE
unknown module "androguard" when I use yara in python

### ISSUE THREAD

**Issue by LianlianMao** [VirusTotal/yara#764]
When I use yara in python, I meet the yara syntaxError that module "androguard" not found.I can fix it in the command line because I can re-compile yara through import androguard.c and add it to the module list,but I am bewildered in python.Thanks for your help.

**Comment by plusvic** [comment]
What's your operating system? Windows? Linux?

**Comment by LianlianMao** [comment]
Mac OS X.

**Comment by plusvic** [comment]
If you are able to build and install yara with androguard module nebaled then you can use `sudo python setup.py build --dynamic-linking` for linking yara-python against the library you just built.
