### ISSUE TITLE
Segmentation fault in "test-rules" test on ppc64le architecture

### ISSUE THREAD

**Issue by rgdoliveira** [VirusTotal/yara#771]
I built Yara 3.6.3 in an Ubuntu 16.04 and Alpine 3.6.2, both ppc64le architecture, and a test is failing with a segmentation fault .

I built it with:
$ ./configure --prefix=/usr --with-crypto --enable-magic
$ make
$ make check
([See the package in Alpine](https://github.com/alpinelinux/aports/blob/master/testing/yara/APKBUILD))

The test output is the following:

PASS: test-alignment
./test-driver: line 107: 18562 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: test-rules
PASS: test-pe
PASS: test-elf
PASS: test-version
PASS: test-exception

File "test-suite.log" doesn't provide useful information so I did a quickly debug and figured out that the test that is failing is:
assert_regexp_syntax_error("\\\x");   
It is from file: ./tests/test-rules.c and function "test_re()"

**Comment by hillu** [comment]
This looks just like #762 and #695. Does upgrading flex to 2.6.4 and regenerating the lexer help?

**Comment by rgdoliveira** [comment]
Flex wasn't listed in Alpine make depends of Yara package, so I added it there but it doesn't solve the problem. 
Alpine currently has flex 2.6.4, so it should work as it is described in #762 and #695

**Comment by plusvic** [comment]
Installing flex 2.6.4 is not enough, you must delete `libyara/re_lexer.c` and re-build. Did you try that?

**Comment by hillu** [comment]
@rgdoliveira [Here's](http://sources.debian.net/src/yara/3.6.3%2Bdfsg-1/debian/rules/) the relevant file for the Debian package. Lexer and parser files are deleted before building, so that they are rebuilt using current bison and flex.

**Comment by rgdoliveira** [comment]
Thanks @plusvic and @hillu , this solved the build problem in Alpine.
I'm going to close this issue.
