### ISSUE TITLE
Crash in yr_object_set_integer

### ISSUE THREAD

**Issue by Woniuke** [VirusTotal/yara#774]
Hello！I have find crash in yr_object_set_integer, there is stack trace:
![2](https://user-images.githubusercontent.com/8768826/32091354-5c03bd7c-bb26-11e7-8a8c-2c64fca3abd6.jpeg)
it’s not safe to use assert, call _yr_object_lookup with OBJECT_CREATE possible return nullptr, when yr_malloc failed in yr_object_structure_set_member. Stack trace:
![3](https://user-images.githubusercontent.com/8768826/32091361-65a2dbc4-bb26-11e7-8dd8-bf5b31c27687.jpeg)

**Comment by plusvic** [comment]
You are right, the assert can trigger in a low memory condition. Is that what you mean?

**Comment by Woniuke** [comment]
@plusvic Whether you should consider returning ERROR_INSUFFICIENT_MEMORY to replace assert, because the probability of encountering insufficient memory when scanning a large number of samples is high and assert will cause the process to coredump

**Comment by Woniuke** [comment]
@plusvic GoodJob！Thx~
