### ISSUE TITLE
Implement process scanning on AIX

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#777]
There is a `proc` filesystem, but the layout differs from the Linux implementation, see https://www.ibm.com/support/knowledgecenter/ssw_aix_72/com.ibm.aix.files/proc.htm for details.

I'd be happy to give it a try, but I'm not sure for how long I'll keep access to an AIX virtual machine.

**Comment by plusvic** [comment]
In that case I wouldn't bother about implementing process scanning for AIX. If someone actually needs this feature and will be able to support it in the long term I would include it, but if not, I don't think the demand for AIX is high enough to be worth the effort.
