### ISSUE TITLE
Re-implement process scanning on BSDs

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#778]
So far, the process scanning feature on BSDs depends on a Linux-compatible `procfs` being available. OpenBSD removed `procfs` in the [5.7 release](https://www.openbsd.org/plus57.html), two years ago. FreeBSD has deprecated it -- a default install of FreeBSD 11.0 still contains support, but `/proc` is not mounted by default. I haven't looked in detail at NetBSD and Dragonfly BSD yet.

Copying memory regions from other processes' memory seems to be possible through the `PT_IO` request to `ptrace()` which is much more efficient than `PTRACE_PEEK*`. Reading the memory works differently: On FreeBSD, there is a `PT_VM_ENTRY` request for `ptrace`, on NetBSD and OpenBSD there are slightly different `sysctl` functions that can be used. I haven't found anything for DragonFly BSD yet.

**Comment by krytarowski** [comment]
What are you going to achieve? Get something comparable to `/proc/pid/maps`? Or copy the content of process mapped memory?

**Comment by krytarowski** [comment]
On NetBSD if you want to get information comparable to `/proc/pid/maps` you can call `kinfo_getvmmap(3)` from libutil or call directly the sysctl(2) calls that are under the neath. If you need to read process memory, you need `ptrace`(2).

**Comment by plusvic** [comment]
Done in #788
