### ISSUE TITLE
Incremental compilation

### ISSUE THREAD

**Issue by Tigzy** [VirusTotal/yara#789]
Hello, 
New feature request: 
Could it be possible to make an incremental compilation? 

Like you have ruleset1, ruleset2, produce a ruleset2.diff.bin ?
Then, ability to load both ruleset1.bin /ruleset2.diff.bin to obtain ruleset2.bin

**Comment by plusvic** [comment]
That won't be possible, the internal structure of compiled rules are not designed with that idea in mind and it would be fairly complicated to do so.

**Comment by Tigzy** [comment]
ok, thanks for taking the time to answer :)
