### ISSUE TITLE
Checksum generation in pe.c version 3.7.0

### ISSUE THREAD

**Issue by bradanfearna** [VirusTotal/yara#797]
Hi,
I think the generate_checksum may be wrong, I got the right checksum when i changed line 2038 in pe.c:
  for (i = 0; i <= pe->data_size / 4; i++)  
to (removing the /4):
  for (i = 0; i <= pe->data_size ; i++)

and also the following line 2046:
if (4 * i + 4 < pe->data_size)   
to (adding the equals)
if (4 * i + 4 <= pe->data_size)

**Comment by plusvic** [comment]
If you do that you will have an out-of-bounds access in line 2048. Can you explain more about your case? Can you share the file for which the checksum is calculated wrongly?

**Comment by bradanfearna** [comment]
Hi,
You're right that is not a proper fix. 
I replicated the issue however, the following file is consent.exe in the windows directory:

Sha1 - d90de430940f1afd9d9a26a1b14b67289e0b095c
Dumpbin /headers tells me the checksum is 0x1e51f
Using the python pefile library to generate the checksum also returns 0x1e51f
However in Yara the generated checksum is 0x1e435

**Comment by plusvic** [comment]
Fixed in 21d82ff7ddaf7c01e9b3a7364f4cb3820870bcb2

**Comment by bradanfearna** [comment]
Great! Thanks for fixing it so quickly.
