### ISSUE TITLE
Regex Vertical Whitespace Possibly Not Working

### ISSUE THREAD

**Issue by 8u1a** [VirusTotal/yara#816]
Greetings,

There may be an issue with strings using regular expressions containing vertical whitespace special characters.  I would expect the rule below to *not* match the sample file.

$ xxd test.txt
00000000: 6669 7273 740a 7365 636f 6e64 0a         first.second.

$ cat test.yar
rule test_vert{

	strings:
		$s1 = /first[^\v]{0,8}second/i

	condition:
		all of them

}

$ yara -v
3.7.1

$ yara test.yar test.txt
test_vert test.txt

**Comment by wxsBSD** [comment]
Why would you expect it to not match? \v is not a recognized character class in YARA.

**Comment by plusvic** [comment]
Implementing \v is relatively easy, but as @wxsBSD said the regexp would match the file anyways. The character in between "first" and "second" is a line-feed character, so it should match [^\v] as _it is not_ a vertical tab.

**Comment by 8u1a** [comment]
Thanks Wesley, Victor.  Fair enough, I see \v is not a supported escape sequence according to docs.  If it were though, I'd expect it to match vertical tab, carriage return, line feed, and others typically grouped in this set (by PCRE for example).  It's easy enough to just use byte sequences, e.g. x0D without \v.  I guess I expected it to fail otherwise as invalid syntax, but it seems it just matches the character v.

**Comment by plusvic** [comment]
That seems to be the semantic of \v as implemented by Perl, but not all regexp engines treat \v in the same form. In Python for example \v only matches the 0x0B character. According to [this](https://www.regular-expressions.info/shorthand.html) there no agreement on the meaning of \v.

**Comment by 8u1a** [comment]
Makes sense.  FWIW I no longer think this is an issue, which is where I think you guys are at.
