### ISSUE TITLE
Windows Binaries Download link from Documentation Broken

### ISSUE THREAD

**Issue by forgottentq** [VirusTotal/yara#841]
Hello!  I was trying to download the Yara windows binaries and the link inside the getting started documentation is a 404.   The link is: https://b161268c3bf5a87bc67309e7c870820f5f39f672.googledrive.com/host/0BznOMqZ9f3VUek8yN3VvSGdhRFU/   

Thanks in advance!

**Comment by plusvic** [comment]
The link has been updated in the documentation for the latest version.

**Comment by CmdrBurrito** [comment]
Hi, hate to bother you, but the link to download the Yara windows binaries appears to be broken again (yields 404 error).  The link is:
https://b161268c3bf5a87bc67309e7c870820f5f39f672.googledrive.com/host/0BznOMqZ9f3VUek8yN3VvSGdhRFU/

Regards!
