### ISSUE TITLE
yara rule multiple condition 

### ISSUE THREAD

**Issue by H1-N1** [VirusTotal/yara#844]
hello!
i'm facing a prob in writing multiple condition check
in this exemple i'm checking some string in plain text file to black list it
but if i add the last conditions it spoil all scan
 files :
---------------------------------------------------------------------------------------
                               BITCOIN PRIVATE KEYS
        
    How to get:  
    Step 1 - Send 0.0005 BTC to this bitcoin address: 1ionChGCZkjP4xSSYqn6HcQEkHBpJtv6W
    Step 2 - Email to this address alt.qt-btc@yopmail.com.
	Step 3 - Receive the private keys
 
19KJZ5aqWnrrCaNAS5Pbd4uknPFBxjALRt
1Jz6HEKNJpYjXAYRLn49QUUUrizL5qGxjM
18vo26nEeDt1Tw17CuWap3F5rKJjBXSMmL`

rule :
rule blacklist
{
    strings:
	    $data_format = "#EXTINF" nocase
		$data_format1 = /\b[\w\.-]+@[\w\.-]+\.\w+\b/
		//$data_format2 = /^([\w.`~!@#$%&*_-]{0,30})[: |-]+([\w\.\`\~\!\@\#\$\%\&\*\_\-\^\*]{4,32})([ ]+)?/
        $keyword1 = "--app-name=LeagueClient" nocase // League of Legends Debug Log
        $keyword2 = "common.application_name: LeagueClient" // League of Legends Debug Log
        $keyword3 = "Minecraft Version:"
		$keyword4 = "---- Minecraft Crash Report ----"
		$keyword5 = "Server version"
		$keyword6 = "server configuration"
		$keyword7 = /([\w\d\$\-\>\<\(\)\[\]\{\}]*[ \t]?)([\w\d\$\-\>\<\(\)\[\]\{\}]*)[ \t]?=[ \t]?([\.\w\d\$\-\>\<\(\)\"\'\[\]\{\}\,]+)[\;]?[ ]*[\n\r]?/
		$keyword8 = "minecraft.jar"
		$keyword9 = /(<.+?>)/	
    condition:
    (any of ($keyword*) and not any of ($data_format*)) or (not any of ($data_format*)) or #$data_format < 10 
  
}

**Comment by plusvic** [comment]
It's `#data_format < 10` not `#$data_format < 10`. Notice that `$` is replaced with `#`.

**Comment by H1-N1** [comment]
man have you tray it befor closing this issue ???
i now its # without $ it just a mistak in writing hear .....
pleas reopen the issue
thx

**Comment by H1-N1** [comment]
this is resulte of  the scan 

0x146:$data_format1: alt.qt-btc@yopmail.com
0x149:$data_format1: .qt-btc@yopmail.com
0x14a:$data_format1: qt-btc@yopmail.com
0x14c:$data_format1: -btc@yopmail.com
0x14d:$data_format1: btc@yopmail.com
0x0:$data_format2: https://pastebin.com/PLpKtX9V
0xf7:$data_format2: address: 1ionChGCZkjP4xSSYqn6HcQEkHBpJtv6W

**Comment by plusvic** [comment]
Can you explain a bit more about what's the issue? What result do you expect?

**Comment by H1-N1** [comment]
thx for your replay 
the resule shoulde be null 
becose none of thos rule has bean found 
i have the same issue with other rule  when i add the 3 condition (first ) or (two) or (this spoil all scan )
im using the yara for windos by the way
thx

**Comment by plusvic** [comment]
The rule matches your file, the clause `#data_format < 10` is true because the number of matches for `$data_format` is zero, as the string "#EXTINF" doesn't appear in your file.

**Comment by H1-N1** [comment]
yes ofcorse..!!  my bad 
can i ask you : 
is there a trick to privilege a condition on other conditions??
and also if  wee can recheck the result of the condition !!
