### ISSUE TITLE
using options like -r with the match function

### ISSUE THREAD

**Issue by sumitaby1** [VirusTotal/yara#847]
I had a requirement for using the  Yara [options] through python with the match() and compile() function. I searched a lot for it but couldn't find anything useful. Is there any way to use them through python with the match() and compile() function?

**Comment by plusvic** [comment]
The -r option is for scanning directories recursively, but in `yara-python` you can only scan individual files. If you want to scan a directory using `yara-python` you must traverse the directories yourself. You can use [os.walk()](https://docs.python.org/2/library/os.html#os.walk) for that.
