### ISSUE TITLE
ptrace+waitpid for Linux memory scan can lead to stopped services

### ISSUE THREAD

**Issue by cheezypoofs** [VirusTotal/yara#861]
During the same investigation for #860, we found a more serious problem. There are cases where _yr_process_attach can succeed at `ptrace` but fail `waitpid`. The waitpid failure goes through some best effort cleanup, which includes a call to ptrace with PTRACE_DETACH. Our findings, however, show that the SIGSTOP from the attach call is causing the target process to stop but the best-effort cleanup is not always causing the SIGCONT to either be sent or recevied or perhaps just handled. Our speculation is that since waitpid did not complete, the timing is not reliable for the sending of the SIGCONT (if it's being sent) so the target process can be left in a STOPPED state.

The repro for this is very tricky and not well understood. It seems to be related to having, for example an sftp session open and the closing it at some point during the scan of many processes. In the case we were investigating, the sshd process was often in a STOPPED state after _yr_process_attach returned ERROR_COULD_NOT_ATTACH_TO_PROCESS through the waitpid error/cleanup path (we verified it was always going through this block in the failure scenario). It may have also be related to a highly oversubscribed virtual environment with high contention and low allocations per guest. Uncertain what the real sequence of events is, but we were able to get one guest to do it quite reliably. This guest was a Centos7.3 64-bit OS.

Related point of info is we put an explicit `kill( pid, SIGCONT )` after the detach call just to see if it would help. This is probably very unreliable since waitpid failed and the detach call may have already sent its own SIGCONT (we did not verify the signal was being sent or not) but in our experiments this always alleviated the problem. Again, I fear this as a real fix would be a hack, but perhaps since it's best-effort maybe it's ok?

The severity of this problem is actually pretty high as the target can be left in a STOPPED. In one case we saw pid 1 in this state, but most of the time it was sshd that manifested with the problem. Possible other processes were too and we didn't notice during our investigation.

**Comment by cheezypoofs** [comment]
There is an interesting related discussion in #622 about how SIGSTOP is undesirable. No conclusion derived in the discussion, but it was once brought up.

**Comment by cheezypoofs** [comment]
Maybe #989 now solves this?

**Comment by plusvic** [comment]
Yes, I think this issue can be closed.
