### ISSUE TITLE
Feature Request: Add more fields from PE headers

### ISSUE THREAD

**Issue by ladislav-zezula** [VirusTotal/yara#868]
Current PE module already contains a lot of fields that are in the PE headers. But not all of them. Those are usually very rarely used, which is why these fields are chosen by file infectors as infected markers.

Sample: e1955fddea0da2bd227d023165ebf3df4bef1cc683f972ddee9c618f6c6a761b
This sample is an EXE infected by Win32/Parite.

Fields used: 
```
  sections[5].PointerToRelocations = 0xFF3C4484
  sections[5].PointerToLinenumbers = 0x00EFED5D
```

These fields are good for testing whether the file is infected by Win32/Parite, yet it's quite hard to do it in YARA, unless you write something like:

```
condition:
    uint32((uint32(0x3C) + 0x04 + 0x14 + uint16(uint32(0x3C)+0x14) + (pe.number_of_sections-1)*0x28) + 0x18) != 0
```

I prepare a pull request to make more fields in PE module available for these purposes.

**Comment by r0ny123** [comment]
@plusvic, this can be closed.
