### ISSUE TITLE
yr_compiler_add_fd failes on parsing rules file with comments which size is greater than 1026 bytes

### ISSUE THREAD

**Issue by maliysergey** [VirusTotal/yara#884]
I was trying to add rules to compiler using yr_compiler_add_fd on Windows, but get such error:

> Error: syntax error, unexpected _IDENTIFIER_ in file 

Rules file is attached to issue - [error_rule.txt](https://github.com/VirusTotal/yara/files/2058848/error_rule.txt)

If delete comment letters to reduce file size to be less than 1024 bytes then error doesn't appear. Also if move comment to the end of file then error doesn't appear.

If use yr_compiler_add_file to add this rules then error doesn't appear.

**Comment by plusvic** [comment]
Fixed by #887
