### ISSUE TITLE
Proposal: Mac OSX Mach-O binary module detection for Yara

### ISSUE THREAD

**Issue by unixfreaxjp** [VirusTotal/yara#889]
Hello. The raise of the threat in Mac OSX vector is daring me to make this request.

I am proposing to add` Mac OSX` binary detection module for [Yara modules](http://yara.readthedocs.io/en/v3.7.1/modules.html) that may help others to avoid writing over and over the `Mach-O` detection. This can improve existing rule's detection in repositories and can help them who don't have much experience in OSX binaries, to produce the rule faster.

The best 32bit bytes signature I am using so far that can fit to the filtration purpose, based on some OSX threat rules I made is as per below, it does the work well, feel free to copy if you want to make `OSX .yar` file.

```asm
private rule is__osx
{
 meta:
    date = "2018-02-12"
    author = "@unixfreaxjp"
 condition:
    uint32(0) == 0xfeedface     or uint32(0) == 0xcafebabe
    or uint32(0) == 0xbebafeca  or uint32(0) == 0xcefaedfe
    or uint32(0) == 0xfeedfacf  or uint32(0) == 0xcffaedfe
}
```

Added above magic(s), the thorough implementation for the Mach-O module on Yara can be applied and Mach-O itself is similar [in some respect to the ELF module reference](http://yara.readthedocs.io/en/v3.7.1/modules/elf.html#reference), since the both basic structure is identical in many ways, so this implementation can be applicable in `entry points`, `sections` and `segments `on Mach-O  (multiple) binary headers. With possible adjustment in `type`, `FLAGs`, etc. What has to be put in note is in the _dynamic-linking_, _symbols implementation_ which is having OSX specifics.

Will be more than happy to contribute more help if this proposal is receiving good feedback. Thank you.

**Comment by plusvic** [comment]
Have you checked this: https://github.com/VirusTotal/yara/blob/master/libyara/modules/macho.c?

**Comment by unixfreaxjp** [comment]
I missed it, will check. Canceling this proposal.
