### ISSUE TITLE
regular expression can't match more than about 4000 characters

### ISSUE THREAD

**Issue by sgact** [VirusTotal/yara#895]
I find that the regular expression defined in [strings] cannot match more than about 4000 words,for example:
```
rule test{
    strings:
        $s = /start[\\s\\S]*end/
    condition:
        $s
}

```
This simple rule cannot match the following string：
```
start..[more than 4k characters]..end
```

However, it can match the following characters

```
start..[less than 4k characters]..end
```

How can I increase this word limit?
（translated by Google. XD）

**Comment by plusvic** [comment]
That's controlled with the `RE_SCAN_LIMIT` macro in `libyara/include/yara/limits.h`. You can increase that value and rebuild.

**Comment by sgact** [comment]
Thank you (๑•̀ㅂ•́)و✧
