### ISSUE TITLE
Double call to destroy_node_if() in re_grammar.y

### ISSUE THREAD

**Issue by fishilico** [VirusTotal/yara#907]
Hello,
libyara/re_grammar.y contains the following code twice (https://github.com/VirusTotal/yara/blob/v3.7.1/libyara/re_grammar.y#L249-L261 and https://github.com/VirusTotal/yara/blob/v3.7.1/libyara/re_grammar.y#L272-L284):
```c
        if ($1->type == RE_NODE_ANY)
        {
          $$ = yr_re_node_create(RE_NODE_RANGE_ANY, NULL, NULL);
          destroy_node_if(TRUE, $1);
        }
        else
        {
          mark_as_not_fast_regexp();
          $$ = yr_re_node_create(RE_NODE_RANGE, $1, NULL);
          destroy_node_if($$ == NULL, $1);
        }

        destroy_node_if($$ == NULL, $1);
```

If ``yr_re_node_create()`` fails to allocate its memory, ``$$`` is ``NULL`` and ``$1`` seems to be destroyed twice (with ``destroy_node_if()``). There seems to be a double-free bug (which is quite impossible to trigger if it is the case). Is this a bug or did I misread the code?
Thanks

**Comment by plusvic** [comment]
You are correct. I've fixed the bug.
