### ISSUE TITLE
yara/grammar.y fails to check for a failed allocation of fixup entry

### ISSUE THREAD

**Issue by fishilico** [VirusTotal/yara#910]
Hi,
``yara/grammar.y`` currently contains twice the following code (https://github.com/VirusTotal/yara/blob/v3.7.1/libyara/grammar.y#L1288-L1298 and https://github.com/VirusTotal/yara/blob/v3.7.1/libyara/grammar.y#L1343-L1350):
```
        // create a fixup entry for the jump and push it in the stack
        fixup = (YR_FIXUP*) yr_malloc(sizeof(YR_FIXUP));

        if (fixup == NULL)
          compiler->last_error = ERROR_INSUFFICIENT_MEMORY;

        fail_if(compiler->last_result != ERROR_SUCCESS);

        fixup->address = jmp_destination_addr;
        fixup->next = compiler->fixup_stack_head;
        compiler->fixup_stack_head = fixup;
```

If ``yr_malloc()`` fails to allocate memory, ``compiler->last_error`` is set, ``fail_if(compiler->last_result != ERROR_SUCCESS);`` does not return (because ``last_result`` has not been modified), and ``fixup`` is dereferenced, which leads to a NULL pointer dereference. What is the difference between ``compiler->last_error`` and ``compiler->last_result``? Which one should be used here?

For information, I found this inconsistency while analyzing libyara's code with clang's static analyzer.

**Comment by plusvic** [comment]
Thank you for reporting this issue. In this case it should be setting `compiler->last_result = ERROR_INSUFFICIENT_MEMORY`, `compiler->last_error` should be modified only by yyerror. The idea is that `compiler->last_result` holds the result for that latest operation, no matter if it was an error or not, and `compiler->last_error` holds the last actual error. 

However, looking in retrospective I think this is confusing, I'll see if I can get rid of `compiler->last_error` altogether.

> For information, I found this inconsistency while analyzing libyara's code with clang's static analyzer.

Interesting, I use coverity and it didn't find this. I'll take a look to clang's static analyzer.
