### ISSUE TITLE
Hex string with alternatives fails to compile in yara-3.7.0, but compiles with yara-3.3.0 compiler

### ISSUE THREAD

**Issue by vadim015** [VirusTotal/yara#911]
Not positive that this is the right place to raise this issue, but I hope someone can provide the input on why the following hex string would compile fine with yara-3.3.0 compiler, but failed compilation with yara-3.7.0 compiler:

```
$connect = {
C7 [3] 01 00 00 00 8B [6] C7 [3] 00 00 20 03 5? 89 [3] ( FF 15 [4] | E8 [4] ) 6A 06 6A 01 6A 02 66 [4] 66 [4] 02 00 ( FF 15 [4] | E8 [4] ) 83 F8 FF 89 [2] 0F 84 [4] [0-7] 8D [3] 6A 04 5? 68 02 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [4] ) 8B [2] 8D [3] 6A 04 5? 68 01 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [4] )
}
```

The error from the compiler is:

`error: invalid hex string "$connect": syntax error, unexpected '|', expecting _BYTE_ or _MASKED_BYTE_ or '(' or '['`

Thanks in advance!

**Comment by aschuster99** [comment]
The last element in an alternative must not be a jump. So instead of
`$not_ok_1 = { ( FF 15 [4] | E8 [4] ) 6A 06 6A 01 } `
you may simply move the jump out of the term in round brackets
`$ok_1 = { ( FF 15 | E8 ) [4] 6A 06 6A 01 } `

There is another term in your example that needs a slightly different approach:
`$not_ok_2 = { ( FF 15 | E8 [4] ) 8B [2] 8D [3] 6A 04 }`
You can replace that 4 byte jump with a three byte jump plus a one byte wildcard: 
$ok_2 = { ( FF 15 | E8 [3] ?? ) 8B [2] 8D [3] 6A 04 }`

It may look strange and is harder to read, but works. So, the problem seems to be somewhere in the grammar.

Tested with version 3.7.1.

**Comment by vadim015** [comment]
Andreas,

Thank you so much for the quick answer! You suggested changes worked! The modified string below compiles without a problem using yara-3.7.0 compiler:

```
$connect = {
C7 [3] 01 00 00 00 8B [6] C7 [3] 00 00 20 03 5? 89 [3] ( FF 15 | E8 ) [4] 6A 06 6A 01 6A 02 66 [4] 66 [4] 02 00 ( FF 15 | E8 ) [4] 83 F8 FF 89 [2] 0F 84 [4] [0-7] 8D [3] 6A 04 5? 68 02 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [3] ??) 8B [2] 8D [3] 6A 04 5? 68 01 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [3] ??)
}
```

I wonder though why the jump can't be the last element of the alternative (I don't believe I've seen that restriction in the documentation), and why it was okay in the previous versions of yara (I have tested it with yara-3.1.0 and yara-3.3.0). In my case,it does cause problems after the upgrade from 3.3.0 to 3.7.0.

**Comment by plusvic** [comment]
Same issue described in  #481.

**Comment by wesinator** [comment]
> Andreas,
> 
> Thank you so much for the quick answer! Your suggested changes worked! The modified string below compiles without a problem using yara-3.7.0 compiler:
> 
> ```
> $connect = {
> C7 [3] 01 00 00 00 8B [6] C7 [3] 00 00 20 03 5? 89 [3] ( FF 15 | E8 ) [4] 6A 06 6A 01 6A 02 66 [4] 66 [4] 02 00 ( FF 15 | E8 ) [4] 83 F8 FF 89 [2] 0F 84 [4] [0-7] 8D [3] 6A 04 5? 68 02 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [3] ??) 8B [2] 8D [3] 6A 04 5? 68 01 10 00 00 68 FF FF 00 00 5? ( FF D? | E8 [3] ??)
> }
> ```
> 
> I wonder though why the jump can't be the last element of the alternative (I don't believe I've seen that restriction in the documentation), and why it was okay in the previous versions of yara (I have tested it with yara-3.1.0 and yara-3.3.0). In my case,it does cause problems after the upgrade from 3.3.0 to 3.7.0.

thanks - updating https://github.com/wesinator/Blockbuster-YARA-sigs/blob/56431a4b2eaa5541eed908053a075acda92e9767/YaraSigs/RomeoFoxtrot.yara
