### ISSUE TITLE
Add printf format attribute to yara_yywarning?

### ISSUE THREAD

**Issue by fishilico** [VirusTotal/yara#913]
Hi,
While compiling yara with ``gcc -Wsuggest-attribute=format``, the compiler reports the following warning:
```
lexer.l:762:3: warning: function ‘yara_yywarning’ might be a candidate for ‘gnu_printf’
format attribute [-Wsuggest-attribute=format]
```

Would it be acceptable to add this attribute, for example with the following patch?
```diff
--- a/libyara/include/yara/lexer.h
+++ b/libyara/include/yara/lexer.h
@@ -127,7 +127,7 @@ void yyerror(
 void yywarning(
     yyscan_t yyscanner,
     const char *message_fmt,
-    ...);
+    ...) __attribute__((format(printf, 2, 3)));
 
 void yyfatal(
     yyscan_t yyscanner,
```

This will help catching issues in format string usages when ``yara_yywarning`` is called (there are currently no such issues, but they might be introduced in the future).

**Comment by plusvic** [comment]
Good idea, just make sure it will compile with compilers that don't support that.
