### ISSUE TITLE
Memory leak found by static analyzer?

### ISSUE THREAD

**Issue by 360CodeSafe** [VirusTotal/yara#917]
Hi all,
This is Qihoo360 CodeSafe Team, we found a memory leak issue in `yara`.

The return value of `yy_scan_string()` is the new allocated memory, see https://github.com/VirusTotal/yara/blob/27e385271f9084a2c127f2ca5aaab8e800f6884c/libyara/hex_lexer.c#L2453. The call chain is `yy_scan_string()` -> `yy_scan_bytes()` -> `yy_scan_buffer()` -> `yyalloc()` -> `malloc()`, the address of new allocated memory is returned in the reverse order of the call chain. If I didn't miss anything, there may be a memory leak.

Can you guys help me to confirm this!

Thanks in advance!

**Comment by plusvic** [comment]
It certainly looks like a memory leak, but it isn't. The `hex_lexer.c` file is automatically generated by [bison](https://en.wikipedia.org/wiki/GNU_bison) and its code is a bit convoluted . In `yy_scan_buffer ` the pointer to the buffer is stored in the `YY_BUFFER_STATE` structure. See:

https://github.com/VirusTotal/yara/blob/27e385271f9084a2c127f2ca5aaab8e800f6884c/libyara/hex_lexer.c#L2002

Then `yr_scan_bytes` takes ownership of the buffer in:
 
https://github.com/VirusTotal/yara/blob/27e385271f9084a2c127f2ca5aaab8e800f6884c/libyara/hex_lexer.c#L2009

The buffer is finally freed in:

https://github.com/VirusTotal/yara/blob/27e385271f9084a2c127f2ca5aaab8e800f6884c/libyara/hex_lexer.c#L1765
