### ISSUE TITLE
compile in debian 9 with mingw-w64

### ISSUE THREAD

**Issue by chenzhongxiang** [VirusTotal/yara#933]
Hello:
        I want to compile version 3.8.0 to windows 64 with mingw-w64 in debian 9, but I have encountered these errors:
```
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
copying selected object files to avoid basename conflicts...
x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/root/yara-3.8.0/libyara'
make[1]: Leaving directory '/root/yara-3.8.0/libyara'
make[1]: Entering directory '/root/yara-3.8.0'
  CC       args.o
  CC       threading.o
  CC       yara.o
  CCLD     yara.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/root/openssl/lib:/root/openssl/bin:/root/yara-3.8.0/libyara/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
  CC       yarac.o
  CCLD     yarac.exe
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/root/openssl/lib:/root/openssl/bin:/root/yara-3.8.0/libyara/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
make[1]: Leaving directory '/root/yara-3.8.0'
```

My build configuration：
```
./configure --host=x86_64-w64-mingw32 --disable-magic --disable-cuckoo --with-crypto CFLAGS=-I/root/openssl/include LDFLAGS=-L/root/openssl/lib --enable-static && make
```

Finally I got the bad executable,Execute on Windows without errors but without any output.
File list:
```
-rwxr-xr-x 1 root root  37376 Aug 11 20:05 yara.exe
-rwxr-xr-x 1 root root  37376 Aug 11 20:05 yarac.exe

yara.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
yarac.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

Running in windows
```
C:\Users\l0stc0mpass\Downloads>.\yara.exe

C:\Users\l0stc0mpass\Downloads>.\yarac.exe

C:\Users\l0stc0mpass\Downloads>
```
What should I do next? Please!

**Comment by hillu** [comment]
The executables are only simple wrapper programs that are generated by libtool so you can run them from the build directory. (On Unix systems those would be shell scripts.). The actual executables are placed in the `.lib` subdirectory. Running `make install` will install the executables and libraries into the prefix you specified when calling `configure`.

**Comment by chenzhongxiang** [comment]
Thank you for your help, I did not solve this issue. but based on the latest version 3.8.1 I used the mingw-w64 carried by msys2 to successfully compile the correct executable file and libs in Windows 7 x64. So I closed this issue.

**Comment by x1a0zu1** [comment]
> 感谢您的帮助，我没有解决此问题。但是基于最新版本3.8.1，我使用了msys2附带的mingw-w64在Windows 7 x64中成功编译了正确的可执行文件和库。所以我关闭了这个问题。



> Thank you for your help, I did not solve this issue. but based on the latest version 3.8.1 I used the mingw-w64 carried by msys2 to successfully compile the correct executable file and libs in Windows 7 x64. So I closed this issue.

老哥，能提供下WIN下的编译命令吗 不胜感谢

**Comment by x1a0zu1** [comment]
> Thank you for your help, I did not solve this issue. but based on the latest version 3.8.1 I used the mingw-w64 carried by msys2 to successfully compile the correct executable file and libs in Windows 7 x64. So I closed this issue.

老哥，能提供下WIN下编译的命令吗，不胜感谢

**Comment by chenzhongxiang** [comment]
> > Thank you for your help, I did not solve this issue. but based on the latest version 3.8.1 I used the mingw-w64 carried by msys2 to successfully compile the correct executable file and libs in Windows 7 x64. So I closed this issue.
> 
> 老哥，能提供下WIN下编译的命令吗，不胜感谢

Sorry i'm late.The latest version (v3.11.0) provides visual studio solution files, so you can easy compile the executable file on Windows.
