### ISSUE TITLE
UNDEFINED overrides existing enum in the project causing compilation problems

### ISSUE THREAD

**Issue by teoring** [VirusTotal/yara#935]
This is rather a suggestion for an improvement than an "issue" but still.

Because of the next define in `./include/yara/exec.h`

`#define UNDEFINED           0xFFFABADAFABADAFFLL
`

You are no more allowed to declare an UNDEFINED enum value in a scoped enum class after the include of the yara.h header.

**Comment by plusvic** [comment]
Fixed in 429fb69efaac38cbb02e4993328769a66f6126ed
