### ISSUE TITLE
Similar rule with different results

### ISSUE THREAD

**Issue by securitykitten** [VirusTotal/yara#939]
I'm not sure if this is intended behaviour or not (a bug).  I have 2 separate rules, both of which should be accomplishing the same thing, but I'm getting different results.  There is no logical differences in the rules, in the second one I'm using an iterator and in the first one I am not.

Testing by running against the following file: https://www.virustotal.com/#/file/273b1c28b1b0b09970ee6e489ee8660f6995a3d30cd9d6c32b9257efa3735b37/detection

Consider the following rule, just simply looking at the offsets for a filename within a zip to see if they contain ".class"
```
rule zip_contains_class {
    strings:
        $header = { 50 4b 03 04 }
        $class_file = ".class" nocase
    condition:
        for any of ($header*) : ( $class_file in (@+30 .. @+30+uint16(@+26)))
}
```

When running this rule against the jar file I notice that the condition does not flag as true.  
```
$ yara rule.yar 273b1c28b1b0b09970ee6e489ee8660f6995a3d30cd9d6c32b9257efa3735b37.jar 
$
```

However re-writing the rule to the following (same logic, just using an iterator)
```
rule zip_contains_class {
strings:
        $header = { 50 4b 03 04 }
        $class_file = ".class" nocase
condition:
        for any i in (1 .. #header) : ( $class_file in (@header[i]+30..@header[i]+30+uint16(@header[i]+26)))
}
```
Now an alert will trigger
```
$ yara rule.yar 273b1c28b1b0b09970ee6e489ee8660f6995a3d30cd9d6c32b9257efa3735b37.jar 
zip_contains_class 273b1c28b1b0b09970ee6e489ee8660f6995a3d30cd9d6c32b9257efa3735b37.jar
```

I was under the assumption that these rules achieve the same result, however it would seem that the first variant of the rule does not trigger on what it's intended to.  Is this expected behaviour?

**Comment by wxsBSD** [comment]
I could be wrong here, as I haven't tested this but I think loops and string sets don't work like you think they do in the first example. In that example you are saying for each string where the identifier starts with `$header` (so basically just `$header`) see if $class_file is in a range that starts at the first instance of `$header + 30` and goes until the first instance of `$header + 30 + uint16(...`. Essentially, the `@` will only look at the first instance of `$header`. It would look at the first instance of `$header1` if it existed.

The proper way to do this is the second example you have. You are confusing a loop over a string set (first example) with a loop over a range (second example).

**Comment by securitykitten** [comment]
Perfect @wxsBSD that's what I was guessing.  Thanks for the clarification and comments.  I can close this as it's a non-issue and intended behaviour.
