### ISSUE TITLE
Yara Scanning File in Memory.

### ISSUE THREAD

**Issue by felipeSynus** [VirusTotal/yara#954]
Hi Guys. I have a issue, i hope someone already did it.

I have a socket. This socket receive a base64 file, then decode this file to binary.
My service don't write this file to the Disk to get a better performance as possible.

I want use Yara to compare a rules file with this file received by socket in b64, decoded to Binary in memory. Other services runs as well with BytesIO library, as OCR system. But it don't work with Yara.

Someone use Yara Rules to Match with a File in Bytes on the memory ?
How it can be done ?

**Comment by wroersma** [comment]
I would recommend checking out volatility as it sounds like this is what you're looking for https://github.com/volatilityfoundation/volatility/wiki/Command-Reference-Mal#yarascan

**Comment by plusvic** [comment]
The C API has [yr_rules_scan_mem](https://yara.readthedocs.io/en/v3.7.0/capi.html#c.yr_rules_scan_mem) for scanning a memory buffer. In `yara-python` you can do:

```
import yara
rules = yara.compile(sources=<string with YARA rules>)
matches = rules.match(data=<string with data to be scanned>)
```
