### ISSUE TITLE
Redundant XOR compare code for ascii strings?

### ISSUE THREAD

**Issue by sysopfb** [VirusTotal/yara#963]
The atom list is being built out with new atoms for every possible XOR key for the atom to the entire atom length meaning the entire string. 

/libyara/atoms.c#L683

```
while (atom != NULL)
  {
    for (j = 1; j <= 255; j++)
    {
      new_atom = (YR_ATOM_LIST_ITEM*) yr_malloc(sizeof(YR_ATOM_LIST_ITEM));

      if (new_atom == NULL)
        return ERROR_INSUFFICIENT_MEMORY;

      for (i = 0; i < atom->atom_length; i++)
        new_atom->atom[i] = atom->atom[i] ^ j;

      new_atom->atom_length = yr_min(atom->atom_length, YR_MAX_ATOM_LENGTH);
      new_atom->forward_code = atom->forward_code;
      new_atom->backward_code = atom->backward_code;
      new_atom->backtrack = atom->backtrack;
      new_atom->next = *xor_atoms;

      *xor_atoms = new_atom;
    }

    atom = atom->next;
}
```

Doesn't this make special xor compare functions redundant for ascii strings? The full xor atoms already exist so why perform extra XOR operations for every xor atom?

/libyara/scan.c#L79
```
k = *s1 ^ *s2;

  while (i < string_length && *s1++ == ((*s2++) ^ k))
i++;
```

Can't you just leave this up to the normal compare operations since the full atom list already exists or is there some short circuiting going on that I missed?
The only thing I see that might need special compare would be a string with both wide and xor, although you could technically add another 255 atoms for wide strings and use the normal compare function with that '_yr_scan_compare'?

**Comment by wxsBSD** [comment]
I'm not sure I understand your question. The second snippet you mention is during the verification of a string literal match, and we have to do the xor because we do not know what the xor value was for that particular atom which caused the potential match in the first place.

**Comment by plusvic** [comment]
> The atom list is being built out with new atoms for every possible XOR key for the atom to the entire atom length **meaning the entire string**.

The highlighted assumption is incorrect. If you have a long string (longer than YR_MAX_ATOM_LENGTH) the atoms extracted from the string don't cover the whole string. Suppose your string is "foobarbaz", for a plain ascii string the atom will be "foob" (assuming the default YR_MAX_ATOM_LENGTH = 4), for a xored string additional atoms will be added with "foob" xored with 0x01, up to 0xFF. But those atoms don't cover the "arbaz" part of the string. Once you find "foob" or any of its xored variants, you need to use the `_yr_scan_xor_compare` function for making sure that you found a match.

**Comment by sysopfb** [comment]
Ah I missed the short circuit logic, thanks Victor!
