### ISSUE TITLE
Zero length array not supported in other programming languages.

### ISSUE THREAD

**Issue by Paintkiller2012** [VirusTotal/yara#965]
Find way to replace zero length array of uint8_t in [struct RE](https://github.com/VirusTotal/yara/blob/3b4d5133a3fed6b9e0cf6bcff25f8e15eedc66e4/libyara/include/yara/types.h#L431) and single element array of char in [struct SIZED_STRING](https://github.com/VirusTotal/yara/blob/3b4d5133a3fed6b9e0cf6bcff25f8e15eedc66e4/libyara/include/yara/sizedstr.h#L55) to uint8_t* and char*.
That structs passed as parameter when invoking modules functions.

**Comment by plusvic** [comment]
Can you provide more details about what do you want to achieve? Do you want to write modules in other programming languages and link them into YARA?
