### ISSUE TITLE
access violation in dotnet module

### ISSUE THREAD

**Issue by CaldurG** [VirusTotal/yara#967]
access violation occurs while scanning file https://github.com/CaldurG/yara/blob/yplsml/tests/dotnet.av It is in dotnet_parse_tilde_2 function when accessing memberref_row.

Rules:
```
import "dotnet"

rule test {
  strings:
    $ = "test"
  condition:
    all of them
}
```

**Comment by plusvic** [comment]
Duplicate of #970
