### ISSUE TITLE
Question: trying to create a nice wrapper for libyara - yr_finalize_thread is confusing

### ISSUE THREAD

**Issue by DaniCybereason** [VirusTotal/yara#968]
This API is barely documented and I am unclear as to why and when a thread must call it.
The only line I found is:

> In a multi-threaded program only the main thread must call yr_initialize() and yr_finalize(), but any additional thread using the library must call yr_finalize_thread() before exiting.

I am trying to create a nice wrapper for which code would look like:
```
allocate_yara(rules) // main thread does this once to be efficient
scan_mem(rules, memory) // multiple loops/threads call this
free_yara(rules) // main thread calls this only
```

And the threading related API is the only thing that is confusing me - since only the main thread calls yr_initialize and only once, why must each thread call finalize_thread? can I somehow elegantly add it to my fantasy API?
or must each thread I know to use yara now now contain "yr_finalize_thread()" as it's last line in it's 'ThreadFunc' ??

I don't expect each consumer of my wrapper to magically know they must call a cleanup function at the end of their thread..

I don't know if free_yara is the last time a thread uses the wrapper, since it might allocate and compile rules multiple times.

Must each thread now add a CRT-style management of memory at it's end? or can I call yr_finalize_thread on each completion and it would work fine the next time a thread (or same thread) wants to use libyara?

**Comment by DaniCybereason** [comment]
sorry, double post because of the github event.. it showed as if issue was not opened.

**Comment by plusvic** [comment]
`yr_finalize_thread` is deprecated since version 3.8.0 and is not needed anymore if you are using a recent YARA version.
