### ISSUE TITLE
access violation in dotnet module

### ISSUE THREAD

**Issue by CaldurG** [VirusTotal/yara#970]
There is an access violation in dotnet module when scanning file https://github.com/CaldurG/yara/blob/yplsml/tests/dotnet.av

```
import "dotnet"

rule test {
  strings:
    $ = "test"
  condition:
    all of them
}
```

**Comment by wxsBSD** [comment]
I can not replicate this. Can you please provide more details? What version of YARA are you using?

**Comment by CaldurG** [comment]
I am using latest yara (3.8.1) on windows. It also crashes in latest yara python (pip install yara-python) on windows. Crash is on line 770 in dotnet.c `if ((*(WORD*) memberref_row & 0x07) != 0x01)`

**Comment by wxsBSD** [comment]
I've checked this with v3.8.1 on OS X and can not replicate it. I don't have a Windows environment handy to build on, so I can't replicate it there. Would you be able to build this on something other than Windows and test it? I don't see how that can make a difference but it wouldn't hurt to rule it out...

**Comment by wxsBSD** [comment]
Also, the sha256 of dotnet.av is `d4191c3b8e8ebe1ea82590d5db913fe694a4c5b4090e8bff5e6bf9a0e27f3e3c` right? Just want to make sure it didn't get mangled on the way down to me.

**Comment by CaldurG** [comment]
sorry I don't have other environment. Your hash is correct. I wanted to download latest compiled yara binary for windows, but the download is broken :( So I downloaded latest sources from github, placed them to a separate directory and compiled yara from there. Access violation is still there in both 32 and 64bit builds.

Have you used the rules from the first post? Basically anything that that contains import "dotnet" should work, but just in case :)

**Comment by wxsBSD** [comment]
Yes, I used the rules from the first post. I’m unable to replicate this still. I wonder if anyone else can try this out?

**Comment by plusvic** [comment]
@CaldurG the Windows binaries should be at: https://www.dropbox.com/sh/umip8ndplytwzj1/AADdLRsrpJL1CM1vPVAxc5JZa?dl=0&lst=

Are you able to download them from there? Check if it crashes with those binaries too?

I'm traveling now, but I'll try to reproduce the issue when I get back home and have access to a Windows VM.

**Comment by CaldurG** [comment]
Thx for the download link. I checked with your binaries and it crashed on both 32 and 64bit versions.

yara64.bat
```
@yara64.exe dotnet.yar dotnet.av
@echo return_value=%errorlevel%

>yara64.bat
return_value=-1073741819
```

yara32.bat
```
@yara32.exe dotnet.yar dotnet.av
@echo return_value=%errorlevel%

>yara32.bat
return_value=-1073741819
```

-1073741819 -> 0xC0000005 should be access violation error

**Comment by CaldurG** [comment]
Hi, were you able to reproduce this? Is there some progress?

**Comment by plusvic** [comment]
Unfortunately not :(

**Comment by CaldurG** [comment]
look at line 746 in dotnet.c
I added "if not fits_in_pe then break" part and it will break on this condition while scanning dotnet.av file. So memberref_row is pointing to memory that is not allocated.

```
if (type_index > 0)
  type_index--;

// Now follow the Type index into the MemberRef table.
memberref_row = memberref_ptr + (memberref_row_size * type_index);
if (!fits_in_pe(pe, memberref_row, memberref_row_size))
  break;

if (index_sizes.memberref == 4)
```
