### ISSUE TITLE
YR_BUILDING_DLL does not seem to be working on v3.8.1 (manual dllexport on v3.7.1 works)

### ISSUE THREAD

**Issue by DaniCybereason** [VirusTotal/yara#971]
I created an empty dllmain.cpp and defined YR_BUILDING_DLL before including yara.h in any place at all.
when basing this small project on v3.7.1 (and forcing YR_API to be declspec(dllexport) myself), it compiles fine and DLL seems to export all the YR_API functions.

when I did the same base on v3.8.1, I got a DLL with absolutely no exports.
Even when I define
`YR_API int yr_initialize();`
myself in my dll, and add just for sanity another line:
`YR_API int yr_initialize_test() {}`

the _test is exported whereas yr_initialize is not...

Was something done to affect DLL building besides creating the define for dllexport?
What is the YR_BUILDING_STATIC_LIBC and YR_BUILDING_STATIC_LIB in release/debug configurations accordingly? could this affect the situation?

**Comment by DaniCybereason** [comment]
I think I figured out what happened, before the change that added YR_BUILDING_DLL, the symbols were by default compiled with __declspec(dllexport), whereas now they are defined without it.
This seems to cause the compiler to use the declaration in the obj files that are in libyara.lib instead of treating the other obj files also and deciding to export.

I'm still not sure why this is a problem, will update if I have time to figure out.
For now I will just compile the whole thing with libyara.vcxproj having preprocessor YR_BUILDING_DLL to save the whole trouble...

**Comment by plusvic** [comment]
Yes, you should build the DLL by adding YR_BUILDING_DLL to libyara.vcxproj, this way all the exported functions are decorated with `__attribute_((dllexport))`. In the project that uses the DLL you must use YR_IMPORTING_DLL. See the comment for this commit: https://github.com/VirusTotal/yara/commit/39602514e2c7aa990d4d361adbd9a89bdfd147dd

More context in https://github.com/VirusTotal/yara/issues/601

**Comment by DaniCybereason** [comment]
Is it not possible to use the same lib for both building a dll and a static
exe? It used to work both ways..

**Comment by DaniCybereason** [comment]
I want the libyara to be possible to be used as a static lib and when I
want to use it to export from a dll all the symbols.
On 3.7.1 I had the libyara compiled to a lib, then any project linking with
it could decide whether to statically link or dll export, or dll import.
All depending on the project settings.

It's very strange that the libyara is the one who defines whether symbols
are exported since dll export should be possible to add later too, and it
worked on 3.7.1. Very strange..
