### ISSUE TITLE
Unexpected behaviour when specifying wildcard for FILE argument

### ISSUE THREAD

**Issue by wesinator** [VirusTotal/yara#974]
yara 3.8.1

**Steps to reproduce:**
 * `yara ../rule.yara [FilesDir]/*.exe`
FilesDir or current dir contains multiple files to check against.

**Expected:** Enumerates the files, checking the rule against each one.

**Actual:** Seems to enumerate the files in the directory, but it interprets the first executable as a rule file:
```
file.exe(1): error: syntax error, unexpected _IDENTIFIER_
file.exe(1): error: non-ascii character
```
If wildcards are not supported, why would it still be reading the first file?

**Comment by plusvic** [comment]
You are probably using a bash shell, right?. In that case when you use a wildcard the shell expands the wildcards and pass the actual file names to the program. So, if you have `file1.exe`, `file2.exe` and `file3.exe` when you do `yara ../rule.yara *.exe` it's exactly like doing: 

```
yara ../rule.yara file1.exe file2.exe file3.exe
```
YARA interprets all the arguments, except the last one, as files containing rules. So, it will try to scan file3.exe with rules contained in `rule.yara`, `file1.exe` and `file3.exe`. YARA doesn't expand wildcards by itself.

**Comment by wesinator** [comment]
Ah, ok. Yes, this is in bash

**Comment by mstc-xqp** [comment]
time ./yara yara_rule3.yr 1ec7c393cbb96e84531c34d5ef9c2470cac3ee97_44b7d352y026ef7177875a6cb619d638f.apk
yara_rule3.yr(1): error: syntax error, unexpected identifier
yara_rule3.yr(1): error: non-ascii character

real	0m0.012s
user	0m0.008s
sys	0m0.003s
