### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by Tigzy** [VirusTotal/yara#976]
Is Yara scanner supposed to be thread safe?
I have numerous cases where scanning file (disk) or reading rule data -with multiple workers- leads to stack corruption. 
Just making sure I'm not using it wrong.

**Comment by plusvic** [comment]
Yes, it's supposed to be thread-safe. Can you provide more info about your issues?

**Comment by Tigzy** [comment]
Thanks. Not yet, I'm using an old Yara version (3.7.1 I think) and I'll upgrade first see what happens.
I just wanted to make I don't investigate in the wrong direction...

**Comment by Tigzy** [comment]
The only thing I know is that it randomly crashes on memory access around a yr_rules_scan_fd call

**Comment by Tigzy** [comment]
Is this guaranteed that the context pointer passed when calling multiple yr_rules_scan_fd from different threads will not be mixed and uses a different storage per call?

**Comment by Tigzy** [comment]
Ok closing for now. I've updated to the latest and I have less crashes. But still some that I'll submit in another topic.
