### ISSUE TITLE
Repository blocked by Windows Defender 

### ISSUE THREAD

**Issue by LloydLabs** [VirusTotal/yara#982]
When downloading the entire repository via the `Download as ZIP` functionality it's being classed as `MSIL/Curshide.A!bit`.

As a result, users with Windows Defender enabled are being blocked from cloning the repository.

Obviously just a false positive.

![alert](https://i.imgur.com/nZqfPk1.png)

**Comment by Joseph-Tortorelli** [comment]
SNORT was recently blocked from me for some reason. I was getting just about the same message. This is weird. Is there something malicious in the repository you think.

**Comment by LloydLabs** [comment]
@Joseph-Tortorelli seems as if it's the `foo.exe` within that file triggering all of the false positives for this. Very strange behaviour, but seems to be associated with a multitude of malware families so makes sense.

**Comment by plusvic** [comment]
That file was put in the repository as part of the starting corpus for oss-fuzz. I'm going to remove it because it seems to be causing trouble.

**Comment by plusvic** [comment]
The offending file has been removed.
