### ISSUE TITLE
Add a rule testing option (-t)

### ISSUE THREAD

**Issue by wesinator** [VirusTotal/yara#984]
Add a `-t` command line option for rule testing, that would take just the `RULES_FILE` argument and test the given rule file(s) for rule syntax errors.

**Use case:** Quickly test rules for invalid syntax without needing to give a file argument or run on a file.

**Comment by plusvic** [comment]
I would use yarac for this as @wxsBSD proposes. If you don't want yarac to generate the output file we can add a flag to yarac that prevents the compiled file to be written.

**Comment by wesinator** [comment]
@plusvic That sounds good, thanks.

**Comment by plusvic** [comment]
The syntax for yarac is:

```
yarac [OPTION]... [NAMESPACE:]SOURCE_FILE... OUTPUT_FILE
```

It accepts multiple source files and uses the last argument as the output file. The output file can't be made optional without changing the arguments format in a backward-incompatible way. Adding a flag for ignoring the output file while being forces to specify a file is a bit weird. Using `/dev/null` sounds like an acceptable solution (at least in OSes that have it):

```
yarac rules.yar /dev/null
```
