### ISSUE TITLE
syntax error, unexpected '?'

### ISSUE THREAD

**Issue by redux-project** [VirusTotal/yara#985]
Getting syntax error with the "?" added. Any advice? 

Error

`invalid regular expression "$addr": syntax error, unexpected '?'`

Rule

```
rule	btc	{	
    strings:		
    $key = /(L|K)[0-9A-Za-z]{51}/
    $addr = /[1-9a-zA-z]{34}(?!OIl)/	
    condition:	
    any of them	
}
```

Version is

```
yara:
  Installed: 3.4.0+dfsg-2build1
  Candidate: 3.4.0+dfsg-2build1
  Version table:
 *** 3.4.0+dfsg-2build1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by plusvic** [comment]
YARA's regexps don't support lookaheads because they can be supported only by backtracking. Although YARA doesn't use RE2, this can be applied to YARA too: https://github.com/google/re2/wiki/WhyRE2
