### ISSUE TITLE
use a fixed expression inside an expression

### ISSUE THREAD

**Issue by SofiaArancibia** [VirusTotal/yara#988]
Hi!
I want to declare a constant like:

EXP = ".+"

and want to use it, for instance, as follows, in every rule I write:

...
strings:
	$event = /eventType:\"Process Created\"**EXP**cmdLine:**EXP**ne(t|t.exe|t1|t1.exe)\suse\s\\\\\\\\**EXP**\\\\(admin|c)$\s{,5}/delete/
		
condition:
	$event
}

Quiero evitar las repeticiones para simplificar las modificaciones. Quiero decir, solo quiero modificar la variable y no todas las reglas donde se usa la expresión.

How can I do this?

Thanks!

**Comment by plusvic** [comment]
Lo que propones no está soportado, desafortunadamente no queda otra opción que repetir esas expresiones.
