### ISSUE TITLE
Windows Binaries Download link from Documentation Broken

### ISSUE THREAD

**Issue by CmdrBurrito** [VirusTotal/yara#993]
Hi, hate to bother you again regarding this issue, but the link to download the Yara windows binaries appears to be broken again (yields 404 error). The link is:
https://b161268c3bf5a87bc67309e7c870820f5f39f672.googledrive.com/host/0BznOMqZ9f3VUek8yN3VvSGdhRFU/

Regards!

**Comment by CmdrBurrito** [comment]
> Where is that link? I can't find it in the current documentation.

https://yara.readthedocs.io/en/v3.4.0/gettingstarted.html#installing-on-windows

There's a link there in the "Installing on Windows" section named "Download Windows binaries".  When you click on it, you get directed to the URL listed above which generates a 404 error.  Thanks!

**Comment by plusvic** [comment]
Oh, I see, but that's an old version. The latest one is: https://yara.readthedocs.io/en/v3.8.1/

**Comment by CmdrBurrito** [comment]
> Oh, I see, but that's an old version. The latest one is: https://yara.readthedocs.io/en/v3.8.1/

Ah, I see.  Got it.  Thanks!
